// Builds the deployable files from src/:
//   public/index.html   the game page (served by the Worker)
//   src/engine.gen.js   the rules engine as an ES module for the server
//   build/artifact.html the same page for publishing as a claude.ai artifact (local play only)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
const r = f => readFileSync(new URL(f, import.meta.url), 'utf8');
const engine = r('./src/engine_data.js') + '\n' + r('./src/engine_rules.js') + '\n' + r('./src/engine_bot.js');
const ui = ['ui_state.js', 'ui_sound.js', 'ui_art.js', 'ui_view.js', 'ui_online.js', 'ui_boot.js'].map(f => r('./src/client/' + f)).join('\n');
const shell = r('./src/client/shell.html');
const script = `<script>\n(()=>{\n'use strict';\nconst $=s=>document.querySelector(s);\n${engine}\n${ui}\n})();\n</script>\n`;
const body = shell + '\n' + script;
mkdirSync(new URL('./public/', import.meta.url), { recursive: true });
mkdirSync(new URL('./build/', import.meta.url), { recursive: true });
writeFileSync(new URL('./public/index.html', import.meta.url),
  `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">\n<meta name="theme-color" content="#0a1310">\n<meta name="mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">\n<meta name="apple-mobile-web-app-title" content="El Dorado">\n</head>\n<body>\n${body}</body>\n</html>\n`);
writeFileSync(new URL('./build/artifact.html', import.meta.url), body);
writeFileSync(new URL('./src/engine.gen.js', import.meta.url),
  `// GENERATED by build.mjs from engine_data.js + engine_rules.js. Do not edit.\n${engine}\nexport const E={botClone,botRandomCourse,botNetFeatures,botNetNF,botNetValue,botChoose,botTurn,botActions,botFeatures,botValue,endGame,BOT_NF,setNet(n){BOT_NET=n},buildCourse,mapFor,COURSES,courseById,newGame,applyAction,resign,eloDeltas,redact,reach,payTargets,nativeTargets,playerDone,CT,get S(){return S},set S(v){S=v},get MAP(){return MAP},set MAP(v){MAP=v}};\n`);
console.log('built public/index.html, src/engine.gen.js, build/artifact.html');
