// Builds the deployable files from src/:
//   public/index.html   the game page (served by the Worker): the start screen, plus a hashed CSS file and a hashed script
//   src/engine.gen.js   the rules engine as one ES module (the server, the AI tools and the page all import it)
//   build/artifact.html the same page for publishing as a claude.ai artifact (local play only, everything inline)
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from 'node:fs';
import { createHash } from 'node:crypto';
import vm from 'node:vm';
import esbuild from 'esbuild';
const r = f => readFileSync(new URL(f, import.meta.url), 'utf8');
const engine = r('./src/engine_data.js') + '\n' + r('./src/engine_rules.js') + '\n' + r('./src/engine_bot.js') + '\n' + r('./src/engine_ai.js');
// every top-level name of the engine is exported by name (the page's modules import names; the server, the tools and
// the tests import the whole engine as a namespace, E). Found by running the engine and asking
// the JavaScript engine which of its identifiers are global variables (exact: no parsing of our own)
const topNames = (() => {
  const ids = [...new Set(engine.match(/[A-Za-z_$][\w$]*/g))];
  const defined = ctx => vm.runInContext(`${JSON.stringify(ids)}.filter($$id=>{try{return eval('typeof '+$$id)!=='undefined'}catch(e){return false}})`, ctx);
  const ctx = vm.createContext({ console }); vm.runInContext(engine, ctx);
  const builtins = new Set(defined(vm.createContext({}))); // (what any script sees: globals, and Object.prototype's names such as constructor)
  return defined(ctx).filter(n => !builtins.has(n) && !/^(this|null|true|false|console)$/.test(n));
})();
writeFileSync(new URL('./src/engine.gen.js', import.meta.url),
  `// GENERATED by build.mjs from engine_data.js + engine_rules.js + engine_bot.js + engine_ai.js. Do not edit.\n${engine}\n`
  + `// every name (live bindings), and setters for the game on show\nexport {${topNames.join(',')}};\nexport const setS=v=>{S=v},setMAP=v=>{MAP=v};\n`);
const E = await import(new URL('./src/engine.gen.js?' + Date.now(), import.meta.url));
// the start screen's lists are written into the page from the engine's data, so it needs no script to show
const esc = t => String(t).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const card = (name, id, b, sub, on) => `<label data-v="${id}"><input type="radio" name="${name}" value="${id}"${on ? ' checked' : ''}><b>${b}</b><span>${esc(sub)}</span></label>`;
const courses = name => E.COURSES.map(c => card(name, c.id, esc(c.name) + (c.diff ? ` <i class="dtag d-${esc(c.diff.toLowerCase())}">${esc(c.diff)}</i>` : ''), 'Boards ' + c.p.map(x => x[0]).join(' · '), c.id === 'first')).join('')
  + (E.COURSES.length > 1 ? card(name, 'random', 'Random course', 'Any course from this list', false) : '');
const COLS = ['crimson', 'ivory', 'violet', 'orange'], sw = (name, i, val) => E.COLORS.map(c => `<label style="--c:${c.hex}" title="${c.name}"><input type="radio" name="${name}" value="${val(c)}"${i >= 0 && c.id === COLS[i] ? ' checked' : ''}${i >= 0 && i < 3 && COLS.slice(0, 3).some((x, j) => j !== i && x === c.id) ? ' disabled' : ''} aria-label="${c.name}"></label>`).join('');
const seats = ['Ana', 'Ben', 'Cleo', 'Dev'].map((nm, i) => `<div class="prow seat" data-i="${i}"${i > 2 ? ' hidden' : ''}><select class="who" name="who${i}" aria-label="Player ${i + 1}: human or AI"><option value="">Human</option><optgroup label="AI players">${E.AIS.map(a => `<option value="${a.id}">${esc(a.name)} · ${esc(a.tier)}</option>`).join('')}</optgroup></select>`
  + `<input name="nm${i}" maxlength="14" value="${nm}" aria-label="Player ${i + 1} name"><div class="ainm" hidden><span></span></div><div class="sws">${sw('col' + i, i, c => c.id)}</div></div>`).join('');
const shell = r('./src/client/shell.html').replace('<!--COURSES:course-->', courses('course')).replace('<!--COURSES:ocourse-->', courses('ocourse')).replace('<!--SEATS-->', seats)
  .replace('<!--AILIST-->', E.AIS.map(a => `<button type="button" data-addai="${a.id}"><b>${esc(a.name)} <span class="aitag">AI</span></b><span>${esc(a.tier)} · ${esc(a.desc)}</span></button>`).join(''))
  .replace('<!--ROOMCOLS-->', sw('rlcol', -1, c => c.hex))
  .replace('<!--ROUTE-->', (M => `Boards <b>${M.route.join(' · ')}</b> · El Dorado (${M.endSym === 'j' ? 'jungle' : 'water'} side) · ${M.blockDefs.length} blockades, dealt at random`)(E.buildCourse(E.courseById('first'), 1)));
/* The design check (docs/DESIGN.md): new UI takes its values from the tokens in shell.html's :root. Counted in the chrome's CSS
   (the tokens themselves and the art rules left out: card faces, deck back, board background) and in the UI scripts (art modules
   left out): raw hex colours, px font sizes, inline styles (style="…" other than custom properties carrying data, --x:…, and
   .style.cssText). What is left from before the tokens is the baseline (src/client/design-baseline.json): a build with more
   anywhere fails; a build with fewer lowers the baseline, so the count only goes down. */
{
  const ART = /^\s*(\.k-|\.c-|\.cface|\.back|#vp|\.mcard|\.card\.dpick)/, ARTJS = /^(art|meeple|cards|icons|train)\.js$|^board\//;
  const HEX = /#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b(?![0-9a-fA-F])/g, FPX = /font-size:\s*[\d.]+px|font:\s*\d+\s+[\d.]+px/g, STY = /style="(?!--)|\.style\.cssText\s*=/g;
  const n = (t, re) => (t.match(re) || []).length, found = {};
  const sh = r('./src/client/shell.html').replace(/\/\*TOKENS\*\/[\s\S]*?\/\*END TOKENS\*\//, '').replace(/<svg width="0"[\s\S]*?<\/svg>/, '');
  const css = [...sh.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map(m => m[1]).join('\n').split('\n').filter(l => !ART.test(l)).join('\n');
  found['shell.html'] = { hex: n(css, HEX), fontpx: n(css, FPX), style: n(sh.replace(/<style[^>]*>[\s\S]*?<\/style>/g, ''), STY) };
  const walk = d => readdirSync(new URL(d, import.meta.url), { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(d + e.name + '/') : [d + e.name]);
  for (const f of walk('./src/client/').filter(f => f.endsWith('.js'))) { const k = f.slice('./src/client/'.length); if (ARTJS.test(k)) continue;
    const t = r(f); found[k] = { hex: n(t, HEX), fontpx: n(t, FPX), style: n(t, STY) }; }
  const BL = new URL('./src/client/design-baseline.json', import.meta.url); let base = {}; try { base = JSON.parse(readFileSync(BL, 'utf8')); } catch (e) { }
  const over = [];
  for (const [k, v] of Object.entries(found)) for (const [kind, c] of Object.entries(v)) { const b = base[k] ? base[k][kind] : 0; if (c > b) over.push(`${k}: ${c} ${kind} (allowed ${b})`); }
  if (over.length) { console.error('design check failed (docs/DESIGN.md: use the tokens in shell.html :root, classes instead of inline styles):\n  ' + over.join('\n  ')); process.exit(1); }
  const lean = Object.fromEntries(Object.entries(found).filter(([, v]) => v.hex || v.fontpx || v.style));
  if (JSON.stringify(lean) !== JSON.stringify(base)) writeFileSync(BL, JSON.stringify(lean, null, 1) + '\n'); // (fewer than before: the baseline goes down)
}
// the AI's neural network (tools/ai/pack.mjs): the site loads it from /ai/first.bin only when an AI needs it;
// the artifact (no network access there) carries it inline
const netBin = readFileSync(new URL('./src/ai/first.bin', import.meta.url));
// the page's script: the modules in src/client bundled into one minified file by esbuild (installed with wrangler)
const bundle = net => esbuild.buildSync({ entryPoints: [new URL('./src/client/main.js', import.meta.url).pathname], bundle: true, format: 'iife',
  minify: !process.env.DEV, target: 'es2020', write: false, define: { AI_NET: JSON.stringify(net) }, logLevel: 'error' }).outputFiles[0].text;
const script = net => `<script>\n${bundle(net)}</script>\n`;
// fonts (Figtree variable 400–800 and Young Serif, Latin subset) are served by the site itself: no render-blocking
// request to another domain; the artifact (no network) gets them embedded
const FONTS = [['Figtree', 'figtree-latin.woff2', '400 800'], ['Young Serif', 'young-serif-latin.woff2', '400']];
const faces = src => '<style>' + FONTS.map(([f, file, w]) => `@font-face{font-family:'${f}';font-style:normal;font-weight:${w};font-display:swap;src:url(${src(file)}) format('woff2')}`).join('') + '</style>';
const siteFonts = faces(f => '/fonts/' + f); // no preload: on a slow phone link it competes with the page itself
const artFonts = faces(f => 'data:font/woff2;base64,' + readFileSync(new URL('./public/fonts/' + f, import.meta.url)).toString('base64'));
const withFonts = (html, fonts) => html.replace('<!--FONTS: build.mjs puts the self-hosted fonts here (preloaded files on the site, embedded in the artifact)-->', fonts);
/* The site's page is split for the first round trip: TCP sends about 14 KB before it waits for the browser, so the page
   itself (the start screen's markup and CSS) stays under that and paints at once; the game's CSS and the script are
   separate files, fetched right after, with names from their contents (cached for good, never stale). */
const minCss = c => esbuild.transformSync(c, { loader: 'css', minify: true }).code;
const LATE = /<style data-late>([\s\S]*?)<\/style>/, late = shell.match(LATE)[1];
const hashed = (ext, text) => { const n = `app.${createHash('sha256').update(text).digest('hex').slice(0, 10)}.${ext}`; writeFileSync(new URL('./public/' + n, import.meta.url), text); return n; };
for (const f of readdirSync(new URL('./public/', import.meta.url))) if (/^app\.[0-9a-f]{10}\.(js|css)$/.test(f)) unlinkSync(new URL('./public/' + f, import.meta.url));
const faceCss = siteFonts.replace(/<\/?style>/g, ''); // the game's fonts are declared in the game's CSS: the start screen never fetches them
const cssFile = hashed('css', minCss(faceCss + late)), jsFile = hashed('js', bundle({ url: '/ai/first.bin' }));
const siteShell = withFonts(shell, '').replace(LATE, '').replace(/<style>([\s\S]*?)<\/style>/, (m, c) => `<style>${minCss(c)}</style>`)
  .replace('</dialog>', `</dialog>\n<link rel="stylesheet" href="${cssFile}">`);
const body = siteShell + `\n<script src="${jsFile}" defer></script>\n`;
mkdirSync(new URL('./public/', import.meta.url), { recursive: true });
mkdirSync(new URL('./build/', import.meta.url), { recursive: true });
mkdirSync(new URL('./public/ai/', import.meta.url), { recursive: true });
writeFileSync(new URL('./public/ai/first.bin', import.meta.url), netBin);
writeFileSync(new URL('./public/index.html', import.meta.url),
  `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">\n<meta name="theme-color" content="#0a1310">\n<meta name="mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">\n<meta name="apple-mobile-web-app-title" content="El Dorado">\n</head>\n<body>\n${body}</body>\n</html>\n`);
writeFileSync(new URL('./build/artifact.html', import.meta.url), withFonts(shell, artFonts) + '\n' + script({ b64: netBin.toString('base64') }));
// the live AI-training page (/train.html): a standalone page, copied as is
writeFileSync(new URL('./public/train.html', import.meta.url), r('./src/client/train.html'));
console.log('built public/index.html, public/train.html, src/engine.gen.js, build/artifact.html');
