// GENERATED by build.mjs from engine_data.js + engine_rules.js. Do not edit.
/* =========================================================
   CARD DATA (base game)
   ========================================================= */
const CT={
  explorer:{n:'Explorer',c:'g',s:'j',p:1},
  traveler:{n:'Traveler',c:'y',s:'v',p:1},
  sailor:{n:'Sailor',c:'b',s:'w',p:1},
  scout:{n:'Scout',c:'g',s:'j',p:2,cost:1},
  trailblazer:{n:'Trailblazer',c:'g',s:'j',p:3,cost:3},
  pioneer:{n:'Pioneer',c:'g',s:'j',p:5,cost:5},
  giant:{n:'Giant Machete',c:'g',s:'j',p:6,cost:3,once:1},
  captain:{n:'Captain',c:'b',s:'w',p:3,cost:2},
  photographer:{n:'Photographer',c:'y',s:'v',p:2,cost:2},
  journalist:{n:'Journalist',c:'y',s:'v',p:3,cost:3},
  chest:{n:'Treasure Chest',c:'y',s:'v',p:4,cost:3,once:1},
  millionaire:{n:'Millionaire',c:'y',s:'v',p:4,cost:5},
  jack:{n:'Jack of All Trades',c:'x',s:'*',p:1,cost:2},
  adventurer:{n:'Adventurer',c:'x',s:'*',p:2,cost:4},
  plane:{n:'Prop Plane',c:'x',s:'*',p:4,cost:4,once:1},
  transmitter:{n:'Transmitter',c:'p',cost:4,once:1,txt:'Take any card from the market or reserve for free.'},
  cartographer:{n:'Cartographer',c:'p',cost:4,txt:'Draw 2 cards.'},
  scientist:{n:'Scientist',c:'p',cost:4,txt:'Draw 1 card. You may remove 1 card in hand from the game.'},
  compass:{n:'Compass',c:'p',cost:2,once:1,txt:'Draw 3 cards.'},
  travellog:{n:'Travel Log',c:'p',cost:3,once:1,txt:'Draw 2 cards. You may remove up to 2 cards in hand from the game.'},
  native:{n:'Native',c:'p',cost:5,txt:'Move to an adjacent space, ignoring its requirement. Can tear down a blockade.'},
};
const MARKET0=['scout','trailblazer','jack','photographer','chest','transmitter'];
const RESERVE0=['pioneer','giant','captain','journalist','millionaire','adventurer','plane','cartographer','scientist','compass','travellog','native'];
const SYMNAME={j:'machete',w:'paddle',v:'coin'};
const SYMCOL={j:'#3f9a5c',w:'#3a8ad0',v:'#e7b54d',r:'#a3a8a4'};
const COLORS=[{id:'crimson',hex:'#e5484d',name:'Crimson'},{id:'ivory',hex:'#efe9dc',name:'Ivory'},{id:'violet',hex:'#9d7df7',name:'Violet'},{id:'orange',hex:'#ff9636',name:'Orange'},{id:'teal',hex:'#35d0ba',name:'Teal'},{id:'pink',hex:'#f07ab8',name:'Rose'}];
/* Official base-game blockades are numbered 1–6: jungle, village, rubble, water, jungle, rubble.
   They are placed along the route in number order; the number also breaks ties. */
const BLOCKADES=[{n:1,k:'j',v:1},{n:2,k:'v',v:1},{n:3,k:'r',v:1},{n:4,k:'w',v:1},{n:5,k:'j',v:2},{n:6,k:'r',v:2}];

/* =========================================================
   TERRAIN BOARDS — base game letters. Terrain counts per board match the published
   tile catalogue (A/B start boards, C–N double-sided terrain boards). Space-by-space
   placement is reconstructed; see Rules.
   rows top→bottom (4,5,6,7,6,5,4): jN jungle · wN water · vN village · rN rubble · cN base camp · mm mountain · ss start
   ========================================================= */
const BOARDS={
 A:['j1 j1 v1 j1','j1 w1 j1 j2 j1','j1 w1 mm j1 v1 j1','v1 j1 w1 j1 j1 c1 j1','j1 j1 j1 mm v1 j1','j1 j1 v1 j1 j1','ss ss ss ss'],
 B:['j1 w1 j1 j1','j1 w1 j1 v1 j1','v1 j1 w1 j1 j1 j1','j1 j1 w1 mm j1 v1 j1','j1 c1 j1 j1 j1 j1','v1 j1 j1 j1 j2','ss ss ss ss'],
 C:['w1 w1 r1 v1','w2 w1 r1 v2 v1','j1 w1 r2 mm v1 j1','j1 w1 w1 r1 v2 v1 j2','w1 w2 r1 r1 v1 j1','w1 w1 r2 v3 j1','r1 r1 w1 v1'],
 D:['j1 j1 w1 j1','j2 j1 w1 j1 mm','j1 mm w2 w1 j1 j1','j1 j1 w1 w3 w1 j2 j1','v1 j1 w1 w1 mm j1','v2 j1 j1 w2 j1','mm w1 v1 j1'],
 E:['j1 j1 r1 j1','j1 mm r2 mm j1','w1 j2 r1 j1 v1 j1','w1 mm r1 c1 r1 mm j1','w1 j1 r2 j1 v2 j1','w1 j2 r1 mm v1','j1 r1 j1 v1'],
 F:['w1 w1 j1 j1','w2 r1 r1 j1 j2','w1 r1 mm c1 j1 j1','w1 r2 mm v1 mm j1 w1','j1 r1 r1 v2 mm w1','j1 j2 r2 c2 w1','j1 v1 r1 j1'],
 G:['j1 v1 v1 j1','j1 v2 v1 v1 j1','j2 v1 mm mm v2 j1','j1 v1 v3 c1 v1 j1 j1','j1 r1 mm v1 v2 j1','j1 j2 mm r2 j1','j1 j1 v1 j1'],
 H:['v1 v1 w1 j1','v2 v1 w1 w1 j1','v1 v3 v1 w2 j1 j1','j1 v1 v2 mm w1 w1 j2','j1 v1 v1 v4 w1 j1','j1 j2 v1 w2 w1','j1 v1 j1 w1'],
 I:['j1 j2 mm j1','j1 mm mm j1 v1','w1 w1 j1 j2 v1 v1','j1 w2 mm c1 j1 v2 j1','j1 w1 j1 mm r1 j1','j2 w1 j1 mm v1','j1 w1 j1 v1'],
 J:['r1 r1 v1 v1','w1 r2 r1 v2 v1','w1 w1 mm r1 v1 j1','w2 w1 r3 c1 r1 v1 j1','w1 w1 r1 mm v3 j1','w1 w1 r1 v1 j2','j1 j1 v1 v1'],
 K:['j1 j1 j2 j1','j1 j2 j1 j1 j1','j1 j1 c1 j2 j1 j1','j2 j1 j1 w1 j1 j3 j1','j1 j1 j2 j1 c2 j1','j1 v1 j1 j1 j2','j1 j1 j3 j1'],
 L:['j1 j1 j1 mm','j2 c1 j1 j1 j1','j1 j1 j2 mm j1 w1','c2 j1 j1 j1 j3 w1 j1','j1 mm j1 v1 j1 w1','j1 j2 j1 c1 j1','j1 v2 j1 j1'],
 M:['j1 mm mm j1','j1 j2 mm j1 j1','mm j1 r1 j2 mm j1','w1 j1 mm c1 j1 j1 mm','w1 mm j1 r2 j1 j1','w1 j1 v1 mm j2','w1 j1 r1 v1'],
 N:['j1 j1 w1 w1','j1 v1 v1 w2 j1','j2 v2 v1 w1 j1 j1','j1 v1 v3 w1 w1 j2 j1','j1 v1 v2 j1 w1 j1','j1 j1 v1 w2 j1','j2 v1 w1 j1'],
};
const PAIRS=[['C','D'],['E','F'],['G','H'],['I','J'],['K','L'],['M','N']];
function parseTok(t){
  if(t==='mm')return{type:'m',val:0};if(t==='ss')return{type:'s',val:0};
  if(t[0]==='g')return{type:'g',sym:t[1],val:1};
  return{type:t[0],val:+t[1]};
}
function parseTpl(rows){
  const cells=[];
  rows.forEach((row,i)=>{const r=i-3,toks=row.trim().split(/\s+/),qmin=Math.max(-3,-r-3),qmax=Math.min(3,-r+3);
    if(toks.length!==qmax-qmin+1)throw new Error('bad tile row '+row);
    toks.forEach((t,j)=>cells.push({q:qmin+j,r,d:parseTok(t)}));});
  return cells;
}
const TPL={};for(const k in BOARDS)TPL[k]=parseTpl(BOARDS[k]);

/* =========================================================
   GEOMETRY / MAP
   ========================================================= */
const SQ3=Math.sqrt(3),R=34;
const DIRS=[[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]];
const TV=[[7,-3],[3,4],[-4,7],[-7,3],[-3,-4],[4,-7]];
const key=(q,r)=>q+','+r;
const rot=(q,r,k)=>{for(let i=0;i<k;i++){const t=q;q=-r;r=t+r;}return[q,r];};
const pxOf=(q,r)=>[R*SQ3*(q+r/2),R*1.5*r];
function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function shuffle(a,rnd=Math.random){for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const hash=(x,y)=>{let h=Math.imul(x|0,374761393)+Math.imul(y|0,668265263);h=Math.imul(h^(h>>>13),1274126177);return((h^(h>>>16))>>>0)/4294967296;};

function genMap(nMid,seed){
  const rng=mulberry32(seed);
  for(let attempt=0;attempt<600;attempt++){
    const centers=[[0,0]],dirs=[];let ok=true;
    const base=rng()<.5?0:1;
    for(let i=0;i<=nMid;i++){ // nMid terrain boards + one slot where the El Dorado tile goes
      const x=rng();
      let pref=x<.42?[0,1]:x<.84?[1,0]:(rng()<.5?[5,0,1]:[2,1,0]);
      if(base===1&&x<.84)pref=pref.slice().reverse();
      let placed=false;
      for(const d of pref){
        const L=centers[centers.length-1],c=[L[0]+TV[d][0],L[1]+TV[d][1]];
        let bad=false;
        for(let j=0;j<centers.length&&!bad;j++){const p=centers[j];
          if(p[0]===c[0]&&p[1]===c[1])bad=true;
          else if(j<centers.length-1&&TV.some(v=>p[0]+v[0]===c[0]&&p[1]+v[1]===c[1]))bad=true;}
        if(bad)continue;centers.push(c);dirs.push(d);placed=true;break;
      }
      if(!placed){ok=false;break;}
    }
    if(!ok)continue;
    const startL=rng()<.5?'A':'B';
    const mids=shuffle(PAIRS.slice(),rng).slice(0,nMid).map(p=>p[rng()<.5?0:1]);
    const endSym=rng()<.5?'j':'w';
    const m=buildMap(centers,dirs,startL,mids,endSym,rng);
    if(m)return m;
  }
  throw new Error('map generation failed');
}
function buildMap(centers,dirs,startL,mids,endSym,rng){
  const hexes=new Map(),tiles=[];const nT=centers.length-1; // last centre = El Dorado side
  for(let ti=0;ti<nT;ti++){
    const c=centers[ti];let cells,k,name;
    if(ti===0){cells=TPL[startL];k=(dirs[0]+1)%6;name=startL;}
    else{name=mids[ti-1];cells=TPL[name];k=Math.floor(rng()*6);}
    tiles.push({c,name,k});
    for(const cell of cells){const[lq,lr]=rot(cell.q,cell.r,k);const q=c[0]+lq,r=c[1]+lr;const K=key(q,r);
      const[x,y]=pxOf(q,r);hexes.set(K,{...cell.d,q,r,k:K,tile:ti,x,y});}
  }
  // El Dorado tile: 3 finishing spaces set against the far edge of the last board
  const last=centers[nT-1],nc=centers[nT];
  const mid=pxOf((last[0]+nc[0])/2,(last[1]+nc[1])/2);
  const cand=[];
  for(let dq=-3;dq<=3;dq++)for(let dr=Math.max(-3,-dq-3);dr<=Math.min(3,-dq+3);dr++){
    const q=nc[0]+dq,r=nc[1]+dr;
    if(DIRS.some(([a,b])=>{const n=hexes.get(key(q+a,r+b));return n&&n.tile===nT-1&&n.type!=='m';})){const[x,y]=pxOf(q,r);cand.push({q,r,x,y,d:Math.hypot(x-mid[0],y-mid[1])});}
  }
  cand.sort((a,b)=>a.d-b.d);
  const goalsC=[];
  for(const c of cand){if(goalsC.length===0||goalsC.some(g=>DIRS.some(([a,b])=>g.q+a===c.q&&g.r+b===c.r)))goalsC.push(c);if(goalsC.length===3)break;}
  if(goalsC.length<3)return null;
  for(const g of goalsC){const K=key(g.q,g.r);hexes.set(K,{type:'g',sym:endSym,val:1,q:g.q,r:g.r,k:K,tile:nT,x:g.x,y:g.y});}
  tiles.push({c:nc,name:'El Dorado',k:0,end:true});
  // seams between consecutive terrain boards
  const conns=[];for(let i=0;i<nT-1;i++)conns.push({a:i,b:i+1,edges:[]});
  const edgeConn=new Map();
  for(const h of hexes.values())for(const[dq,dr]of DIRS){const n=hexes.get(key(h.q+dq,h.r+dr));
    if(n&&n.tile!==h.tile&&h.tile<nT&&n.tile<nT){const c=Math.min(h.tile,n.tile);edgeConn.set(h.k+'|'+n.k,c);if(h.tile<n.tile)conns[c].edges.push([h.k,n.k]);}}
  const starts=[...hexes.values()].filter(h=>h.type==='s');
  const goals=[...hexes.values()].filter(h=>h.type==='g');
  // path check
  const seen=new Set(starts.map(s=>s.k)),q=[...starts];let found=false;
  while(q.length){const h=q.shift();if(h.type==='g'){found=true;break;}
    for(const[dq,dr]of DIRS){const n=hexes.get(key(h.q+dq,h.r+dr));if(!n||seen.has(n.k)||n.type==='m'||n.type==='s')continue;seen.add(n.k);q.push(n);}}
  if(!found)return null;
  for(const c of conns){if(c.edges.filter(([a,b])=>hexes.get(a).type!=='m'&&hexes.get(b).type!=='m').length<2)return null;}
  // start numbering along the edge
  const sc=starts.reduce((a,h)=>[a[0]+h.x/4,a[1]+h.y/4],[0,0]);
  const f=pxOf(...centers[1]);const ang=Math.atan2(f[1],f[0])+Math.PI/2;
  const proj=h=>(h.x-sc[0])*Math.cos(ang)+(h.y-sc[1])*Math.sin(ang);
  starts.sort((a,b)=>proj(a)-proj(b));starts.forEach((s,i)=>s.num=i+1);
  const blockDefs=BLOCKADES.slice(0,conns.length).map((b,i)=>({...b,conn:i}));
  // city
  const gc=goals.reduce((a,h)=>[a[0]+h.x/3,a[1]+h.y/3],[0,0]);
  const tc=pxOf(...last);let dx=gc[0]-tc[0],dy=gc[1]-tc[1];const dl=Math.hypot(dx,dy)||1;dx/=dl;dy/=dl;
  const city={x:gc[0]+dx*R*2.5,y:gc[1]+dy*R*2.5,dx,dy};
  let minX=1e9,minY=1e9,maxX=-1e9,maxY=-1e9;
  for(const h of hexes.values()){minX=Math.min(minX,h.x-R);maxX=Math.max(maxX,h.x+R);minY=Math.min(minY,h.y-R);maxY=Math.max(maxY,h.y+R);}
  minX=Math.min(minX,city.x-R*2.6);maxX=Math.max(maxX,city.x+R*2.6);minY=Math.min(minY,city.y-R*2.6);maxY=Math.max(maxY,city.y+R*2.6);
  const pad=R*.6;minX-=pad;minY-=pad;maxX+=pad;maxY+=pad;
  return{hexes,tiles,conns,edgeConn,starts:starts.map(s=>s.k),goals:goals.map(g=>g.k),blockDefs,city,endSym,minX,minY,w:maxX-minX,h:maxY-minY,route:[startL,...mids]};
}


/* =========================================================
   RULES ENGINE — pure game logic shared by the browser and the server.
   Works on the module-level S (game state) and MAP (board derived from S.seed).
   Nothing in here touches the page.
   ========================================================= */
let S=null,MAP=null;
const hexAt=k=>MAP.hexes.get(k);
const typeOf=id=>S.cards[id];
const def=id=>CT[S.cards[id]];
const plural=(n,w)=>n+' '+w+(n===1?'':'s');
const fmt=n=>(n%1?(Math.floor(n)?Math.floor(n)+'½':'½'):String(n));
function rm(arr,id){const i=arr.indexOf(id);if(i>=0)arr.splice(i,1);}
function playerDone(p){return p.pieces.every(k=>k==='done');}
function isActive(p){return !playerDone(p)&&!p.resigned;}

function newGame(o){
  MAP=genMap(o.nMid,o.seed);
  let nid=1;const cards={};const mk=t=>{const id='c'+(nid++);cards[id]=t;return id;};
  const players=o.players.map(p=>{
    const deck=[];for(let i=0;i<3;i++)deck.push(mk('explorer'));for(let i=0;i<4;i++)deck.push(mk('traveler'));deck.push(mk('sailor'));
    return{name:p.name,color:p.color,pieces:[],deck:shuffle(deck),hand:[],discard:[],play:[],blocks:[],fin:0,resigned:0};
  });
  const st=MAP.starts;
  if(players.length===2){players[0].pieces=[st[0],st[2]];players[1].pieces=[st[1],st[3]];}
  else players.forEach((p,i)=>p.pieces=[st[i]]);
  S={v:3,seed:o.seed,nMid:o.nMid,players,cards,nid,market:MARKET0.map(t=>({t,n:3})),reserve:RESERVE0.map(t=>({t,n:3})),
     blockades:MAP.blockDefs.map(d=>({...d,owner:null})),cur:0,start:0,round:1,endTriggered:false,over:false,winners:null,places:null,
     fullRace:o.fullRace!==false,turn:{bought:false,active:null,pending:null},trash:[],log:[],privacy:!!o.privacy,resigns:0};
  players.forEach(p=>drawCards(p,4));
  log(null,'The expedition sets out: '+players.map(p=>p.name).join(', ')+'. Route '+MAP.route.join(' · ')+' · El Dorado.');
  return S;
}
function newCard(t){const id='c'+(S.nid++);S.cards[id]=t;return id;}
function drawCards(p,n){const got=[];for(let i=0;i<n;i++){if(!p.deck.length){if(!p.discard.length)break;p.deck=shuffle(p.discard);p.discard=[];}const c=p.deck.pop();p.hand.push(c);got.push(c);}return got;}
function log(pi,t){S.log.push({p:pi,t});if(S.log.length>200)S.log.shift();}
function occupied(k,exPl,exPi){return S.players.some((p,pi)=>p.pieces.some((pk,i)=>pk===k&&!(pi===exPl&&i===exPi)));}
function blockAt(a,b){const c=MAP.edgeConn.get(a+'|'+b);if(c===undefined)return null;const bi=S.blockades.findIndex(x=>x.conn===c);if(bi<0||S.blockades[bi].owner!==null)return null;return bi;}
function neighbors(k){const h=hexAt(k);return DIRS.map(([dq,dr])=>key(h.q+dq,h.r+dr)).filter(n=>MAP.hexes.has(n));}
function coinVal(id){const d=def(id);if(d.c==='y'||d.c==='x')return d.p;return .5;}
function blkLabel(B){return B.k==='r'?'discard '+plural(B.v,'card'):plural(B.v,SYMNAME[B.k]);}

/* ---------- reachability ---------- */
function reach(pl,pi,syms,budget){
  const out=new Map();const from=S.players[pl].pieces[pi];if(!from||from==='done')return out;
  for(const sym of syms){
    const dist=new Map([[from,0]]),prev=new Map(),pq=[[0,from]];
    while(pq.length){
      let bi=0;for(let i=1;i<pq.length;i++)if(pq[i][0]<pq[bi][0])bi=i;
      const[d,u]=pq.splice(bi,1)[0];if(d>dist.get(u))continue;
      if(u!==from&&hexAt(u).type==='g')continue;
      for(const n of neighbors(u)){
        const h=hexAt(n);
        if(!(h.type===sym||(h.type==='g'&&h.sym===sym)))continue;
        if(occupied(n,pl,pi))continue;
        let c=h.val;const b=blockAt(u,n);
        if(b!==null){if(S.blockades[b].k!==sym)continue;c+=S.blockades[b].v;}
        const nd=d+c;if(nd>budget)continue;
        if(!dist.has(n)||nd<dist.get(n)){dist.set(n,nd);prev.set(n,u);pq.push([nd,n]);}
      }
    }
    const pathTo=k=>{const p=[];let x=k;while(x!==from){p.unshift(x);x=prev.get(x);}return p;};
    for(const[k,d]of dist){if(k===from)continue;const o=out.get(k);if(!o||d<o.cost)out.set(k,{kind:'move',cost:d,sym,path:pathTo(k),pi});}
    for(const[k,d]of dist){
      if(hexAt(k).type==='g')continue;
      for(const n of neighbors(k)){const b=blockAt(k,n);if(b===null)continue;const B=S.blockades[b];
        if(B.k!==sym||d+B.v>budget)continue;const K='B'+b;const o=out.get(K);
        if(!o||d+B.v<o.cost)out.set(K,{kind:'bl',bl:b,cost:d+B.v,sym,path:k===from?[]:pathTo(k),pi});}
    }
  }
  return out;
}
function nativeTargets(pl,pi){
  const T=new Map();const pk=S.players[pl].pieces[pi];if(!pk||pk==='done')return T;
  for(const n of neighbors(pk)){const h=hexAt(n);if(h.type==='m'||h.type==='s'||occupied(n))continue;T.set(n,{kind:'native',path:[n],cost:0,pi,bl:blockAt(pk,n)});}
  for(const n of neighbors(pk)){const b=blockAt(pk,n);if(b!==null&&!T.has('B'+b))T.set('B'+b,{kind:'nativebl',bl:b,path:[],cost:0,pi});}
  return T;
}
/* spaces/blockades entered by discarding (rubble, grey blockade) or removing cards (base camp) */
function payTargets(pl,pi){
  const T=new Map();const P=S.players[pl];const pk=P.pieces[pi];if(!pk||pk==='done')return T;
  const hn=P.hand.length;
  for(const n of neighbors(pk)){const h=hexAt(n);
    if((h.type==='r'||h.type==='c')&&!occupied(n)&&blockAt(pk,n)===null&&hn>=h.val)T.set(n,{kind:h.type==='r'?'rubble':'camp',need:h.val,path:[n],pi});
    const b=blockAt(pk,n);if(b!==null&&S.blockades[b].k==='r'&&hn>=S.blockades[b].v&&!T.has('B'+b))T.set('B'+b,{kind:'blr',bl:b,need:S.blockades[b].v,pi});
  }
  return T;
}

/* =========================================================
   APPLY AN ACTION. Returns {ok, err?, ev:[events], reveal}
   reveal = new information came out (cards drawn), so undo stops here.
   Actions (acting player = S.cur):
     {t:'move', card, pi, to}        movement card (or a card with leftover strength)
     {t:'native', card, pi, to}
     {t:'pay', pi, to, cards}        rubble / base camp / grey blockade
     {t:'action', card}              Cartographer, Compass, Scientist, Travel Log
     {t:'trash', cards}              finish Scientist / Travel Log
     {t:'transmit', card, src, idx}
     {t:'buy', src, idx, cards}
     {t:'end', keep}                 end the turn, keeping these hand cards
   ========================================================= */
function applyAction(seat,a){
  const fail=err=>({ok:false,err,ev:[]});
  if(!S||S.over)return fail('The game is over.');
  if(seat!==S.cur)return fail('It is not your turn.');
  if(!a||typeof a!=='object')return fail('Bad action.');
  const P=S.players[seat],T=S.turn,ev=[];let reveal=false;
  const inHand=id=>typeof id==='string'&&P.hand.includes(id);
  const distinctHand=ids=>Array.isArray(ids)&&new Set(ids).size===ids.length&&ids.every(inHand);
  const pieceOk=pi=>Number.isInteger(pi)&&pi>=0&&pi<P.pieces.length&&P.pieces[pi]!=='done';
  if(T.pending&&a.t!=='trash')return fail('Choose which cards to remove first.');
  const takeBlock=b=>{const B=S.blockades[b];if(B.owner!==null)return;B.owner=seat;P.blocks.push(b);log(seat,'tears down blockade #'+B.n+' and keeps it.');ev.push({e:'block',pl:seat,n:B.n});};
  const arrive=pi=>{if(P.pieces[pi]!=='done')return;log(seat,'reaches El Dorado!');ev.push({e:'arrive',pl:seat,pi});
    if(playerDone(P)&&!P.fin){P.fin=S.round;checkEnd();}};
  switch(a.t){
    case 'move':{
      const act=T.active&&T.active.id===a.card?T.active:null;
      if(!act&&!inHand(a.card))return fail('That card is not in your hand.');
      const d=def(a.card);if(!d||d.c==='p')return fail('That card cannot move.');
      const pi=act?act.pi:a.pi;if(!pieceOk(pi))return fail('Choose one of your explorers.');
      const syms=act?[act.sym]:(d.s==='*'?['j','w','v']:[d.s]);const budget=act?act.left:d.p;
      const tg=reach(seat,pi,syms,budget).get(a.to);if(!tg)return fail('That space is out of reach.');
      if(!act){T.active=null;rm(P.hand,a.card);P.play.push(a.card);}
      const from=P.pieces[pi];let pos=from;const path=[from];
      for(const st of tg.path){const b=blockAt(pos,st);if(b!==null)takeBlock(b);pos=st;path.push(st);}
      if(tg.kind==='bl')takeBlock(tg.bl);
      const done=hexAt(pos).type==='g';P.pieces[pi]=done?'done':pos;
      const left=budget-tg.cost;T.active=(left>0&&!done)?{id:a.card,pi,sym:tg.sym,left}:null;
      if(tg.path.length){log(seat,'moves '+plural(tg.path.length,'space')+' with '+d.n+(d.s==='*'?' (as '+SYMNAME[tg.sym]+')':'')+'.');ev.push({e:'move',pl:seat,pi,path});}
      arrive(pi);break;
    }
    case 'native':{
      if(!inHand(a.card)||typeOf(a.card)!=='native')return fail('You need the Native.');
      if(!pieceOk(a.pi))return fail('Choose one of your explorers.');
      const tg=nativeTargets(seat,a.pi).get(a.to);if(!tg)return fail('The Native can only reach an adjacent free space.');
      T.active=null;rm(P.hand,a.card);P.play.push(a.card);
      if(tg.bl!=null)takeBlock(tg.bl);
      if(tg.kind==='native'){const from=P.pieces[a.pi];const n=tg.path[0];P.pieces[a.pi]=hexAt(n).type==='g'?'done':n;
        log(seat,'plays the Native and moves to an adjacent space.');ev.push({e:'move',pl:seat,pi:a.pi,path:[from,n]});arrive(a.pi);}
      else log(seat,'plays the Native to tear down a blockade.');
      break;
    }
    case 'pay':{
      if(!pieceOk(a.pi))return fail('Choose one of your explorers.');
      const tg=payTargets(seat,a.pi).get(a.to);if(!tg)return fail('You cannot enter there.');
      if(!distinctHand(a.cards)||a.cards.length!==tg.need)return fail('Choose exactly '+plural(tg.need,'card')+'.');
      T.active=null;const trash=tg.kind==='camp';
      for(const id of a.cards){rm(P.hand,id);if(trash)S.trash.push(id);else P.play.push(id);}
      if(tg.kind==='blr'){takeBlock(tg.bl);log(seat,'discards '+plural(tg.need,'card')+' to clear the blockade.');}
      else{const from=P.pieces[a.pi];const n=tg.path[0];P.pieces[a.pi]=n;
        log(seat,trash?'removes '+plural(tg.need,'card')+' from the game to enter a base camp.':'discards '+plural(tg.need,'card')+' to cross rubble.');
        ev.push({e:'move',pl:seat,pi:a.pi,path:[from,n]});}
      break;
    }
    case 'action':{
      const t=inHand(a.card)&&typeOf(a.card);
      const n={cartographer:2,compass:3,scientist:1,travellog:2}[t];if(!n)return fail('That card has no draw effect.');
      T.active=null;rm(P.hand,a.card);if(CT[t].once)S.trash.push(a.card);else P.play.push(a.card);
      const got=drawCards(P,n);reveal=true;
      log(seat,'plays '+CT[t].n+' and draws '+plural(got.length,'card')+'.');ev.push({e:'draw',pl:seat,n:got.length});
      if(t==='scientist'||t==='travellog')T.pending={max:t==='scientist'?1:2};
      break;
    }
    case 'trash':{
      if(!T.pending)return fail('Nothing to remove.');
      if(!distinctHand(a.cards)||a.cards.length>T.pending.max)return fail('Choose up to '+plural(T.pending.max,'card')+'.');
      if(a.cards.length){for(const id of a.cards){rm(P.hand,id);S.trash.push(id);}log(seat,'removes '+a.cards.map(i=>def(i).n).join(', ')+' from the game.');}
      T.pending=null;break;
    }
    case 'transmit':{
      if(!inHand(a.card)||typeOf(a.card)!=='transmitter')return fail('You need the Transmitter.');
      const stack=a.src==='m'?S.market[a.idx]:a.src==='r'?S.reserve[a.idx]:null;if(!stack||stack.n<=0)return fail('That card is sold out.');
      T.active=null;rm(P.hand,a.card);S.trash.push(a.card);
      stack.n--;P.discard.push(newCard(stack.t));
      log(seat,'uses the Transmitter to take '+CT[stack.t].n+'.');ev.push({e:'gain',pl:seat,t:stack.t,src:a.src,idx:a.idx});
      break;
    }
    case 'buy':{
      if(T.bought)return fail('You can buy only one card per turn.');
      const open=S.market.some(s=>s.n===0);
      let stack=a.src==='m'?S.market[a.idx]:a.src==='r'?S.reserve[a.idx]:null;
      if(!stack||stack.n<=0)return fail('That card is sold out.');
      if(a.src==='r'&&!open)return fail('The reserve opens once a market slot is empty.');
      if(!distinctHand(a.cards))return fail('Pay with cards from your hand.');
      const total=a.cards.reduce((s,id)=>s+coinVal(id),0),cost=CT[stack.t].cost;
      if(total<cost)return fail('Not enough coins.');
      T.active=null;
      for(const id of a.cards){rm(P.hand,id);const d=def(id);if(d.once&&(d.c==='y'||d.c==='x'))S.trash.push(id);else P.play.push(id);}
      const t=stack.t;
      if(a.src==='r'){const slot=S.market.findIndex(s=>s.n===0);S.market[slot]={t,n:stack.n};S.reserve.splice(a.idx,1);stack=S.market[slot];}
      stack.n--;P.discard.push(newCard(t));T.bought=true;
      log(seat,'buys '+CT[t].n+' for '+fmt(total)+' coin'+(total===1?'':'s')+'.');ev.push({e:'gain',pl:seat,t,src:a.src,idx:a.idx});
      break;
    }
    case 'end':{
      const keep=Array.isArray(a.keep)?a.keep:[];
      if(!keep.every(inHand)||new Set(keep).size!==keep.length)return fail('Bad cards to keep.');
      const toDisc=P.hand.filter(id=>!keep.includes(id));
      for(const id of toDisc){rm(P.hand,id);P.discard.push(id);}
      P.discard.push(...P.play);P.play=[];
      drawCards(P,Math.max(0,4-P.hand.length));reveal=true;
      log(seat,'ends the turn'+(toDisc.length?', discarding '+toDisc.length:'')+(keep.length?(toDisc.length?' and':'')+' keeping '+keep.length:'')+'.');
      S.turn={bought:false,active:null,pending:null};
      advance();ev.push({e:'turn',pl:S.cur});
      break;
    }
    default:return fail('Unknown action.');
  }
  if(S.over)ev.push({e:'over'});
  return{ok:true,ev,reveal};
}
/* who still races */
function checkEnd(){
  const n=S.players.length;
  if(S.fullRace){if(S.players.filter(isActive).length<=1&&!S.endTriggered){S.endTriggered=true;log(null,'Only one expedition is still racing. The round will be finished.');}}
  else if(S.players.some(playerDone)&&!S.endTriggered){S.endTriggered=true;log(null,'The final round has begun.');}
  if(S.players.every(p=>!isActive(p))&&S.fullRace)S.endTriggered=true;
  return n;
}
function advance(){
  const n=S.players.length;let i=S.cur;
  for(let step=0;step<n*2+2;step++){
    i=(i+1)%n;
    if(i===S.start){if(S.endTriggered){endGame();return;}S.round++;}
    const p=S.players[i];
    if(S.fullRace?isActive(p):!p.resigned){S.cur=i;return;}
  }
  endGame();
}
/* A player leaves a game for good (online): placed below everyone still racing. */
function resign(seat){
  if(!S||S.over)return{ok:false,ev:[]};
  const P=S.players[seat];if(P.resigned||playerDone(P))return{ok:false,ev:[]};
  P.resigned=++S.resigns;log(seat,'leaves the expedition.');
  const ev=[{e:'resign',pl:seat}];
  const others=S.players.filter((p,i)=>i!==seat&&!p.resigned);
  if(others.length<=1||S.players.filter(isActive).length<=1){ // nobody left to race: finish now
    if(S.players.filter(isActive).length===0||others.length<=1){endGame();ev.push({e:'over'});return{ok:true,ev};}
  }
  checkEnd();
  if(seat===S.cur){S.turn={bought:false,active:null,pending:null};advance();ev.push({e:'turn',pl:S.cur});}
  if(S.over)ev.push({e:'over'});
  return{ok:true,ev};
}
function progress(p){ // lower = closer: sum of shortest step counts from each explorer to a finishing space
  let tot=0;
  for(const k of p.pieces){if(k==='done')continue;
    const seen=new Set([k]);let q=[k],d=0,found=false;
    while(q.length&&!found){d++;const nq=[];for(const u of q)for(const n of neighbors(u)){if(seen.has(n))continue;const h=hexAt(n);if(h.type==='m')continue;if(h.type==='g'){found=true;break;}seen.add(n);nq.push(n);}q=nq;if(d>200)break;}
    tot+=found?d:999;}
  return tot;
}
function endGame(){
  S.over=true;
  const mb=p=>Math.max(0,...p.blocks.map(b=>S.blockades[b].n));
  const keyOf=(p)=>playerDone(p)?[0,p.fin,-p.blocks.length,-mb(p)]:p.resigned?[2,-p.resigned,0,0]:[1,progress(p),-p.blocks.length,-mb(p)];
  const idx=S.players.map((p,i)=>({i,k:keyOf(p)}));
  const cmp=(a,b)=>{for(let j=0;j<4;j++)if(a.k[j]!==b.k[j])return a.k[j]-b.k[j];return 0;};
  idx.sort(cmp);
  const places=new Array(S.players.length);
  idx.forEach((x,j)=>{places[x.i]=j>0&&cmp(x,idx[j-1])===0?places[idx[j-1].i]:j+1;});
  S.places=places;S.winners=places.map((p,i)=>p===1?i:-1).filter(i=>i>=0);
  log(null,S.winners.map(i=>S.players[i].name).join(' & ')+' win'+(S.winners.length>1?'':'s')+' the race to El Dorado.');
}
/* ---------- multiplayer Elo from a finishing order ---------- */
function eloDeltas(ratings,places,games){
  const n=ratings.length;const out=new Array(n).fill(0);if(n<2)return out;
  for(let i=0;i<n;i++){const K=(games[i]<10?48:32)/(n-1);
    for(let j=0;j<n;j++){if(i===j)continue;
      const E=1/(1+Math.pow(10,(ratings[j]-ratings[i])/400));
      const Sc=places[i]<places[j]?1:places[i]===places[j]?.5:0;
      out[i]+=K*(Sc-E);}}
  return out.map(x=>Math.round(x*10)/10);
}
/* ---------- what one player may see ---------- */
function redact(state,seat){
  const R=JSON.parse(JSON.stringify(state));const vis=new Set();
  R.players.forEach((p,i)=>{
    if(i===seat){p.deck=p.deck.slice().sort((a,b)=>(state.cards[a]<state.cards[b]?-1:state.cards[a]>state.cards[b]?1:0));p.hand.forEach(id=>vis.add(id));p.deck.forEach(id=>vis.add(id));}
    else{p.hand=p.hand.map((_,k)=>'h'+i+'_'+k);p.deck=p.deck.map((_,k)=>'d'+i+'_'+k);}
    p.play.forEach(id=>vis.add(id));p.discard.forEach(id=>vis.add(id));
  });
  R.trash.forEach(id=>vis.add(id));
  if(R.turn&&R.turn.active)vis.add(R.turn.active.id);
  const cards={};for(const id of vis)if(state.cards[id])cards[id]=state.cards[id];R.cards=cards;
  return R;
}

export const E={genMap,newGame,applyAction,resign,eloDeltas,redact,reach,payTargets,nativeTargets,playerDone,CT,get S(){return S},set S(v){S=v},get MAP(){return MAP},set MAP(v){MAP=v}};
