// GENERATED by build.mjs from engine_data.js + engine_rules.js + engine_bot.js + engine_ai.js. Do not edit.
/* =========================================================
   CARD DATA (base game)
   ========================================================= */
const CT={
  explorer:{n:'Explorer',c:'g',s:'j',p:1},
  traveler:{n:'Traveler',c:'y',s:'v',p:1},
  sailor:{n:'Sailor',c:'b',s:'w',p:1},
  scout:{n:'Scout',c:'g',s:'j',p:2,cost:1},
  trailblazer:{n:'Trailblazer',c:'g',s:'j',p:3,cost:3},
  pioneer:{n:'Pioneer',c:'g',s:'j',p:5,cost:5},
  giant:{n:'Giant Machete',c:'g',s:'j',p:6,cost:3,once:1},
  captain:{n:'Captain',c:'b',s:'w',p:3,cost:2},
  photographer:{n:'Photographer',c:'y',s:'v',p:2,cost:2},
  journalist:{n:'Journalist',c:'y',s:'v',p:3,cost:3},
  chest:{n:'Treasure Chest',c:'y',s:'v',p:4,cost:3,once:1},
  millionaire:{n:'Millionaire',c:'y',s:'v',p:4,cost:5},
  jack:{n:'Jack of All Trades',c:'x',s:'*',p:1,cost:2},
  adventurer:{n:'Adventurer',c:'x',s:'*',p:2,cost:4},
  plane:{n:'Prop Plane',c:'x',s:'*',p:4,cost:4,once:1},
  transmitter:{n:'Transmitter',c:'p',cost:4,once:1,txt:'Take any card from the market or reserve for free.',face:'Take any market or reserve card for free.'},
  cartographer:{n:'Cartographer',c:'p',cost:4,txt:'Draw 2 cards.'},
  scientist:{n:'Scientist',c:'p',cost:4,txt:'Draw 1 card. You may remove 1 card in hand from the game.',face:'Draw 1 card. You may remove 1 card from the game.'},
  compass:{n:'Compass',c:'p',cost:2,once:1,txt:'Draw 3 cards.'},
  travellog:{n:'Travel Log',c:'p',cost:3,once:1,txt:'Draw 2 cards. You may remove up to 2 cards in hand from the game.',face:'Draw 2 cards. You may remove up to 2 from the game.'},
  native:{n:'Native',c:'p',cost:5,txt:'Move to an adjacent space, ignoring its requirement. Can tear down a blockade.',face:'Move 1 space, ignoring its cost. Can tear down a blockade.'},
};
const MARKET0=['scout','trailblazer','jack','photographer','chest','transmitter'];
const RESERVE0=['pioneer','giant','captain','journalist','millionaire','adventurer','plane','cartographer','scientist','compass','travellog','native'];
const SYMNAME={j:'machete',w:'paddle',v:'coin'};
const SYMCOL={j:'#3f9a5c',w:'#3a8ad0',v:'#e7b54d',r:'#a3a8a4'};
const COLORS=[{id:'crimson',hex:'#e5484d',name:'Crimson'},{id:'ivory',hex:'#efe9dc',name:'Ivory'},{id:'violet',hex:'#9d7df7',name:'Violet'},{id:'orange',hex:'#ff9636',name:'Orange'}]; // one explorer figure per colour
/* Official base-game blockades are numbered 1–6: jungle, village, rubble, water, jungle, rubble.
   They are placed along the route in number order; the number also breaks ties. */
const BLOCKADES=[{n:1,k:'j',v:1},{n:2,k:'v',v:1},{n:3,k:'r',v:1},{n:4,k:'w',v:1},{n:5,k:'j',v:2},{n:6,k:'r',v:2}];

/* =========================================================
   TERRAIN BOARDS — base game letters. Terrain counts per board match the published
   tile catalogue (A/B start boards, C–N double-sided terrain boards).
   Transcribed space by space from the BoardGameHelpers catalogue images (Q4eD.<n>.<L>.gif, image orientation = rotation 0):
   A B C D F G I K L M N. Still reconstructed (counts right, layout guessed): E H J.
   rows top→bottom (4,5,6,7,6,5,4): jN jungle · wN water · vN village · rN rubble · cN base camp · mm mountain · ss start
   ========================================================= */
const BOARDS={
 A:['j1 c1 j1 j1','w1 mm j1 j1 v1','j1 mm v1 j1 j1 j1','j1 v1 j1 w1 j1 v1 j1','j1 j1 v1 j1 w1 j1','j1 j1 j1 j1 j1','s1 s2 s3 s4'],
 B:['j1 w1 c1 w1','j1 j1 v1 mm j1','j1 v1 j1 j1 j1 j1','w1 j1 v1 j1 v1 j1 j1','j1 j1 w1 j1 j1 j1','j1 j1 j1 j1 j1','s4 s3 s2 s1'],
 C:['j1 j1 r1 r1','j1 v1 r1 w1 w1','w1 w1 v1 v1 r1 w1','w1 v1 r1 mm w1 r1 r1','v1 r1 w1 w1 v1 v1','v1 r1 j1 v1 w1','j1 j1 w1 w1'],
 D:['j2 j1 mm w3','j1 j1 v3 v1 mm','j1 w1 j1 mm v3 j1','j2 w1 w2 mm j1 j1 j2','j1 w1 w1 w2 w1 j1','j1 w1 w1 w1 j1','j1 j1 j1 j2'],
 E:['j1 j1 r1 j1','j1 mm r2 mm j1','w1 j2 r1 j1 v1 j1','w1 mm r1 c1 r1 mm j1','w1 j1 r2 j1 v2 j1','w1 j2 r1 mm v1','j1 r1 j1 v1'],
 F:['j1 mm mm w1','j2 j1 mm w1 w1','r1 j1 w2 w3 w1 r1','r1 v1 v2 mm j2 j1 r1','r1 v1 r2 j1 j1 r1','j1 j3 j1 w2 w2','c1 j2 r1 c2'],
 G:['j1 j1 j1 j1','j1 j2 v1 mm j1','v1 v2 v2 r1 v1 j1','mm mm v4 v3 v2 j2 c1','v1 v2 v2 r1 v1 j1','j1 j2 v1 mm j1','j1 j1 j1 j1'],
 H:['v1 v1 w1 j1','v2 v1 w1 w1 j1','v1 v3 v1 w2 j1 j1','j1 v1 v2 mm w1 w1 j2','j1 v1 v1 v4 w1 j1','j1 j2 v1 w2 w1','j1 v1 j1 w1'],
 I:['j1 j1 j1 j1','v1 j1 mm j1 j1','v1 v2 j1 mm j2 j1','v1 v2 j1 j2 c2 mm mm','v2 r3 mm mm j2 j1','w2 w1 w1 j1 j1','w2 w2 w1 j1'],
 J:['r1 r1 v1 v1','w1 r2 r1 v2 v1','w1 w1 mm r1 v1 j1','w2 w1 r3 c1 r1 v1 j1','w1 w1 r1 mm v3 j1','w1 w1 r1 v1 j2','j1 j1 v1 v1'],
 K:['c1 j2 j2 j1','j1 j1 w3 j1 j2','j1 j2 j1 j3 j1 j2','j2 j1 j3 j1 j3 j1 j2','j2 j1 j3 j1 j2 j1','j2 j1 v4 j1 j1','j1 j2 j2 c1'],
 L:['w1 c1 c1 j3','j1 w1 w1 j3 j1','j2 j1 j1 j3 j1 j2','j2 j1 mm j1 mm j1 j2','j1 j2 j2 j1 j2 j1','v2 c2 v2 j1 j1','j2 j2 j1 mm'],
 M:['j1 j1 j1 c1','j1 v4 mm mm w4','j1 v2 j1 j1 w1 mm','mm j1 j1 r2 j1 j1 mm','mm mm mm mm r2 j1','j1 j1 j1 r2 j1','w1 w1 j1 j1'],
 N:['j1 j1 j1 j1','v1 j1 j2 j1 w1','v1 v2 j1 w1 w1 w1','w1 w1 v3 v4 v2 v2 v1','w1 w1 w1 j1 v2 v1','j1 j1 j2 j1 j1','j1 j1 j1 j1'],
};
function parseTok(t){
  if(t==='mm')return{type:'m',val:0};if(t[0]==='s')return{type:'s',val:0,num:+t[1]||0}; // s1–s4: numbered start spaces
  if(t[0]==='g')return{type:'g',sym:t[1],val:1};
  return{type:t[0],val:+t[1]};
}
function parseTpl(rows){
  const cells=[];
  rows.forEach((row,i)=>{const r=i-3,toks=row.trim().split(/\s+/),qmin=Math.max(-3,-r-3),qmax=Math.min(3,-r+3);
    if(toks.length!==qmax-qmin+1)throw new Error('bad tile row '+row);
    toks.forEach((t,j)=>cells.push({q:qmin+j,r,d:parseTok(t)}));});
  return cells;
}
const TPL={};for(const k in BOARDS)TPL[k]=parseTpl(BOARDS[k]);

/* =========================================================
   GEOMETRY / MAP
   ========================================================= */
const SQ3=Math.sqrt(3),R=34;
const DIRS=[[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]];
const key=(q,r)=>q+','+r;
const rot=(q,r,k)=>{for(let i=0;i<k;i++){const t=q;q=-r;r=t+r;}return[q,r];};
const pxOf=(q,r)=>[R*SQ3*(q+r/2),R*1.5*r];
function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
/* where shuffles get their randomness: Math.random in play; a seeded generator while recording or replaying a game log */
let RNG=Math.random;
function setRng(f){RNG=f||Math.random;}
function shuffle(a,rnd=RNG){for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const hash=(x,y)=>{let h=Math.imul(x|0,374761393)+Math.imul(y|0,668265263);h=Math.imul(h^(h>>>13),1274126177);return((h^(h>>>16))>>>0)/4294967296;};

/* =========================================================
   COURSES — fixed routes (no random generation).
   p: the boards in route order as [letter, q, r, rotation]; the first is start board A or B.
      (q,r) is where the board's central space goes; rotation is in 60° steps.
   e: [q,r] the middle finishing space of the El Dorado tile, next to the last board.
   s: El Dorado side, 'j' jungle or 'w' water.
   Blockades are dealt at random onto the connections when a game starts (rulebook).
   ========================================================= */
const COURSES=[
  // Positions and rotations taken from Ravensburger's setup sheet (first game); El Dorado water side on K's top-right corner.
  {id:'first',name:'First Expedition',src:'Rulebook route for your first game',diff:'Easy',
   p:[['B',0,0,2],['C',7,-3,5],['N',11,0,2],['I',14,4,2],['K',21,-1,0]],e:[25,-5],s:'w'},
  // The other official routes come from page 2 of the same sheet (German "Andere Wege nach El Dorado"). There the hexes are
  // flat-topped; every board was matched space by space against its catalogue tile (tools/course-check/), so positions and
  // rotations are exact. Shown here turned 30° (our lattice is pointy-topped).
  {id:'winding',name:'Winding Paths',src:'Rulebook route (German: Verschlungene Wege)',diff:'Medium',
   p:[['B',0,0,2],['I',7,-3,4],['F',11,0,4],['G',8,7,2],['C',15,4,1],['N',19,7,5]],e:[23,7],s:'w'},
  {id:'witch',name:"Witch's Cauldron",src:'Rulebook route (German: Der Hexenkessel)',diff:'Hard',
   p:[['A',0,0,0],['L',7,-4,5],['G',14,-7,4],['D',18,-4,4],['M',14,3,0],['I',7,7,5]],e:[3,7],s:'w'},
];
const courseById=id=>COURSES.find(c=>c.id===id)||null;
function buildCourse(C,seed){
  const hexes=new Map(),tiles=[];
  C.p.forEach(([name,cq,cr,k],ti)=>{
    const tpl=TPL[name];if(!tpl)throw new Error('Unknown board '+name);
    if((ti===0)!==(name==='A'||name==='B'))throw new Error('A route starts with board A or B, and only there.');
    let sx=0,sy=0;
    for(const cell of tpl){const[lq,lr]=rot(cell.q,cell.r,k);const q=cq+lq,r=cr+lr,K=key(q,r);
      if(hexes.has(K))throw new Error('Boards '+tiles[hexes.get(K).tile].name+' and '+name+' overlap.');
      const[x,y]=pxOf(q,r);hexes.set(K,{...cell.d,q,r,k:K,tile:ti,x,y});sx+=x;sy+=y;}
    tiles.push({c:[cq,cr],name,k,x:sx/tpl.length,y:sy/tpl.length});
  });
  const nT=tiles.length;
  // El Dorado tile: the given space plus its two neighbours along the last board's edge
  const touch=(q,r)=>!hexes.has(key(q,r))&&DIRS.some(([a,b])=>{const n=hexes.get(key(q+a,r+b));return n&&n.tile===nT-1&&n.type!=='m';});
  const[eq,er]=C.e;if(!touch(eq,er))throw new Error('El Dorado must sit against the last board.');
  let side=null;
  for(let d=0;d<3&&!side;d++){const a=[eq+DIRS[d][0],er+DIRS[d][1]],b=[eq-DIRS[d][0],er-DIRS[d][1]];if(touch(...a)&&touch(...b))side=[a,b];}
  if(!side){const fr=DIRS.map(([a,b])=>[eq+a,er+b]).filter(c=>touch(...c));if(fr.length<2)throw new Error('No room for El Dorado there.');side=fr.slice(0,2);}
  for(const[q,r]of[[eq,er],...side]){const K=key(q,r),[x,y]=pxOf(q,r);hexes.set(K,{type:'g',sym:C.s,val:1,q,r,k:K,tile:nT,x,y});}
  // connections between consecutive boards (only these carry blockades; other touching boards are open)
  const conns=[];const edgeConn=new Map();
  for(let i=0;i<nT-1;i++)conns.push({a:i,b:i+1,edges:[]});
  for(const h of hexes.values())for(const[dq,dr]of DIRS){const n=hexes.get(key(h.q+dq,h.r+dr));
    if(n&&n.tile===h.tile+1&&n.tile<nT){conns[h.tile].edges.push([h.k,n.k]);edgeConn.set(h.k+'|'+n.k,h.tile);edgeConn.set(n.k+'|'+h.k,h.tile);}}
  conns.forEach((c,i)=>{if(c.edges.filter(([a,b])=>hexes.get(a).type!=='m'&&hexes.get(b).type!=='m').length<2)throw new Error('Boards '+tiles[i].name+' and '+tiles[i+1].name+' are not properly connected.');});
  const starts=[...hexes.values()].filter(h=>h.type==='s');
  const goals=[...hexes.values()].filter(h=>h.type==='g');
  const seen=new Set(starts.map(s=>s.k)),q=[...starts];let found=false;
  while(q.length){const h=q.shift();if(h.type==='g'){found=true;break;}
    for(const[dq,dr]of DIRS){const n=hexes.get(key(h.q+dq,h.r+dr));if(!n||seen.has(n.k)||n.type==='m'||n.type==='s')continue;seen.add(n.k);q.push(n);}}
  if(!found)throw new Error('There is no path from the start to El Dorado.');
  // start spaces numbered along their edge
  const sc=starts.reduce((a,h)=>[a[0]+h.x/starts.length,a[1]+h.y/starts.length],[0,0]);
  const ang=Math.atan2(tiles[1].y-tiles[0].y,tiles[1].x-tiles[0].x)+Math.PI/2;
  const proj=h=>(h.x-sc[0])*Math.cos(ang)+(h.y-sc[1])*Math.sin(ang);
  if(starts.every(s=>s.num))starts.sort((a,b)=>a.num-b.num);else{starts.sort((a,b)=>proj(a)-proj(b));starts.forEach((s,i)=>s.num=i+1);}
  // a random blockade on each connection
  const deal=shuffle(BLOCKADES.slice(),mulberry32(seed^0x2c1b3c6d));
  if(conns.length>deal.length)throw new Error('Too many connections for 6 blockades.');
  const blockDefs=conns.map((c,i)=>({...deal[i],conn:i}));
  const gc=goals.reduce((a,h)=>[a[0]+h.x/3,a[1]+h.y/3],[0,0]);
  const last=tiles[nT-1];let dx=gc[0]-last.x,dy=gc[1]-last.y;const dl=Math.hypot(dx,dy)||1;dx/=dl;dy/=dl;
  const city={x:gc[0]+dx*R*2.5,y:gc[1]+dy*R*2.5,dx,dy};
  tiles.push({c:[eq,er],name:'El Dorado',k:0,end:true,x:gc[0],y:gc[1]});
  let minX=1e9,minY=1e9,maxX=-1e9,maxY=-1e9;
  for(const h of hexes.values()){minX=Math.min(minX,h.x-R);maxX=Math.max(maxX,h.x+R);minY=Math.min(minY,h.y-R);maxY=Math.max(maxY,h.y+R);}
  minX=Math.min(minX,city.x-R*2.6);maxX=Math.max(maxX,city.x+R*2.6);minY=Math.min(minY,city.y-R*2.6);maxY=Math.max(maxY,city.y+R*2.6);
  const pad=R*.6;minX-=pad;minY-=pad;maxX+=pad;maxY+=pad;
  return{hexes,tiles,conns,edgeConn,starts:starts.map(s=>s.k),goals:goals.map(g=>g.k),blockDefs,city,endSym:C.s,minX,minY,w:maxX-minX,h:maxY-minY,route:C.p.map(x=>x[0]),name:C.name,course:C.id};
}

/* =========================================================
   RULES ENGINE — pure game logic shared by the browser and the server.
   Works on the module-level S (game state) and MAP (board built from S.course + S.seed).
   Nothing in here touches the page.
   ========================================================= */
let S=null,MAP=null;
const hexAt=k=>MAP.hexes.get(k);
const typeOf=id=>S.cards[id];
const def=id=>CT[S.cards[id]];
const plural=(n,w)=>n+' '+w+(n===1?'':'s');
const fmt=n=>(n%1?(Math.floor(n)?Math.floor(n)+'½':'½'):String(n));
function rm(arr,id){const i=arr.indexOf(id);if(i>=0)arr.splice(i,1);}
function playerDone(p){return p.pieces.every(k=>k==='done');}
function isActive(p){return !playerDone(p)&&!p.resigned;}

function mapFor(st){return buildCourse(st.course,st.seed);}
/* ---- game logs (replays) ----
   {kind:'eldorado-replay', v:1, title, course, seed, rng, fullRace, players:[{name,color,bot}], actions:[[seat,action],…], notes:[…]}
   Every shuffle draws from a generator seeded with log.rng, so re-applying the same actions rebuilds the identical game. */
const REPLAY_MAX_ACTIONS=20000;
function replayCheck(log){
  if(!log||log.kind!=='eldorado-replay'||log.v!==1)return'Not an El Dorado game log.';
  if(!courseById(log.course))return'Unknown course: '+log.course;
  if(!Array.isArray(log.players)||log.players.length<2||log.players.length>4)return'A game log needs 2 to 4 players.';
  if(!Number.isFinite(log.seed)||!Number.isFinite(log.rng))return'The game log is missing its seeds.';
  if(log.gift&&!(CT[log.gift]&&CT[log.gift].cost))return'Unknown gift card: '+log.gift;
  if(!Array.isArray(log.actions)||log.actions.length>REPLAY_MAX_ACTIONS||!log.actions.every(x=>Array.isArray(x)&&Number.isInteger(x[0])&&x[1]&&typeof x[1].t==='string'))return'The game log has no valid list of actions.';
  return null;}
function replayStart(log){const g=mulberry32(log.rng>>>0);setRng(g);
  newGame({course:courseById(log.course),seed:log.seed,fullRace:log.fullRace!==false,players:log.players.map((p,i)=>({name:String(p.name||'Player '+(i+1)).slice(0,24),color:COLORS[i%COLORS.length].hex}))});
  // training exploration: every player starts with the same extra card, shuffled into the draw pile
  if(log.gift)for(const p of S.players)p.deck.splice(Math.floor(RNG()*(p.deck.length+1)),0,newCard(log.gift));
  return g;}
function newGame(o){

  const course=o.course||COURSES[0];
  MAP=buildCourse(course,o.seed);
  let nid=1;const cards={};const mk=t=>{const id='c'+(nid++);cards[id]=t;return id;};
  const players=o.players.map(p=>{
    const deck=[];for(let i=0;i<3;i++)deck.push(mk('explorer'));for(let i=0;i<4;i++)deck.push(mk('traveler'));deck.push(mk('sailor'));
    const pl={name:p.name,color:p.color,pieces:[],deck:shuffle(deck),hand:[],discard:[],play:[],blocks:[],fin:0,resigned:0};
    if(p.ai&&aiById(p.ai))pl.ai=p.ai; // a named AI plays this seat (engine_ai.js)
    return pl;
  });
  const st=MAP.starts;
  if(players.length===2){players[0].pieces=[st[0],st[2]];players[1].pieces=[st[1],st[3]];}
  else players.forEach((p,i)=>p.pieces=[st[i]]);
  S={v:5,seed:o.seed,course,players,cards,nid,market:MARKET0.map(t=>({t,n:3})),reserve:RESERVE0.map(t=>({t,n:3})),
     blockades:MAP.blockDefs.map(d=>({...d,owner:null})),cur:0,start:0,round:1,endTriggered:false,over:false,winners:null,places:null,
     fullRace:o.fullRace!==false,turn:{bought:false,active:null,pending:null},trash:[],log:[],privacy:!!o.privacy,resigns:0};
  players.forEach(p=>drawCards(p,4));
  log(null,'The expedition sets out: '+players.map(p=>p.name).join(', ')+'. Course: '+MAP.name+' ('+MAP.route.join(' · ')+' · El Dorado).');
  return S;
}
function newCard(t){const id='c'+(S.nid++);S.cards[id]=t;return id;}
function drawCards(p,n){const got=[];for(let i=0;i<n;i++){if(!p.deck.length){if(!p.discard.length)break;p.deck=shuffle(p.discard);p.discard=[];}const c=p.deck.pop();p.hand.push(c);got.push(c);}return got;}
function log(pi,t){S.log.push({p:pi,t,r:S.round});if(S.log.length>200)S.log.shift();}
function occupied(k,exPl,exPi){return S.players.some((p,pi)=>p.pieces.some((pk,i)=>pk===k&&!(pi===exPl&&i===exPi)));}
function blockAt(a,b){const c=MAP.edgeConn.get(a+'|'+b);if(c===undefined)return null;const bi=S.blockades.findIndex(x=>x.conn===c);if(bi<0||S.blockades[bi].owner!==null)return null;return bi;}
function neighbors(k){const nb=MAP._nb||(MAP._nb=new Map());let r=nb.get(k);if(!r){const h=hexAt(k);r=DIRS.map(([dq,dr])=>key(h.q+dq,h.r+dr)).filter(n=>MAP.hexes.has(n));nb.set(k,r);}return r;} // cached per map
function coinVal(id){const d=def(id);if(d.c==='y'||d.c==='x')return d.p;return .5;}
function blkLabel(B){return B.k==='r'?'discard '+plural(B.v,'card'):plural(B.v,SYMNAME[B.k]);}

/* ---------- reachability ---------- */
function reach(pl,pi,syms,budget){
  const out=new Map();const from=S.players[pl].pieces[pi];if(!from||from==='done')return out;
  for(const sym of syms){
    const dist=new Map([[from,0]]),prev=new Map(),pq=[[0,from]];
    while(pq.length){
      let bi=0;for(let i=1;i<pq.length;i++)if(pq[i][0]<pq[bi][0])bi=i;
      const[d,u]=pq[bi];pq[bi]=pq[pq.length-1];pq.pop();if(d>dist.get(u))continue;
      if(u!==from&&hexAt(u).type==='g')continue;
      for(const n of neighbors(u)){
        const h=hexAt(n);
        if(!(h.type===sym||(h.type==='g'&&h.sym===sym)))continue;
        if(occupied(n,pl,pi))continue;
        let c=h.val;const b=blockAt(u,n);
        if(b!==null){if(S.blockades[b].k!==sym)continue;c+=S.blockades[b].v;}
        const nd=d+c;if(nd>budget)continue;
        if(!dist.has(n)||nd<dist.get(n)){dist.set(n,nd);prev.set(n,u);pq.push([nd,n]);}
      }
    }
    const pathTo=k=>{const p=[];let x=k;while(x!==from){p.unshift(x);x=prev.get(x);}return p;};
    for(const[k,d]of dist){if(k===from)continue;const o=out.get(k);if(!o||d<o.cost)out.set(k,{kind:'move',cost:d,sym,path:pathTo(k),pi});}
    for(const[k,d]of dist){
      if(hexAt(k).type==='g')continue;
      for(const n of neighbors(k)){const b=blockAt(k,n);if(b===null)continue;const B=S.blockades[b];
        if(B.k!==sym||d+B.v>budget)continue;const K='B'+b;const o=out.get(K);
        if(!o||d+B.v<o.cost)out.set(K,{kind:'bl',bl:b,cost:d+B.v,sym,path:k===from?[]:pathTo(k),pi});}
    }
  }
  return out;
}
function nativeTargets(pl,pi){
  const T=new Map();const pk=S.players[pl].pieces[pi];if(!pk||pk==='done')return T;
  for(const n of neighbors(pk)){const h=hexAt(n);if(h.type==='m'||h.type==='s'||occupied(n))continue;T.set(n,{kind:'native',path:[n],cost:0,pi,bl:blockAt(pk,n)});}
  for(const n of neighbors(pk)){const b=blockAt(pk,n);if(b!==null&&!T.has('B'+b))T.set('B'+b,{kind:'nativebl',bl:b,path:[],cost:0,pi});}
  return T;
}
/* spaces/blockades entered by discarding (rubble, grey blockade) or removing cards (base camp) */
function payTargets(pl,pi){
  const T=new Map();const P=S.players[pl];const pk=P.pieces[pi];if(!pk||pk==='done')return T;
  const hn=P.hand.length;
  for(const n of neighbors(pk)){const h=hexAt(n);
    if((h.type==='r'||h.type==='c')&&!occupied(n)&&blockAt(pk,n)===null&&hn>=h.val)T.set(n,{kind:h.type==='r'?'rubble':'camp',need:h.val,path:[n],pi});
    const b=blockAt(pk,n);if(b!==null&&S.blockades[b].k==='r'&&hn>=S.blockades[b].v&&!T.has('B'+b))T.set('B'+b,{kind:'blr',bl:b,need:S.blockades[b].v,pi});
  }
  return T;
}

/* =========================================================
   APPLY AN ACTION. Returns {ok, err?, ev:[events], reveal}
   reveal = new information came out (cards drawn), so undo stops here.
   Actions (acting player = S.cur):
     {t:'move', card, pi, to}        movement card (or a card with leftover strength)
     {t:'native', card, pi, to}
     {t:'pay', pi, to, cards}        rubble / base camp / grey blockade
     {t:'action', card}              Cartographer, Compass, Scientist, Travel Log
     {t:'trash', cards}              finish Scientist / Travel Log
     {t:'transmit', card, src, idx}
     {t:'buy', src, idx, cards}
     {t:'end', keep}                 end the turn, keeping these hand cards
   ========================================================= */
function applyAction(seat,a){
  const fail=err=>({ok:false,err,ev:[]});
  if(!S||S.over)return fail('The game is over.');
  if(seat!==S.cur)return fail('It is not your turn.');
  if(!a||typeof a!=='object')return fail('Bad action.');
  const P=S.players[seat],T=S.turn,ev=[];let reveal=false;
  const inHand=id=>typeof id==='string'&&P.hand.includes(id);
  const distinctHand=ids=>Array.isArray(ids)&&new Set(ids).size===ids.length&&ids.every(inHand);
  const pieceOk=pi=>Number.isInteger(pi)&&pi>=0&&pi<P.pieces.length&&P.pieces[pi]!=='done';
  if(T.pending&&a.t!=='trash')return fail('Choose which cards to remove first.');
  const takeBlock=b=>{const B=S.blockades[b];if(B.owner!==null)return;B.owner=seat;P.blocks.push(b);log(seat,'tears down blockade #'+B.n+' and keeps it.');ev.push({e:'block',pl:seat,n:B.n});};
  const arrive=pi=>{if(P.pieces[pi]!=='done')return;log(seat,'reaches El Dorado!');ev.push({e:'arrive',pl:seat,pi});
    if(playerDone(P)&&!P.fin){P.fin=S.round;checkEnd();}};
  switch(a.t){
    case 'move':{
      const act=T.active&&T.active.id===a.card?T.active:null;
      if(!act&&!inHand(a.card))return fail('That card is not in your hand.');
      const d=def(a.card);if(!d||d.c==='p')return fail('That card cannot move.');
      const pi=act?act.pi:a.pi;if(!pieceOk(pi))return fail('Choose one of your explorers.');
      const syms=act?[act.sym]:(d.s==='*'?['j','w','v']:[d.s]);const budget=act?act.left:d.p;
      const tg=reach(seat,pi,syms,budget).get(a.to);if(!tg)return fail('That space is out of reach.');
      ev.push({e:'play',pl:seat,k:'move',ts:[typeOf(a.card)],more:!!act,n:tg.path.length,sym:tg.sym});
      if(!act){T.active=null;rm(P.hand,a.card);P.play.push(a.card);}
      const from=P.pieces[pi];let pos=from;const path=[from];
      for(const st of tg.path){const b=blockAt(pos,st);if(b!==null)takeBlock(b);pos=st;path.push(st);}
      if(tg.kind==='bl')takeBlock(tg.bl);
      const done=hexAt(pos).type==='g';P.pieces[pi]=done?'done':pos;
      const left=budget-tg.cost;T.active=(left>0&&!done)?{id:a.card,pi,sym:tg.sym,left}:null;
      if(tg.path.length){log(seat,'moves '+plural(tg.path.length,'space')+' with '+d.n+(d.s==='*'?' (as '+SYMNAME[tg.sym]+')':'')+'.');ev.push({e:'move',pl:seat,pi,path});}
      arrive(pi);break;
    }
    case 'native':{
      if(!inHand(a.card)||typeOf(a.card)!=='native')return fail('You need the Native.');
      if(!pieceOk(a.pi))return fail('Choose one of your explorers.');
      const tg=nativeTargets(seat,a.pi).get(a.to);if(!tg)return fail('The Native can only reach an adjacent free space.');
      T.active=null;rm(P.hand,a.card);P.play.push(a.card);ev.push({e:'play',pl:seat,k:'native',ts:['native'],n:tg.kind==='native'?1:0});
      if(tg.bl!=null)takeBlock(tg.bl);
      if(tg.kind==='native'){const from=P.pieces[a.pi];const n=tg.path[0];P.pieces[a.pi]=hexAt(n).type==='g'?'done':n;
        log(seat,'plays the Native and moves to an adjacent space.');ev.push({e:'move',pl:seat,pi:a.pi,path:[from,n]});arrive(a.pi);}
      else log(seat,'plays the Native to tear down a blockade.');
      break;
    }
    case 'pay':{
      if(!pieceOk(a.pi))return fail('Choose one of your explorers.');
      const tg=payTargets(seat,a.pi).get(a.to);if(!tg)return fail('You cannot enter there.');
      if(!distinctHand(a.cards)||a.cards.length!==tg.need)return fail('Choose exactly '+plural(tg.need,'card')+'.');
      T.active=null;const trash=tg.kind==='camp';ev.push({e:'play',pl:seat,k:tg.kind,ts:a.cards.map(typeOf)});
      for(const id of a.cards){rm(P.hand,id);if(trash)S.trash.push(id);else P.play.push(id);}
      if(tg.kind==='blr'){takeBlock(tg.bl);log(seat,'discards '+plural(tg.need,'card')+' to clear the blockade.');}
      else{const from=P.pieces[a.pi];const n=tg.path[0];P.pieces[a.pi]=n;
        log(seat,trash?'removes '+plural(tg.need,'card')+' from the game to enter a base camp.':'discards '+plural(tg.need,'card')+' to cross rubble.');
        ev.push({e:'move',pl:seat,pi:a.pi,path:[from,n]});}
      break;
    }
    case 'action':{
      const t=inHand(a.card)&&typeOf(a.card);
      const n={cartographer:2,compass:3,scientist:1,travellog:2}[t];if(!n)return fail('That card has no draw effect.');
      T.active=null;rm(P.hand,a.card);if(CT[t].once)S.trash.push(a.card);else P.play.push(a.card);
      const got=drawCards(P,n);reveal=true;ev.push({e:'play',pl:seat,k:'action',ts:[t],n:got.length});
      log(seat,'plays '+CT[t].n+' and draws '+plural(got.length,'card')+'.');ev.push({e:'draw',pl:seat,n:got.length});
      if(t==='scientist'||t==='travellog')T.pending={max:t==='scientist'?1:2};
      break;
    }
    case 'trash':{
      if(!T.pending)return fail('Nothing to remove.');
      if(!distinctHand(a.cards)||a.cards.length>T.pending.max)return fail('Choose up to '+plural(T.pending.max,'card')+'.');
      ev.push({e:'play',pl:seat,k:'trash',ts:a.cards.map(typeOf)});
      if(a.cards.length){for(const id of a.cards){rm(P.hand,id);S.trash.push(id);}log(seat,'removes '+a.cards.map(i=>def(i).n).join(', ')+' from the game.');}
      T.pending=null;break;
    }
    case 'transmit':{
      if(!inHand(a.card)||typeOf(a.card)!=='transmitter')return fail('You need the Transmitter.');
      const stack=a.src==='m'?S.market[a.idx]:a.src==='r'?S.reserve[a.idx]:null;if(!stack||stack.n<=0)return fail('That card is sold out.');
      T.active=null;rm(P.hand,a.card);S.trash.push(a.card);
      stack.n--;P.discard.push(newCard(stack.t));ev.push({e:'play',pl:seat,k:'transmit',ts:['transmitter'],got:stack.t});
      log(seat,'uses the Transmitter to take '+CT[stack.t].n+'.');ev.push({e:'gain',pl:seat,t:stack.t,src:a.src,idx:a.idx});
      break;
    }
    case 'buy':{
      if(T.bought)return fail('You can buy only one card per turn.');
      const open=S.market.some(s=>s.n===0);
      let stack=a.src==='m'?S.market[a.idx]:a.src==='r'?S.reserve[a.idx]:null;
      if(!stack||stack.n<=0)return fail('That card is sold out.');
      if(a.src==='r'&&!open)return fail('The reserve opens once a market slot is empty.');
      if(!distinctHand(a.cards))return fail('Pay with cards from your hand.');
      const total=a.cards.reduce((s,id)=>s+coinVal(id),0),cost=CT[stack.t].cost;
      if(total<cost)return fail('Not enough coins.');
      T.active=null;ev.push({e:'play',pl:seat,k:'buy',ts:a.cards.map(typeOf),got:stack.t,paid:total});
      for(const id of a.cards){rm(P.hand,id);const d=def(id);if(d.once&&(d.c==='y'||d.c==='x'))S.trash.push(id);else P.play.push(id);}
      const t=stack.t;
      if(a.src==='r'){const slot=S.market.findIndex(s=>s.n===0);S.market[slot]={t,n:stack.n};S.reserve.splice(a.idx,1);stack=S.market[slot];}
      stack.n--;P.discard.push(newCard(t));T.bought=true;
      log(seat,'buys '+CT[t].n+' for '+fmt(total)+' coin'+(total===1?'':'s')+'.');ev.push({e:'gain',pl:seat,t,src:a.src,idx:a.idx});
      break;
    }
    case 'end':{
      const keep=Array.isArray(a.keep)?a.keep:[];
      if(!keep.every(inHand)||new Set(keep).size!==keep.length)return fail('Bad cards to keep.');
      const toDisc=P.hand.filter(id=>!keep.includes(id));ev.push({e:'play',pl:seat,k:'end',kept:keep.length,disc:toDisc.length}); // counts only: the hand is private
      for(const id of toDisc){rm(P.hand,id);P.discard.push(id);}
      P.discard.push(...P.play);P.play=[];
      drawCards(P,Math.max(0,4-P.hand.length));reveal=true;
      log(seat,'ends the turn'+(toDisc.length?', discarding '+toDisc.length:'')+(keep.length?(toDisc.length?' and':'')+' keeping '+keep.length:'')+'.');
      S.turn={bought:false,active:null,pending:null};
      advance();ev.push({e:'turn',pl:S.cur});
      break;
    }
    default:return fail('Unknown action.');
  }
  if(S.over)ev.push({e:'over'});
  return{ok:true,ev,reveal};
}
/* who still races */
function checkEnd(){
  const n=S.players.length;
  if(S.fullRace){if(S.players.filter(isActive).length<=1&&!S.endTriggered){S.endTriggered=true;log(null,'Only one expedition is still racing. The round will be finished.');}}
  else if(S.players.some(playerDone)&&!S.endTriggered){S.endTriggered=true;log(null,'The final round has begun.');}
  if(S.players.every(p=>!isActive(p))&&S.fullRace)S.endTriggered=true;
  return n;
}
function advance(){
  const n=S.players.length;let i=S.cur;
  for(let step=0;step<n*2+2;step++){
    i=(i+1)%n;
    if(i===S.start){if(S.endTriggered){endGame();return;}S.round++;}
    const p=S.players[i];
    if(S.fullRace?isActive(p):!p.resigned){S.cur=i;return;}
  }
  endGame();
}
/* A player leaves a game for good (online): placed below everyone still racing. */
function resign(seat){
  if(!S||S.over)return{ok:false,ev:[]};
  const P=S.players[seat];if(P.resigned||playerDone(P))return{ok:false,ev:[]};
  P.resigned=++S.resigns;log(seat,'leaves the expedition.');
  const ev=[{e:'resign',pl:seat}];
  const others=S.players.filter((p,i)=>i!==seat&&!p.resigned);
  if(others.length<=1||S.players.filter(isActive).length<=1){ // nobody left to race: finish now
    if(S.players.filter(isActive).length===0||others.length<=1){endGame();ev.push({e:'over'});return{ok:true,ev};}
  }
  checkEnd();
  if(seat===S.cur){S.turn={bought:false,active:null,pending:null};advance();ev.push({e:'turn',pl:S.cur});}
  if(S.over)ev.push({e:'over'});
  return{ok:true,ev};
}
function progress(p){ // lower = closer: sum of shortest step counts from each explorer to a finishing space
  let tot=0;
  for(const k of p.pieces){if(k==='done')continue;
    const seen=new Set([k]);let q=[k],d=0,found=false;
    while(q.length&&!found){d++;const nq=[];for(const u of q)for(const n of neighbors(u)){if(seen.has(n))continue;const h=hexAt(n);if(h.type==='m')continue;if(h.type==='g'){found=true;break;}seen.add(n);nq.push(n);}q=nq;if(d>200)break;}
    tot+=found?d:999;}
  return tot;
}
function endGame(){
  S.over=true;
  const mb=p=>Math.max(0,...p.blocks.map(b=>S.blockades[b].n));
  const keyOf=(p)=>playerDone(p)?[0,p.fin,-p.blocks.length,-mb(p)]:p.resigned?[2,-p.resigned,0,0]:[1,progress(p),-p.blocks.length,-mb(p)];
  const idx=S.players.map((p,i)=>({i,k:keyOf(p)}));
  const cmp=(a,b)=>{for(let j=0;j<4;j++)if(a.k[j]!==b.k[j])return a.k[j]-b.k[j];return 0;};
  idx.sort(cmp);
  const places=new Array(S.players.length);
  idx.forEach((x,j)=>{places[x.i]=j>0&&cmp(x,idx[j-1])===0?places[idx[j-1].i]:j+1;});
  S.places=places;S.winners=places.map((p,i)=>p===1?i:-1).filter(i=>i>=0);
  log(null,S.winners.map(i=>S.players[i].name).join(' & ')+' win'+(S.winners.length>1?'':'s')+' the race to El Dorado.');
}
/* ---------- multiplayer Elo from a finishing order ---------- */
function eloDeltas(ratings,places,games){
  const n=ratings.length;const out=new Array(n).fill(0);if(n<2)return out;
  for(let i=0;i<n;i++){const K=(games[i]<10?48:32)/(n-1);
    for(let j=0;j<n;j++){if(i===j)continue;
      const E=1/(1+Math.pow(10,(ratings[j]-ratings[i])/400));
      const Sc=places[i]<places[j]?1:places[i]===places[j]?.5:0;
      out[i]+=K*(Sc-E);}}
  return out.map(x=>Math.round(x*10)/10);
}
/* ---------- what one player may see ---------- */
function redact(state,seat){
  const R=JSON.parse(JSON.stringify(state));const vis=new Set();
  R.players.forEach((p,i)=>{
    if(i===seat){p.deck=p.deck.slice().sort((a,b)=>(state.cards[a]<state.cards[b]?-1:state.cards[a]>state.cards[b]?1:0));p.hand.forEach(id=>vis.add(id));p.deck.forEach(id=>vis.add(id));}
    else{p.hand=p.hand.map((_,k)=>'h'+i+'_'+k);p.deck=p.deck.map((_,k)=>'d'+i+'_'+k);}
    p.play.forEach(id=>vis.add(id));p.discard.forEach(id=>vis.add(id));
  });
  R.trash.forEach(id=>vis.add(id));
  if(R.turn&&R.turn.active)vis.add(R.turn.active.id);
  const cards={};for(const id of vis)if(state.cards[id])cards[id]=state.cards[id];R.cards=cards;
  return R;
}

/* =========================================================
   BOT — plays through the same applyAction as a human. Runs anywhere the engine runs
   (browser for local games; Node for training). Never sees hidden information it
   shouldn't: its own draw pile is re-shuffled before every look-ahead, and opponents
   are judged only by public facts (position, blockades, the cards they own).

   Decision = greedy over "afterstates": list every legal atomic action, apply each to
   a copy of the state, score the result with value(), take the best. value() is either
   the hand-written heuristic or a small neural net trained by self-play (TD-Gammon style).
   ========================================================= */
const BOT_TYPES=Object.keys(CT);
/* ---- static distances to El Dorado, per map (cost = sum of space values along the way) ---- */
function botDist(){
  if(MAP._bd)return MAP._bd;
  const cost=new Map(),steps=new Map(),next=new Map(),pq=[];
  for(const g of MAP.goals){cost.set(g,0);steps.set(g,0);pq.push([0,g]);}
  while(pq.length){let bi=0;for(let i=1;i<pq.length;i++)if(pq[i][0]<pq[bi][0])bi=i;const[d,u]=pq.splice(bi,1)[0];if(d>cost.get(u))continue;
    const hu=hexAt(u);if(hu.type==='s')continue;           // start spaces can't be entered, so nothing routes through them
    const enter=hu.type==='g'?1:hu.val;                     // cost of stepping onto u
    for(const n of neighbors(u)){const h=hexAt(n);if(h.type==='m'||h.type==='g')continue;
      const nd=d+enter;if(!cost.has(n)||nd<cost.get(n)){cost.set(n,nd);steps.set(n,steps.get(u)+1);next.set(n,u);pq.push([nd,n]);}}}
  const mix=new Map(); // terrain still ahead on the cheapest route, per type (tells the bot what to buy)
  const near=new Map(); // the same, only for the next ~10 cost ahead (what the next few hands must handle)
  for(const k of cost.keys()){const m={j:0,w:0,v:0,r:0,c:0},m2={j:0,w:0,v:0,r:0,c:0};let x=next.get(k),guard=0,acc=0;
    while(x&&guard++<200){const h=hexAt(x);if(h.type==='g'){m[h.sym]+=1;if(acc<10)m2[h.sym]+=1;break;}if(m[h.type]!=null){m[h.type]+=h.val;if(acc<10)m2[h.type]+=h.val;}acc+=h.val||1;x=next.get(x);}mix.set(k,m);near.set(k,m2);}
  MAP._bd={cost,steps,mix,near};return MAP._bd;
}
const botCost=k=>k==='done'?0:(botDist().cost.get(k)??60);
function botRemaining(pl){const p=S.players[pl];return p.pieces.reduce((a,k)=>a+botCost(k),0)/p.pieces.length;} // route cost still ahead
/* ---- legal atomic actions for the player to move (deduplicated by card type) ---- */
function botWorth(t){const d=CT[t];if(!d)return 0;if(d.c==='p')return t==='native'?3:t==='transmitter'?3.5:2.5;return d.p*(d.c==='x'?1.25:1)+(d.once?-.5:0);}
/* every distinct subset (by card types) of `ids` with exactly k cards */
function botCombos(ids,k){const out=[],seen=new Set(),cur=[];
  const rec=i=>{if(cur.length===k){const sig=cur.map(typeOf).sort().join();if(!seen.has(sig)){seen.add(sig);out.push(cur.slice());}return;}
    for(let j=i;j<ids.length;j++){cur.push(ids[j]);rec(j+1);cur.pop();}};rec(0);return out;}
function botActions(){
  const seat=S.cur,P=S.players[seat],T=S.turn,out=[];
  // Scientist / Travel Log: remove nothing, or any distinct choice of up to `max` cards
  if(T.pending){for(let k=0;k<=Math.min(T.pending.max,P.hand.length);k++)for(const c of botCombos(P.hand,k))out.push({t:'trash',cards:c});return out;}
  const seen=new Set(),hand=P.hand.filter(id=>{const t=typeOf(id);if(seen.has(t))return false;seen.add(t);return true;}); // one of each type
  P.pieces.forEach((pk,pi)=>{if(pk==='done')return;
    if(T.active&&T.active.pi===pi)for(const[k]of reach(seat,pi,[T.active.sym],T.active.left))out.push({t:'move',card:T.active.id,pi,to:k});
    for(const id of hand){const d=def(id),t=typeOf(id);
      if(t==='native'){for(const[k]of nativeTargets(seat,pi))out.push({t:'native',card:id,pi,to:k});continue;}
      if(d.c==='p')continue;
      for(const[k]of reach(seat,pi,d.s==='*'?['j','w','v']:[d.s],d.p))out.push({t:'move',card:id,pi,to:k});}
    // rubble / base camp / rubble blockade: every distinct choice of cards to give up
    for(const[k,tg]of payTargets(seat,pi))for(const c of botCombos(P.hand,tg.need))out.push({t:'pay',pi,to:k,cards:c});
  });
  for(const id of hand){const t=typeOf(id);if(['cartographer','compass','scientist','travellog'].includes(t))out.push({t:'action',card:id});}
  const open=S.market.some(s=>s.n===0);
  const tr=hand.find(id=>typeOf(id)==='transmitter');
  if(tr){S.market.forEach((s,i)=>{if(s.n>0)out.push({t:'transmit',card:tr,src:'m',idx:i});});S.reserve.forEach((s,i)=>{if(s.n>0)out.push({t:'transmit',card:tr,src:'r',idx:i});});}
  if(!T.bought){
    // every minimal way to pay (no card could be left out), distinct by card types
    const cash=P.hand.reduce((a,id)=>a+coinVal(id),0),pays=new Map();
    const payFor=cost=>{if(pays.has(cost))return pays.get(cost);const res=[];
      for(let k=1;k<=P.hand.length&&res.length<8;k++)for(const c of botCombos(P.hand,k)){const tot=c.reduce((a,id)=>a+coinVal(id),0);if(tot>=cost&&c.every(id=>tot-coinVal(id)<cost))res.push(c);}
      pays.set(cost,res);return res;};
    const tryStack=(src,s,i)=>{if(s.n<=0||CT[s.t].cost>cash)return;for(const cards of payFor(CT[s.t].cost))out.push({t:'buy',src,idx:i,cards});};
    S.market.forEach((s,i)=>tryStack('m',s,i));if(open)S.reserve.forEach((s,i)=>tryStack('r',s,i));
  }
  // end turn keeping any distinct choice of 0–3 cards
  for(let k=0;k<=Math.min(3,P.hand.length);k++)for(const c of botCombos(P.hand,k))out.push({t:'end',keep:c});
  return out;
}
/* ---- features: everything a player can see at a glance, from `me`'s point of view ----
   No history-based deductions. Hidden: my draw-pile ORDER, opponents' hands vs. draw piles
   (but all the cards they own and their discard piles are public). The map is encoded along
   the "steps to El Dorado" axis, so the same inputs work on any course. */
const BOT_BINS=16,BOT_BW=3,BOT_NT=BOT_TYPES.length;
const BOT_NF=16*9+14+BOT_NT*4+12+3*(BOT_NT*2+8)+BOT_NT*2+2+6*9+4;
function botCounts(ids){const c=new Float32Array(BOT_NT);for(const id of ids){const k=BOT_TYPES.indexOf(S.cards[id]);if(k>=0)c[k]++;}return c;}
function botFeatures(me){
  const f=new Float32Array(BOT_NF);let i=0;const put=(v)=>{f[i++]=v;},putArr=(a,sc)=>{for(const x of a)f[i++]=x*sc;};
  const P=S.players[me],endView=S._endView===me,myTurn=S.cur===me&&!S.over&&!endView,bd=botDist(),n=S.players.length;
  const stepsOf=k=>k==='done'?0:(bd.steps.get(k)??48);
  // 1. the map, binned by steps to El Dorado: width, terrain mix, difficulty, crowding, blockades
  const bins=Array.from({length:BOT_BINS},()=>new Float32Array(9));
  const occ=new Set();S.players.forEach(p=>p.pieces.forEach(k=>{if(k!=='done')occ.add(k);}));
  for(const[k,st]of bd.steps){const h=hexAt(k);if(h.type==='g'||h.type==='s')continue;const b=bins[Math.min(BOT_BINS-1,Math.floor(st/BOT_BW))];
    b[0]++;const t='jwvrc'.indexOf(h.type);if(t>=0)b[1+t]++;b[6]+=h.val;if(occ.has(k))b[7]++;}
  S.blockades.forEach(B=>{if(B.owner!==null)return;const e=MAP.conns[B.conn].edges[0];const st=Math.min(stepsOf(e[0]),stepsOf(e[1]));bins[Math.min(BOT_BINS-1,Math.floor(st/BOT_BW))][8]+=B.v;});
  for(const b of bins){const c=b[0]||1;put(b[0]/10);for(let t=1;t<=5;t++)put(b[t]/c);put(b[6]/c/3);put(b[7]/2);put(b[8]/2);}
  // 2. me: where I am and what's ahead
  const pieceCost=p=>p.pieces.reduce((a,k)=>a+botCost(k),0)/p.pieces.length,pieceSteps=p=>p.pieces.reduce((a,k)=>a+stepsOf(k),0)/p.pieces.length;
  const myCost=pieceCost(P);put(myCost/40);put(pieceSteps(P)/40);put(Math.min(...P.pieces.map(stepsOf))/40);put(playerDone(P)?1:0);put(P.blocks.length/3);
  const mix={j:0,w:0,v:0,r:0,c:0};for(const k of P.pieces){if(k==='done')continue;const m=bd.mix.get(k);if(m)for(const s in mix)mix[s]+=m[s];}
  for(const s of'jwvrc')put(mix[s]/P.pieces.length/20);
  put(myTurn?1:0);put(((me-S.start+n)%n)/3);put(S.turn&&S.cur===me&&S.turn.bought?1:0);put(n===2?1:0);
  // 3. my cards: hand (only meaningful on my turn), draw pile, discard, in play
  // hand: my cards on my turn; in the end-of-turn view, the cards I kept
  putArr(myTurn||endView?botCounts(P.hand):new Float32Array(BOT_NT),1/3);putArr(botCounts(P.deck),1/4);putArr(botCounts(P.discard),1/4);putArr(botCounts(P.play),1/3);
  // 4. this turn: leftover strength, pending removal, what the hand could still do
  if(myTurn){const a=S.turn.active;put(a?a.left/4:0);for(const s of'jwv')put(a&&a.sym===s?1:0);put(S.turn.pending?S.turn.pending.max/2:0);
    let coins=0;for(const id of P.hand)coins+=coinVal(id);put(coins/6);put(P.hand.length/6);put(P.hand.filter(id=>def(id).c==='p').length/2);
    let bestRed=0,sumRed=0;
    for(const id of P.hand){const d=def(id);if(d.c==='p')continue;let r=0;P.pieces.forEach((pk,pi)=>{if(pk==='done')return;const base=botCost(pk);for(const[k]of reach(me,pi,d.s==='*'?['j','w','v']:[d.s],d.p)){if(k[0]!=='B')r=Math.max(r,base-botCost(k));}});bestRed=Math.max(bestRed,r);sumRed+=r;}
    if(a){const pk=P.pieces[a.pi];if(pk!=='done'){const base=botCost(pk);for(const[k]of reach(me,a.pi,[a.sym],a.left))if(k[0]!=='B'){const r=base-botCost(k);bestRed=Math.max(bestRed,r);sumRed+=r;}}}
    put(bestRed/8);put(sumRed/12);put(myCost>0?Math.min(1,sumRed/myCost):1);put(1);
  }else i+=12;
  // 5. opponents in turn order after me: all cards they own, their discard pile, position, blockades
  for(let k=1;k<=3;k++){const j=(me+k)%n;const p=k<n?S.players[j]:null;if(!p){i+=BOT_NT*2+8;continue;}
    putArr(botCounts([...p.deck,...p.hand,...p.discard,...p.play]),1/4);putArr(botCounts(p.discard),1/4);
    put(pieceCost(p)/40);put(pieceSteps(p)/40);put(playerDone(p)?1:0);put(p.resigned?1:0);put(p.blocks.length/3);put(p.hand.length/6);put(j===S.cur?1:0);put((pieceCost(p)-myCost)/20);}
  // 6. market and reserve (cards left of each type) + reserve open
  const mk=new Float32Array(BOT_NT),rs=new Float32Array(BOT_NT);S.market.forEach(s=>{mk[BOT_TYPES.indexOf(s.t)]+=s.n;});S.reserve.forEach(s=>{rs[BOT_TYPES.indexOf(s.t)]+=s.n;});
  putArr(mk,1/3);putArr(rs,1/3);put(S.market.some(s=>s.n===0)?1:0);put(S.market.filter(s=>s.n>0).length/6);
  // 7. blockades #1–6: on the board / mine / someone else's, cost, where, type
  for(let num=1;num<=6;num++){const bi=S.blockades.findIndex(B=>B.n===num);if(bi<0){i+=9;continue;}const B=S.blockades[bi];
    const e=MAP.conns[B.conn].edges[0];put(B.owner===null?1:0);put(B.owner===me?1:0);put(B.owner!==null&&B.owner!==me?1:0);put(B.v/2);put(Math.min(stepsOf(e[0]),stepsOf(e[1]))/40);
    for(const s of'jwvr')put(B.k===s?1:0);}
  // 8. game clock
  put(S.round/40);put((n-2)/2);put(S.endTriggered?1:0);put(S.players.filter(p=>playerDone(p)).length/3);
  if(i!==BOT_NF)throw new Error('bot features: wrote '+i+' of '+BOT_NF);
  return f;
}
/* ---- values ---- */
function botHeuristic(me){ // hand-tuned: be close to the goal, own a strong deck, use this turn's cards well
  const P=S.players[me];if(playerDone(P))return 100-P.fin;
  const own=[...P.deck,...P.hand,...P.discard,...P.play],tot=own.length||1;let pw=0;
  for(const id of own){const d=CT[S.cards[id]];if(d.c!=='p')pw+=d.p*(d.c==='x'?1.2:1);else pw+=1.2;}
  let v=-P.pieces.reduce((a,k)=>a+botCost(k),0)/P.pieces.length;
  v+=pw/tot*9-Math.max(0,tot-12)*.35+P.blocks.length*1.5;
  if(S.cur===me&&!S.over&&S._endView!==me){let sumRed=0;
    for(const id of P.hand){const d=def(id);if(d.c==='p')continue;let r=0;P.pieces.forEach((pk,pi)=>{if(pk==='done')return;const base=botCost(pk);for(const[k]of reach(me,pi,d.s==='*'?['j','w','v']:[d.s],d.p))if(k[0]!=='B')r=Math.max(r,base-botCost(k));});sumRed+=r;}
    const a=S.turn.active;if(a&&P.pieces[a.pi]!=='done'){const base=botCost(P.pieces[a.pi]);let r=0;for(const[k]of reach(me,a.pi,[a.sym],a.left))if(k[0]!=='B')r=Math.max(r,base-botCost(k));sumRed+=r;}
    v+=sumRed*.95;}
  return v;
}
/* Heuristic 2 (candidate benchmark): minimise the estimated number of turns still needed.
   speed = how much of the route ahead one card covers on average, given the terrain mix ahead
   (a card covers its strength on matching terrain, jokers match anything, any card pays 1 of rubble / base camp);
   turns left = (route still ahead − what this turn's hand can still cover) / (4 cards × speed). */
const BOT_ACT_SPEED={cartographer:1,compass:1.6,travellog:.9,scientist:.6,native:1.4,transmitter:.4};
function botHeuristic2(me){
  const P=S.players[me];if(playerDone(P))return 100-P.fin;
  const bd=botDist(),live=P.pieces.filter(k=>k!=='done'),cost=P.pieces.reduce((a,k)=>a+botCost(k),0)/P.pieces.length;
  const m={j:0,w:0,v:0,r:0,c:0};for(const k of live){const x=bd.mix.get(k);if(x)for(const s in m)m[s]+=x[s]/live.length;}
  const mt=m.j+m.w+m.v+m.r+m.c||1,own=[...P.deck,...P.hand,...P.discard,...P.play],tot=own.length||1;
  let move=0,acts=0;
  for(const id of own){const d=CT[S.cards[id]];
    if(d.c==='p'){acts+=BOT_ACT_SPEED[S.cards[id]]||.5;continue;}
    for(const s of'jwv')if(d.s===s||d.s==='*')move+=d.p*m[s]/mt;
    move+=(m.r+m.c)/mt;}
  const base=move/Math.max(1,tot-0),speed=Math.max(.3,base+acts/tot*base); // action cards stand in for extra cards
  let handRed=0;
  if(S.cur===me&&!S.over&&S._endView!==me){
    for(const id of P.hand){const d=def(id);if(d.c==='p')continue;let r=0;P.pieces.forEach((pk,pi)=>{if(pk==='done')return;const b=botCost(pk);for(const[k]of reach(me,pi,d.s==='*'?['j','w','v']:[d.s],d.p))if(k[0]!=='B')r=Math.max(r,b-botCost(k));});handRed+=r;}
    const a=S.turn.active;if(a&&P.pieces[a.pi]!=='done'){const b=botCost(P.pieces[a.pi]);let r=0;for(const[k]of reach(me,a.pi,[a.sym],a.left))if(k[0]!=='B')r=Math.max(r,b-botCost(k));handRed+=r;}}
  const turns=Math.max(0,cost-handRed*.9)/(4*speed);
  return -turns*10+P.blocks.length*.3;
}
/* Planner heuristic (candidate benchmark, mode 'plan'): search this turn's movement exactly, then buy.
   1. draw cards first (Scientist / Travel Log remove weak starting cards);
   2. depth-first search over every order of moves / leftover strength / rubble / base camps / Native, keeping the
      end position with the least route left (ties: more coin value left for buying);
   3. buy the most useful affordable card for the terrain still ahead; stop buying when close to the end. */
const BOT_STARTER={explorer:1,traveler:1,sailor:1};
/* planner knobs; 'plan' is the committed benchmark, other entries are candidates tried head-to-head (tools/ai/h2h.mjs) */
const BOT_PLANS={plan:{}};let BOT_PLAN_CUR=null;
const BOT_PLAN_DEF={near:0,blockAhead:0,guard:0,buyStop:7,buyMin:2,costW:.08,keepEnd:0,safeTrash:0,minDeck:0,blockW:0,transStop:7};BOT_PLAN_CUR=BOT_PLAN_DEF;
function botPlanMoves(me){
  const root=S,P0=root.players[me],memo=new Map();let best=null,nodes=0;
  const O=BOT_PLAN_CUR;
  const score=st=>{const P=st.players[me];const c=P.pieces.reduce((a,k)=>a+(k==='done'?-5:botCost(k)),0);const coin=P.hand.reduce((a,id)=>a+coinVal(id),0);
    // El Dorado can only be entered by paddling: removing my last paddle card (base camp) would strand me for good
    const stranded=P.pieces.some(k=>k!=='done')&&botPaddles(P,st)<1;
    let ahead=0;if(O.blockAhead)for(const B of st.blockades)if(B.owner===null)for(const k of P.pieces)if(k!=='done'&&hexAt(k).tile<=B.conn){ahead+=B.v;break;}
    return -(c+ahead*O.blockAhead)*10+coin+P.blocks.length*O.blockW-(stranded&&O.guard?1e4:0);};
  const dfs=(st,path,depth)=>{
    if(++nodes>4000)return;
    const sc=score(st);if(!best||sc>best.sc)best={sc,path:path.slice()};
    if(depth>=9||st.over||st.cur!==me)return;
    const P=st.players[me],key=P.pieces.join('|')+'#'+P.hand.map(id=>st.cards[id]).sort().join()+'#'+(st.turn.active?st.turn.active.id+st.turn.active.left:'');
    if(memo.has(key)&&memo.get(key)<=depth)return;memo.set(key,depth);
    S=st;const acts=botActions().filter(a=>a.t==='move'||a.t==='native'||a.t==='pay');S=root;
    // per card and explorer keep the 3 targets that get closest (the search stays small)
    const groups=new Map();for(const a of acts){const g=a.t+(a.card||'')+a.pi;if(!groups.has(g))groups.set(g,[]);groups.get(g).push(a);}
    for(const[,list]of groups){
      const ranked=list.map(a=>({a,c:a.to[0]==='B'?-1:botCost(a.to)})).sort((x,y)=>x.c-y.c).slice(0,3);
      for(const{a}of ranked){S=botClone(st);const r=applyAction(me,a);const nx=S;S=root;if(!r.ok)continue;path.push(a);dfs(nx,path,depth+1);path.pop();}
    }
  };
  dfs(botClone(root),[],0);S=root;return best?best.path:[];
}
function botCardWorth(t,me){ // how useful a new card is for the rest of the route
  const P=S.players[me],bd=botDist(),live=P.pieces.filter(k=>k!=='done');const m={j:0,w:0,v:0,r:0,c:0},nw=BOT_PLAN_CUR.near||0;
  for(const k of live){const x=bd.mix.get(k),y=bd.near.get(k);if(x){const tx=x.j+x.w+x.v+1,ty=y.j+y.w+y.v+1;
    for(const s in m)m[s]+=((1-nw)*x[s]/tx+nw*y[s]/ty)*tx/Math.max(1,live.length);}}
  const mt=m.j+m.w+m.v+1,d=CT[t];
  if(d.c==='p')return {cartographer:2.6,native:2.2,compass:2.3,scientist:2.2,travellog:2.2,transmitter:1.5}[t]||1;
  const fit=d.s==='*'?1:(m[d.s]||0)/mt;return d.p*(0.35+fit)+(d.c==='y'?0.6:0);
}
const BOT_PADDLE=t=>{const d=CT[t];return d.c!=='p'&&(d.s==='w'||d.s==='*');};
function botPaddles(P,st){const cs=(st||S).cards;return[...P.deck,...P.hand,...P.discard,...P.play].filter(id=>BOT_PADDLE(cs[id])).length;}
function botPlanChoose(me,O){
  O=BOT_PLAN_CUR={...BOT_PLAN_DEF,...(O||{})};
  const P=S.players[me],T=S.turn;
  if(T.pending){let weak=P.hand.filter(id=>BOT_STARTER[typeOf(id)]).slice(0,T.pending.max);
    if(O.safeTrash){// never trash the last cards that can paddle into El Dorado
      let pad=botPaddles(P);
      weak=weak.filter(id=>{if(BOT_PADDLE(typeOf(id))){if(pad<=O.safeTrash)return false;pad--;}return true;});}
    if(O.minDeck){const all=P.deck.length+P.hand.length+P.discard.length+P.play.length;weak=weak.slice(0,Math.max(0,all-O.minDeck));}
    return{t:'trash',cards:weak}; }
  const draw=P.hand.find(id=>BOT_DRAW[typeOf(id)]);if(draw)return{t:'action',card:draw};
  const moves=botPlanMoves(me);if(moves.length)return moves[0];
  // buy with what's left
  const left=botRemaining(me);
  if(!T.bought&&left>O.buyStop){
    const cash=P.hand.reduce((a,id)=>a+coinVal(id),0),open=S.market.some(s=>s.n===0);let pick=null;
    const consider=(src,s,i)=>{if(s.n<=0||CT[s.t].cost>cash)return;const w=botCardWorth(s.t,me)*(1+CT[s.t].cost*O.costW);if(!pick||w>pick.w)pick={w,src,idx:i};};
    S.market.forEach((s,i)=>consider('m',s,i));if(open)S.reserve.forEach((s,i)=>consider('r',s,i));
    if(pick&&pick.w>O.buyMin){const buys=botActions().filter(a=>a.t==='buy'&&a.src===pick.src&&a.idx===pick.idx);
      if(buys.length){buys.sort((a,b)=>a.cards.length-b.cards.length);return buys[0];}}
  }
  const tr=P.hand.find(id=>typeOf(id)==='transmitter');
  if(tr&&left>O.transStop){let pick=null;const c=(src,s,i)=>{if(s.n<=0)return;const w=botCardWorth(s.t,me)+CT[s.t].cost*.3;if(!pick||w>pick.w)pick={w,src,idx:i};};S.market.forEach((s,i)=>c('m',s,i));S.reserve.forEach((s,i)=>c('r',s,i));if(pick)return{t:'transmit',card:tr,src:pick.src,idx:pick.idx};}
  if(O.keepEnd){// keep unplayed strong cards (not starters) for next turn
    const keep=P.hand.filter(id=>!BOT_STARTER[typeOf(id)]&&CT[typeOf(id)].c!=='p'&&(CT[typeOf(id)].p||0)>=O.keepEnd).slice(0,3);return{t:'end',keep};}
  return{t:'end',keep:[]};
}
/* ---- per-map network input: the summary above + every space on this course + every tile connection ----
   Each space gets 4 slots (my explorer here / opponent 1, 2, 3 here, in turn order after me);
   each connection between tiles gets 8 (which blockade type was dealt there, its cost, owned by nobody / me / an opponent).
   The terrain itself never changes on a given course, so the network learns it per slot. */
function botMapOrder(){if(MAP._bo)return MAP._bo;const keys=[...MAP.hexes.keys()].filter(k=>MAP.hexes.get(k).type!=='m').sort();const idx=new Map(keys.map((k,i)=>[k,i]));MAP._bo={keys,idx};return MAP._bo;}
/* multi-course networks (net.courses = [course ids]): input = the summary (BOT_NF) + BOT_FLAGS rule switches + one board block per
   course in that order; only the current course's block is filled. Single-course networks (net.course) keep the old layout. */
const BOT_FLAGS=4,BOT_BLOCK={};
function botBlockSize(id){if(BOT_BLOCK[id]!=null)return BOT_BLOCK[id];const C=courseById(id);if(!C)return BOT_BLOCK[id]=0;
  const m=MAP&&MAP.course===id?MAP:buildCourse(C,1),keys=[...m.hexes.keys()].filter(k=>m.hexes.get(k).type!=='m');return BOT_BLOCK[id]=keys.length*4+m.conns.length*8;}
const botMulti=()=>!!(BOT_NET&&BOT_NET.courses);
function botNetNF(){if(botMulti())return BOT_NF+BOT_FLAGS+BOT_NET.courses.reduce((a,id)=>a+botBlockSize(id),0);return BOT_NF+botMapOrder().keys.length*4+MAP.conns.length*8;}
function botNetFeatures(me){
  const{keys,idx}=botMapOrder(),n=S.players.length,f=new Float32Array(botNetNF());
  f.set(botFeatures(me),0);let o=BOT_NF;
  if(botMulti()){f[o]=S.rules&&S.rules.campOnce?1:0;o+=BOT_FLAGS;for(const id of BOT_NET.courses){if(id===MAP.course)break;o+=botBlockSize(id);}}
  S.players.forEach((p,j)=>{const rel=(j-me+n)%n;if(rel>3)return;for(const k of p.pieces){if(k==='done')continue;const x=idx.get(k);if(x!=null)f[o+x*4+rel]=1;}});
  o+=keys.length*4;
  S.blockades.forEach(B=>{const c=o+B.conn*8;const t='jwvr'.indexOf(B.k);if(t>=0)f[c+t]=1;f[c+4]=B.v/2;f[c+5]=B.owner===null?1:0;f[c+6]=B.owner===me?1:0;f[c+7]=B.owner!==null&&B.owner!==me?1:0;});
  return f;
}
/* network: {course, nf, w1T (input-major, nf×h1), b1, w2 (h2×h1), b2, w3 (h2), b3}; leaky-ReLU, sigmoid out.
   The first layer only touches non-zero inputs (most board slots are empty), so it stays fast in the browser. */
let BOT_NET=null;
let BOT_EVALS=0;
function botNetValue(f){BOT_EVALS++;const N=BOT_NET,H1=N.b1.length,H2=N.b2.length;const h1=Float32Array.from(N.b1);
  for(let k=0;k<f.length;k++){const x=f[k];if(x===0)continue;const r=k*H1,w=N.w1T;for(let j=0;j<H1;j++)h1[j]+=w[r+j]*x;}
  for(let j=0;j<H1;j++)if(h1[j]<0)h1[j]*=.01;
  let s=N.b3[0];for(let j=0;j<H2;j++){let a=N.b2[j];const r=j*H1;for(let k=0;k<H1;k++)a+=N.w2[r+k]*h1[k];s+=N.w3[j]*(a>0?a:.01*a);}
  return 1/(1+Math.exp(-s));}
const botNetReady=()=>!!(BOT_NET&&MAP&&(botMulti()?BOT_NET.courses.includes(MAP.course):BOT_NET.course===MAP.course)&&BOT_NET.nf===botNetNF());
/* what a finishing place is worth: 1st = 1, 2nd = 1/BOT_FIRST_RATIO, each further place half the one above, last = 0
   (3 players: 1, ¼, 0 · 4 players: 1, ¼, ⅛, 0). Training targets use the same values (tools/ai/gen.mjs). */
const BOT_FIRST_RATIO=4;
function botPlaceValue(pl,n){return pl>=n?0:pl<=1?1:1/BOT_FIRST_RATIO/2**(pl-2);}
// my place is final once no one still racing moves after me in this round (turn order runs from S.start)
function botPlaceSettled(me){const n=S.players.length;for(let i=(me+1)%n;i!==S.start;i=(i+1)%n)if(isActive(S.players[i]))return false;return true;}
function botValue(me,mode){
  if(S.over){const pl=S.places[me],n=S.players.length;return mode==='net'?botPlaceValue(pl,n):1e3-pl*100;}
  const P=S.players[me];
  if(playerDone(P)){
    // arrived, but players still to move this round can arrive in the same round and beat me on the tie-break
    // (more blockades, then the biggest blockade): until the round is over my place is a chance, which the network estimates
    // once it has been trained on such positions (net.unsettled); older networks get the place as if settled (optimistic)
    if(mode==='net'&&botNetReady()&&BOT_NET.unsettled&&!botPlaceSettled(me))return botNetValue(botNetFeatures(me));
    // settled: only players who arrived earlier, or in the same round with a better tie-break, are ahead of me (as endGame ranks)
    const n=S.players.length,mb=p=>Math.max(0,...p.blocks.map(b=>S.blockades[b].n));
    const pl=1+S.players.filter(q=>q!==P&&playerDone(q)&&(q.fin<P.fin||q.fin===P.fin&&(q.blocks.length>P.blocks.length||q.blocks.length===P.blocks.length&&mb(q)>mb(P)))).length;
    return mode==='net'?botPlaceValue(pl,n):1e3-pl*100;}
  return mode==='net'&&botNetReady()?botNetValue(botNetFeatures(me)):mode==='heur2'?botHeuristic2(me):botHeuristic(me);
}
/* ---- choose and play ---- */
/* fast structural copy of the game state (everything applyAction can change gets its own copy) */
function botClone(st){
  const t=st.turn;
  // cards (id → type) gets its own copy: buying or transmitting creates a card, and look-ahead copies that each bought
  // something different must not overwrite each other's new card (they reuse the same next id)
  return{...st,cards:{...st.cards},log:[],trash:st.trash.slice(),
    players:st.players.map(p=>({...p,pieces:p.pieces.slice(),deck:p.deck.slice(),hand:p.hand.slice(),discard:p.discard.slice(),play:p.play.slice(),blocks:p.blocks.slice()})),
    market:st.market.map(x=>({...x})),reserve:st.reserve.map(x=>({...x})),blockades:st.blockades.map(b=>({...b})),
    turn:{...t,active:t.active&&{...t.active},pending:t.pending&&{...t.pending}},
    winners:st.winners&&st.winners.slice(),places:st.places&&st.places.slice()};
}
/* "My turn is over, next hand not drawn yet": played and unkept cards go to the discard pile.
   Scoring "end turn" here (instead of after the real draw) values it as an expectation over the draw, without peeking. */
function botEndView(me,keep){const P=S.players[me];keep=(keep||[]).filter(id=>P.hand.includes(id));
  P.discard.push(...P.play,...P.hand.filter(id=>!keep.includes(id)));P.play=[];P.hand=keep.slice();
  S.turn={bought:false,active:null,pending:null};S._endView=me;}
function botEndFeatures(me,keep){const root=S;S=botClone(root);botEndView(me,keep);const f=botNetFeatures(me);S=root;return f;}
const BOT_DRAW={cartographer:1,compass:1,scientist:1,travellog:1};
/* Pick an action. Each option is scored by the value network's estimate of my chance of finishing ahead
   from the position right after it (TD-Gammon / AlphaZero style; mid-turn positions include the cards still in hand).
   Chance is handled as an expectation: "end turn" is scored before the next hand is drawn (botEndView), and a card that
   draws is scored as the average over opts.draws imagined draws from my (unordered) draw pile.
   Training exploration: eps = uniformly random action; temp = softmax over scores; turnState.forceBuy = a random purchase this turn. */
function botChoose(opts){
  opts=opts||{};let mode=opts.mode||(BOT_NET?'net':'heur');const eps=opts.eps||0,rnd=opts.rnd||Math.random;
  if(mode.startsWith('plan'))return{a:botPlanChoose(S.cur,BOT_PLANS[mode])};
  const me=S.cur,root=S;let acts=botActions();if(mode==='net'&&!botNetReady())mode='heur';
  if(opts.turnState&&opts.turnState.noBuy){const f=acts.filter(a=>a.t!=='buy'&&a.t!=='transmit');if(f.length)acts=f;} // exploration: a turn without gaining a card
  if(eps&&rnd()<eps)return{a:acts[Math.floor(rnd()*acts.length)],why:'random'};
  // typed exploration: a random KIND of decision (buy / remove / keep / pay rubble / play a draw card / …), then a random option of it,
  // so rare decisions get explored as much as common ones
  if(opts.typeEps&&rnd()<opts.typeEps){const kinds=[...new Set(acts.map(a=>a.t))],k=kinds[Math.floor(rnd()*kinds.length)],L=acts.filter(a=>a.t===k);return{a:L[Math.floor(rnd()*L.length)],why:'typed'};}
  const ts=opts.turnState;
  if(ts&&ts.forceBuy&&!S.turn.bought){const buys=acts.filter(a=>a.t==='buy');if(buys.length){ts.forceBuy=false;return{a:buys[Math.floor(rnd()*buys.length)],why:'forceBuy'};}}
  if(ts&&ts.forceTransmit){const tr=acts.filter(a=>a.t==='transmit');if(tr.length){ts.forceTransmit=false; // a random card, reserve included, weighted toward expensive ones (cost²)
    const w=tr.map(a=>{const s=a.src==='m'?S.market[a.idx]:S.reserve[a.idx];return CT[s.t].cost**2;});let r=rnd()*w.reduce((x,y)=>x+y,0);for(let i=0;i<tr.length;i++){r-=w[i];if(r<=0)return{a:tr[i],why:'forceTransmit'};}return{a:tr[tr.length-1],why:'forceTransmit'};}}
  // search (after exploration, so random / typed moves and no-buy turns still happen in training)
  if(opts.search&&mode==='net')return opts.search.kind==='plan'?botPlanTurnChoose(opts):opts.search.kind==='deep'?botDeepChoose(opts):opts.search.kind==='rollout'?botRolloutChoose(opts):botTurnSearch(opts);
  const vals=[];let best=null,bv=-Infinity;const K=opts.draws||4;
  const one=a=>{S=botClone(root);shuffle(S.players[me].deck,rnd);let v;
    if(a.t==='end'){botEndView(me,a.keep);v=botValue(me,mode);}
    else{const r=applyAction(me,a);v=r.ok?botValue(me,mode):-Infinity;}
    S=root;return v;};
  for(const a of acts){
    let v=a.t==='action'&&BOT_DRAW[typeOf(a.card)]?[...Array(K)].reduce(x=>x+one(a),0)/K:one(a);
    if(opts.noise&&v>-Infinity)v+=(rnd()-.5)*opts.noise;
    vals.push(v);if(v>bv){bv=v;best=a;}
  }
  // exploration by log-odds: pick each option with probability ∝ (its odds of winning)^(1/lotemp), so every option is tried,
  // near-best ones often and clearly worse ones rarely (Boltzmann over logits; probabilities clamped to [0.002, 0.998])
  if(opts.lotemp&&acts.length>1){const lo=v=>{const p=Math.min(.998,Math.max(.002,v));return Math.log(p/(1-p));},lb=lo(bv);
    const w=vals.map(v=>v===-Infinity?0:Math.exp((lo(v)-lb)/opts.lotemp)),tot=w.reduce((x,y)=>x+y,0);let r=rnd()*tot;
    for(let i=0;i<acts.length;i++){r-=w[i];if(r<=0)return{a:acts[i],v:vals[i],best:bv,why:acts[i]===best?undefined:'explore'};}}
  if(opts.temp&&acts.length>1){const w=vals.map(v=>v===-Infinity?0:Math.exp((v-bv)/opts.temp)),tot=w.reduce((x,y)=>x+y,0);let r=rnd()*tot;
    for(let i=0;i<acts.length;i++){r-=w[i];if(r<=0)return{a:acts[i],v:vals[i],best:bv,why:acts[i]===best?undefined:'softmax'};}}
  return{a:best||{t:'end',keep:[]},v:bv,best:bv,alts:opts.explain?acts.map((x,i)=>({a:x,v:vals[i]})).sort((x,y)=>y.v-x.v).slice(0,5):undefined};
}
/* ---- search at decision time (experiments; training and normal play don't use it) ----
   Same value network, but look further ahead before choosing. */
// score every legal action by the value right after it (what the plain bot does); returns [{a,v,st}] best first,
// st = the position after the action when my turn goes on (null when it ended, the game ended, or a card was drawn)
function botScoreActions(me,rnd,K){
  const root=S,acts=botActions(),out=[];
  for(const a of acts){
    if(a.t==='end'){S=botClone(root);shuffle(S.players[me].deck,rnd);botEndView(me,a.keep);out.push({a,v:botValue(me,'net'),st:null});S=root;continue;}
    if(a.t==='action'&&BOT_DRAW[typeOf(a.card)]){let v=0;for(let k=0;k<K;k++){S=botClone(root);shuffle(S.players[me].deck,rnd);const r=applyAction(me,a);v+=r.ok?botValue(me,'net'):-1;S=root;}out.push({a,v:v/K,st:null});continue;}
    S=botClone(root);shuffle(S.players[me].deck,rnd);const r=applyAction(me,a);
    const v=r.ok?botValue(me,'net'):-Infinity,st=r.ok&&!S.over&&S.cur===me?S:null;S=root;out.push({a,v,st});
  }
  return out.sort((x,y)=>y.v-x.v);
}
/* 0. whole-turn planner (beam search over my own turn). My turn has almost no luck (only cards drawn by draw cards), so plan
   it: keep the `beam` most promising partial turns (ranked by the network's value), extend each by every legal action, and
   let every line also end the turn at each step (every choice of cards to keep). Lines are compared by the network's value
   of the end-of-turn position (before the next draw: what it is trained on); a draw card is scored as the average over
   `draws` imagined draws and ends that line (the real draw reveals new cards, so the plan is redone after it). The same
   position reached in a different order is expanded once. The plan is made once per turn and followed; it is redone after
   a draw card, or if the next step is no longer legal. Cost ≈ beam × the plain bot's (measured with BOT_EVALS). */
function botTurnKey(me){const P=S.players[me],T=S.turn,ty=ids=>ids.map(typeOf).sort().join(',');
  return[P.pieces.join('|'),ty(P.hand),ty(P.play),P.discard.length,ty(P.discard),T.bought?1:0,T.active?typeOf(T.active.id)+T.active.pi+T.active.sym+T.active.left:'',T.pending?T.pending.max:'',
    S.market.map(x=>x.n).join(''),S.reserve.map(x=>x.n).join(''),S.blockades.map(b=>b.owner??'-').join(''),S.trash.length].join('#');}
function botPlanTurn(me,B,rnd,K,noBuy,top){ // top: optional array that receives every complete line {v,line}
  const root=S,seen=new Set(),start=botClone(root);S=start;shuffle(S.players[me].deck,rnd);S=root; // my deck order stays hidden
  let beam=[{st:start,line:[]}],best={v:-Infinity,line:null};
  for(let depth=0;depth<14&&beam.length;depth++){
    const next=[];
    for(const node of beam){
      S=node.st;const acts=botActions();S=root;
      for(const a of acts){
        if(noBuy&&(a.t==='buy'||a.t==='transmit'))continue; // exploration: a turn without gaining a card
        const line=[...node.line,a];
        if(a.t==='end'){S=botClone(node.st);botEndView(me,a.keep);const v=botValue(me,'net');S=root;if(top)top.push({v,line});if(v>best.v)best={v,line};continue;}
        if(a.t==='action'&&BOT_DRAW[typeOf(a.card)]){let v=0;for(let k=0;k<K;k++){S=botClone(node.st);shuffle(S.players[me].deck,rnd);const r=applyAction(me,a);v+=r.ok?botValue(me,'net'):-1;S=root;}v/=K;if(top)top.push({v,line});if(v>best.v)best={v,line,draw:true};continue;}
        S=botClone(node.st);const r=applyAction(me,a);
        if(!r.ok){S=root;continue;}
        const v=botValue(me,'net');
        if(S.over||S.cur!==me){S=root;if(top)top.push({v,line});if(v>best.v)best={v,line};continue;}          // the action ended my turn / the game
        const key=botTurnKey(me);if(seen.has(key)){S=root;continue;}seen.add(key);
        next.push({st:S,line,v});S=root;
      }
    }
    next.sort((x,y)=>y.v-x.v);beam=next.slice(0,B);
  }
  S=root;return best;
}
let BOT_PLAN_CACHE=null;
function botPlanTurnChoose(opts){
  const me=S.cur,o=opts.search,rnd=opts.rnd||Math.random,C=BOT_PLAN_CACHE;
  // follow the current plan while it still applies (same player, same round, same position the plan expects)
  if(C&&C.me===me&&C.round===S.round&&C.i<C.line.length&&C.key===botTurnKey(me)){
    const a=C.line[C.i];const root=S;S=botClone(root);const ok=applyAction(me,a).ok;const nk=ok&&!S.over&&S.cur===me?botTurnKey(me):null;S=root;
    if(ok){C.i++;C.key=nk;if(a.t==='action'&&BOT_DRAW[typeOf(a.card)])BOT_PLAN_CACHE=null;return{a,v:C.v,why:'plan'};}
  }
  const best=botPlanTurn(me,o.beam||3,rnd,opts.draws||4,!!(opts.turnState&&opts.turnState.noBuy));
  if(!best.line||!best.line.length){BOT_PLAN_CACHE=null;return{a:{t:'end',keep:[]},why:'plan'};}
  const a=best.line[0];const root=S;S=botClone(root);applyAction(me,a);const nk=!S.over&&S.cur===me?botTurnKey(me):null;S=root;
  BOT_PLAN_CACHE=best.line.length>1&&!(a.t==='action'&&BOT_DRAW[typeOf(a.card)])?{me,round:S.round,line:best.line,i:1,key:nk,v:best.v}:null;
  return{a,v:best.v,why:'plan'};
}
/* 0b. deep planner (experiment): the whole-turn planner's best K complete turns, each played forward `depth` more of my turns
   (everyone plays the planner; hidden cards re-dealt at random: my deck order, opponents' hands and decks; the same deals for
   every candidate), scored by the network where the playout stops (exact once places are settled). Successive halving
   spends `budget` network evaluations (BOT_EVALS). The chosen turn is then followed like a normal plan. */
function botDeepPlayout(root,me,line,seed,o){
  const g=mulberry32(seed),saved=BOT_PLAN_CACHE;BOT_PLAN_CACHE=null;S=botClone(root);const r0=RNG;setRng(g);
  S.players.forEach((p,j)=>{if(j===me){shuffle(p.deck,g);return;}const pool=shuffle([...p.hand,...p.deck],g);p.hand=pool.slice(0,p.hand.length);p.deck=pool.slice(p.hand.length);});
  for(const a of line){if(S.over||S.cur!==me)break;if(!applyAction(me,a).ok){applyAction(me,{t:'end',keep:[]});break;}}
  let away=S.cur!==me,turns=0,n=0;
  while(!S.over&&n++<3000){
    if(S.cur!==me)away=true;else if(away){away=false;if(++turns>=o.depth)break;}
    if(S.round>25){endGame();break;}
    const c=botChoose({mode:'net',rnd:g,search:{kind:'plan',beam:o.beam||3}});
    if(!applyAction(S.cur,c.a).ok)applyAction(S.cur,{t:'end',keep:[]});
  }
  const v=botValue(me,'net');RNG=r0;BOT_PLAN_CACHE=saved;S=root;return v;
}
function botDeepChoose(opts){
  const me=S.cur,o=opts.search,rnd=opts.rnd||Math.random,C=BOT_PLAN_CACHE;
  if(C&&C.me===me&&C.round===S.round&&C.i<C.line.length&&C.key===botTurnKey(me))return botPlanTurnChoose({...opts,search:{kind:'plan',beam:o.beam||3}});
  const root=S,top=[],e0=BOT_EVALS;const best=botPlanTurn(me,o.beam||3,rnd,opts.draws||4,!!(opts.turnState&&opts.turnState.noBuy),top);S=root;
  if(!best.line||!best.line.length){BOT_PLAN_CACHE=null;return{a:{t:'end',keep:[]},why:'plan'};}
  top.sort((x,y)=>y.v-x.v);const cands=[];for(const t of top){if(cands.length>=(o.cands||3))break;if(!cands.some(c=>Math.abs(c.v1-t.v)<1e-9))cands.push({line:t.line,v1:t.v,sum:0,n:0});}
  let pick=cands[0],info={cands:cands.length,playouts:0};
  if(cands.length>1){let live=cands,per=1,rounds=0;
    // rounds cap: playouts that end the game at once cost no network evaluations, so the budget alone could never run out
    while(live.length>1&&BOT_EVALS-e0<o.budget&&rounds++<8){
      const seeds=[...Array(per)].map(()=>(rnd()*2**31)|0);
      for(const c of live)for(const sd of seeds){c.sum+=botDeepPlayout(root,me,c.line,sd,o);c.n++;info.playouts++;}
      live.sort((x,y)=>y.sum/y.n-x.sum/x.n);
      if(BOT_EVALS-e0>=o.budget*.5&&live.length>2)live=live.slice(0,Math.ceil(live.length/2));else if(BOT_EVALS-e0>=o.budget*.75)live=live.slice(0,1);
      per=Math.min(per*2,8);
    }
    cands.sort((x,y)=>(y.n?y.sum/y.n:-1)-(x.n?x.sum/x.n:-1));pick=cands[0];}
  S=root;const line=pick.line,a=line[0];S=botClone(root);applyAction(me,a);const nk=!S.over&&S.cur===me?botTurnKey(me):null;S=root;
  BOT_PLAN_CACHE=line.length>1&&!(a.t==='action'&&BOT_DRAW[typeOf(a.card)])?{me,round:S.round,line,i:1,key:nk,v:pick.v1}:null;
  return{a,v:pick.v1,why:pick.v1===best.v?'deep-agrees':'deep-changed',deep:info};
}
/* 1. turn search: look through whole sequences of my remaining actions this turn (top `width` actions at each step,
   up to `depth` steps), score each line by the network where it stops, play the first action of the best line */
function botTurnSearch(opts){
  const me=S.cur,root=S,rnd=opts.rnd||Math.random,W=opts.search.width||3,D=opts.search.depth||4,K=opts.draws||4;let nodes=0;
  const best=(st,d)=>{S=st;const sc=botScoreActions(me,rnd,K);S=root;nodes++;let bv=-Infinity,ba=null;
    sc.forEach((x,i)=>{let v=x.v;if(x.st&&d>1&&i<W&&x.v>-Infinity)v=Math.max(v,best(x.st,d-1).v);if(v>bv){bv=v;ba=x.a;}});return{v:bv,a:ba};};
  const r=best(root,D);S=root;return{a:r.a||{t:'end',keep:[]},v:r.v,why:'turnSearch',nodes};
}
/* 2. rollouts (Monte Carlo): for the top `cands` actions, `sims` times each: hide what I can't see (reshuffle opponents' hands+decks
   and my deck), play on with the plain network for everyone until my next turn starts (or the game ends), score it.
   The same random samples are used for every candidate. Only used when the plain bot's top choices are within `margin`. */
function botRolloutChoose(opts){
  const me=S.cur,root=S,rnd=opts.rnd||Math.random,o=opts.search,C=o.cands||3,M=o.sims||6,K=opts.draws||4;
  const sc=botScoreActions(me,rnd,K);S=root;
  if(sc.length<2||sc[0].v-sc[1].v>(o.margin??.03))return{a:sc[0].a,v:sc[0].v,why:'clear'};
  const cand=sc.slice(0,C).filter(x=>x.v>-Infinity),seeds=[...Array(M)].map(()=>(rnd()*2**31)|0),prevRng=RNG;let best=null;
  for(const c of cand){let tot=0;
    for(const seed of seeds){const g=mulberry32(seed);S=botClone(root);RNG=g;
      S.players.forEach((p,j)=>{if(j===me){shuffle(p.deck,g);return;}const pool=shuffle([...p.hand,...p.deck],g);p.hand=pool.slice(0,p.hand.length);p.deck=pool.slice(p.hand.length);});
      let r=applyAction(me,c.a),left=400,passed=false;
      while(r.ok&&!S.over&&left-->0){if(S.cur!==me)passed=true;else if(passed)break;
        RNG=Math.random;const ch=botChoose({mode:'net',rnd:g});RNG=g;r=applyAction(S.cur,ch.a);if(!r.ok)r=applyAction(S.cur,{t:'end',keep:[]});}
      tot+=S.over||S.cur!==me?botValue(me,'net'):botValue(me,'net');S=root;}
    RNG=prevRng;const v=tot/M;if(!best||v>best.v)best={a:c.a,v};}
  RNG=prevRng;S=root;return{a:best?best.a:sc[0].a,v:best?best.v:sc[0].v,why:'rollout'};
}
/* play one whole turn for the player to move (used by the UI and the simulator) */
function botTurn(opts){const me=S.cur;const steps=[];for(let g=0;g<40&&!S.over&&S.cur===me;g++){const{a}=botChoose(opts);const r=applyAction(me,a);steps.push(a);if(!r.ok){applyAction(me,{t:'end',keep:[]});break;}}return steps;}

/* ---- random courses for training (so the bot learns to play, not to memorise one map) ----
   Boards chained edge to edge, never touching non-neighbours; random sides and rotations;
   start board rotated so its start row faces away from the route; El Dorado on the far edge. */
function botRandomCourse(seed,nMid){
  const rnd=mulberry32(seed),TV=[[7,-3],[3,4],[-4,7],[-7,3],[-3,-4],[4,-7]],pairs=[['C','D'],['E','F'],['G','H'],['I','J'],['K','L'],['M','N']];
  for(let attempt=0;attempt<400;attempt++){
    const cs=[[0,0]];let ok=true,dir=Math.floor(rnd()*6);
    for(let b=0;b<nMid;b++){let placed=false;
      for(const dd of shuffle([0,1,-1,0,1,-1,2,-2],rnd)){const d=(dir+dd+6)%6,L=cs[cs.length-1],c=[L[0]+TV[d][0],L[1]+TV[d][1]];
        if(cs.some((p,j)=>(p[0]===c[0]&&p[1]===c[1])||(j<cs.length-1&&TV.some(v=>p[0]+v[0]===c[0]&&p[1]+v[1]===c[1]))))continue;
        cs.push(c);dir=d;placed=true;break;}
      if(!placed){ok=false;break;}}
    if(!ok)continue;
    const mids=shuffle(pairs.slice(),rnd).slice(0,nMid).map(p=>p[rnd()<.5?0:1]);
    const start=rnd()<.5?'A':'B';
    // start rotation: start row as far as possible from the next board
    let bestK=0,bestD=-1;const nx=pxOf(cs[1][0],cs[1][1]);
    for(let k=0;k<6;k++){const pts=TPL[start].filter(c=>c.d.type==='s').map(c=>rot(c.q,c.r,k));const m=pts.reduce((a,[q,r])=>{const[x,y]=pxOf(q,r);return a+Math.hypot(x-nx[0],y-nx[1]);},0);if(m>bestD){bestD=m;bestK=k;}}
    const p=[[start,0,0,bestK],...mids.map((L,j)=>[L,cs[j+1][0],cs[j+1][1],Math.floor(rnd()*6)])];
    // El Dorado: try spaces just beyond the last board, farthest from the previous one first
    const last=cs[cs.length-1],prev=cs[cs.length-2],cand=[];
    for(let dq=-4;dq<=4;dq++)for(let dr=-4;dr<=4;dr++){const q=last[0]+dq,r=last[1]+dr,dist=(Math.abs(dq)+Math.abs(dr)+Math.abs(dq+dr))/2;if(dist!==4)continue;
      const[x,y]=pxOf(q,r),[px,py]=pxOf(prev[0],prev[1]);cand.push([q,r,Math.hypot(x-px,y-py)]);}
    cand.sort((a,b)=>b[2]-a[2]);
    for(const[q,r]of cand.slice(0,8)){const C={id:'rnd'+seed,name:'Random '+seed,p,e:[q,r],s:rnd()<.5?'j':'w'};try{buildCourse(C,1);return C;}catch(e){}}
  }
  return null;
}

/* =========================================================
   NAMED AI PLAYERS — thin layer over the bot (engine_bot.js), shared by local games (browser)
   and online rooms (the Room Durable Object runs them server-side).
   Doesn't change how the bot decides; it only picks the bot's settings per AI and keeps the
   whole-turn planner's cache per game (the cache is module-global and a server isolate runs many rooms).
   ========================================================= */
/* rating: the calibrated starting rating (tools/ai/calibrate_ais.mjs: AI-vs-AI games, Raleigh anchored at 1200 = a new player);
   the server applies it once (worker.js ensureSchema). */
const AIS=[
  {id:'humboldt',name:'Humboldt',tier:'Master',rating:1530,desc:'Neural network that plans each whole turn',opts:{mode:'net',search:{kind:'plan',beam:3}}},
  {id:'orellana',name:'Orellana',tier:'Strong',rating:1483,desc:'Neural network, one move at a time',opts:{mode:'net'}},
  {id:'raleigh',name:'Raleigh',tier:'Steady',rating:1200,desc:'Hand-written route planner',opts:{mode:'plan'}},
];
const aiById=id=>AIS.find(a=>a.id===id)||null;
const aiUsesNet=id=>{const a=aiById(id);return!!(a&&a.opts.mode==='net');};
/* the shipped network: see tools/ai/pack.mjs for the format (half floats) */
function aiNetDecode(bin){
  const u8=bin instanceof Uint8Array?bin:new Uint8Array(bin),dv=new DataView(u8.buffer,u8.byteOffset,u8.byteLength);
  const hl=dv.getUint32(0,true),H=JSON.parse(new TextDecoder().decode(u8.subarray(4,4+hl)));
  let o=4+hl+((4+hl)&1);const N={course:H.course,nf:H.nf,unsettled:H.unsettled,name:H.name};
  const half=h=>{const s=h&0x8000?-1:1,e=(h>>10)&31,m=h&1023;return e===0?s*m*2**-24:e===31?(m?NaN:s*Infinity):s*(1+m/1024)*2**(e-15);};
  const tab=new Float32Array(65536);for(let i=0;i<65536;i++)tab[i]=half(i);
  for(const[k,n]of H.parts){const a=new Float32Array(n);for(let i=0;i<n;i++,o+=2)a[i]=tab[dv.getUint16(o,true)];N[k]=a;}
  return N;
}
function aiSetNet(n){BOT_NET=n;}
const aiNetFits=()=>botNetReady();
/* one decision for the AI in seat S.cur. mem: per-game object ({}) that keeps the turn planner's cache between calls.
   Returns a legal action (falls back to ending the turn). */
function aiChoose(id,mem){
  const A=aiById(id)||AIS[AIS.length-1];mem=mem||{};
  let opts=A.opts;if(opts.mode==='net'&&(!botNetReady()||S.players.length===2))opts={mode:'plan'}; // network missing, trained for another course, or a 2-player game (never trained on those: it mostly failed to arrive)
  const me=S.cur,tk=me+':'+S.round;if(mem.tk!==tk){mem.tk=tk;mem.n=0;}
  if(++mem.n>60)return S.turn.pending?{t:'trash',cards:[]}:{t:'end',keep:[]}; // never loop inside a turn
  const r0=RNG;setRng(null);BOT_PLAN_CACHE=mem.plan||null;
  let a=null;try{a=botChoose(opts).a;}finally{mem.plan=BOT_PLAN_CACHE;BOT_PLAN_CACHE=null;RNG=r0;}
  return a||(S.turn.pending?{t:'trash',cards:[]}:{t:'end',keep:[]});
}
/* apply the AI's decision; if it is somehow illegal, end the turn instead. Returns applyAction's result. */
function aiStep(id,mem){
  const me=S.cur,a=aiChoose(id,mem);let r=applyAction(me,a);
  if(!r.ok){if(S.turn.pending)applyAction(me,{t:'trash',cards:[]});S.turn.active=null;r=applyAction(me,{t:'end',keep:[]});}
  return r;
}

export const E={AIS,aiById,aiUsesNet,aiNetDecode,aiSetNet,aiNetFits,aiChoose,aiStep,get MAPX(){return MAP},get BOT_EVALS(){return BOT_EVALS},botScoreActions,botPlaceValue,botPlaceSettled,setRng,replayCheck,replayStart,mulberry32,botCost,botRemaining,botEndFeatures,botClone,botRandomCourse,botNetFeatures,botNetNF,botNetValue,botChoose,botTurn,botActions,botFeatures,botValue,endGame,BOT_NF,BOT_FLAGS,setNet(n){BOT_NET=n},setPlan(k,o){BOT_PLANS[k]=o},get BOT_PLANS(){return BOT_PLANS},buildCourse,mapFor,COURSES,courseById,newGame,applyAction,resign,eloDeltas,redact,reach,payTargets,nativeTargets,playerDone,CT,get S(){return S},set S(v){S=v},get MAP(){return MAP},set MAP(v){MAP=v}};
