// GENERATED by build.mjs from engine_data.js + engine_rules.js. Do not edit.
/* =========================================================
   CARD DATA (base game)
   ========================================================= */
const CT={
  explorer:{n:'Explorer',c:'g',s:'j',p:1},
  traveler:{n:'Traveler',c:'y',s:'v',p:1},
  sailor:{n:'Sailor',c:'b',s:'w',p:1},
  scout:{n:'Scout',c:'g',s:'j',p:2,cost:1},
  trailblazer:{n:'Trailblazer',c:'g',s:'j',p:3,cost:3},
  pioneer:{n:'Pioneer',c:'g',s:'j',p:5,cost:5},
  giant:{n:'Giant Machete',c:'g',s:'j',p:6,cost:3,once:1},
  captain:{n:'Captain',c:'b',s:'w',p:3,cost:2},
  photographer:{n:'Photographer',c:'y',s:'v',p:2,cost:2},
  journalist:{n:'Journalist',c:'y',s:'v',p:3,cost:3},
  chest:{n:'Treasure Chest',c:'y',s:'v',p:4,cost:3,once:1},
  millionaire:{n:'Millionaire',c:'y',s:'v',p:4,cost:5},
  jack:{n:'Jack of All Trades',c:'x',s:'*',p:1,cost:2},
  adventurer:{n:'Adventurer',c:'x',s:'*',p:2,cost:4},
  plane:{n:'Prop Plane',c:'x',s:'*',p:4,cost:4,once:1},
  transmitter:{n:'Transmitter',c:'p',cost:4,once:1,txt:'Take any card from the market or reserve for free.',face:'Take any market or reserve card for free.'},
  cartographer:{n:'Cartographer',c:'p',cost:4,txt:'Draw 2 cards.'},
  scientist:{n:'Scientist',c:'p',cost:4,txt:'Draw 1 card. You may remove 1 card in hand from the game.',face:'Draw 1 card. You may remove 1 card from the game.'},
  compass:{n:'Compass',c:'p',cost:2,once:1,txt:'Draw 3 cards.'},
  travellog:{n:'Travel Log',c:'p',cost:3,once:1,txt:'Draw 2 cards. You may remove up to 2 cards in hand from the game.',face:'Draw 2 cards. You may remove up to 2 from the game.'},
  native:{n:'Native',c:'p',cost:5,txt:'Move to an adjacent space, ignoring its requirement. Can tear down a blockade.',face:'Move 1 space, ignoring its cost. Can tear down a blockade.'},
};
const MARKET0=['scout','trailblazer','jack','photographer','chest','transmitter'];
const RESERVE0=['pioneer','giant','captain','journalist','millionaire','adventurer','plane','cartographer','scientist','compass','travellog','native'];
const SYMNAME={j:'machete',w:'paddle',v:'coin'};
const SYMCOL={j:'#3f9a5c',w:'#3a8ad0',v:'#e7b54d',r:'#a3a8a4'};
const COLORS=[{id:'crimson',hex:'#e5484d',name:'Crimson'},{id:'ivory',hex:'#efe9dc',name:'Ivory'},{id:'violet',hex:'#9d7df7',name:'Violet'},{id:'orange',hex:'#ff9636',name:'Orange'}]; // one explorer figure per colour
/* Official base-game blockades are numbered 1–6: jungle, village, rubble, water, jungle, rubble.
   They are placed along the route in number order; the number also breaks ties. */
const BLOCKADES=[{n:1,k:'j',v:1},{n:2,k:'v',v:1},{n:3,k:'r',v:1},{n:4,k:'w',v:1},{n:5,k:'j',v:2},{n:6,k:'r',v:2}];

/* =========================================================
   TERRAIN BOARDS — base game letters. Terrain counts per board match the published
   tile catalogue (A/B start boards, C–N double-sided terrain boards). Space-by-space
   placement is reconstructed; see Rules.
   rows top→bottom (4,5,6,7,6,5,4): jN jungle · wN water · vN village · rN rubble · cN base camp · mm mountain · ss start
   ========================================================= */
const BOARDS={
 A:['j1 j1 v1 j1','j1 w1 j1 j2 j1','j1 w1 mm j1 v1 j1','v1 j1 w1 j1 j1 c1 j1','j1 j1 j1 mm v1 j1','j1 j1 v1 j1 j1','ss ss ss ss'],
 B:['j1 w1 c1 w1','j1 j1 v1 mm j1','j1 v1 j1 j1 j1 j1','w1 j1 v1 j1 v1 j1 j1','j1 j1 w1 j1 j1 j1','j1 j1 j1 j1 j1','s4 s3 s2 s1'],
 C:['j1 j1 r1 r1','j1 v1 r1 w1 w1','w1 w1 v1 v1 r1 w1','w1 v1 r1 mm w1 r1 r1','v1 r1 w1 w1 v1 v1','v1 r1 j1 v1 w1','j1 j1 w1 w1'],
 D:['j1 j1 w1 j1','j2 j1 w1 j1 mm','j1 mm w2 w1 j1 j1','j1 j1 w1 w3 w1 j2 j1','v1 j1 w1 w1 mm j1','v2 j1 j1 w2 j1','mm w1 v1 j1'],
 E:['j1 j1 r1 j1','j1 mm r2 mm j1','w1 j2 r1 j1 v1 j1','w1 mm r1 c1 r1 mm j1','w1 j1 r2 j1 v2 j1','w1 j2 r1 mm v1','j1 r1 j1 v1'],
 F:['w1 w1 j1 j1','w2 r1 r1 j1 j2','w1 r1 mm c1 j1 j1','w1 r2 mm v1 mm j1 w1','j1 r1 r1 v2 mm w1','j1 j2 r2 c2 w1','j1 v1 r1 j1'],
 G:['j1 v1 v1 j1','j1 v2 v1 v1 j1','j2 v1 mm mm v2 j1','j1 v1 v3 c1 v1 j1 j1','j1 r1 mm v1 v2 j1','j1 j2 mm r2 j1','j1 j1 v1 j1'],
 H:['v1 v1 w1 j1','v2 v1 w1 w1 j1','v1 v3 v1 w2 j1 j1','j1 v1 v2 mm w1 w1 j2','j1 v1 v1 v4 w1 j1','j1 j2 v1 w2 w1','j1 v1 j1 w1'],
 I:['j1 j1 j1 j1','v1 j1 mm j1 j1','v1 v2 j1 mm j2 j1','v1 v2 j1 j2 c2 mm mm','v2 r3 mm mm j2 j1','w2 w1 w1 j1 j1','w2 w2 w1 j1'],
 J:['r1 r1 v1 v1','w1 r2 r1 v2 v1','w1 w1 mm r1 v1 j1','w2 w1 r3 c1 r1 v1 j1','w1 w1 r1 mm v3 j1','w1 w1 r1 v1 j2','j1 j1 v1 v1'],
 K:['c1 j2 j2 j1','j1 j1 w3 j1 j2','j1 j2 j1 j3 j1 j2','j2 j1 j3 j1 j3 j1 j2','j2 j1 j3 j1 j2 j1','j2 j1 v4 j1 j1','j1 j2 j2 c1'],
 L:['j1 j1 j1 mm','j2 c1 j1 j1 j1','j1 j1 j2 mm j1 w1','c2 j1 j1 j1 j3 w1 j1','j1 mm j1 v1 j1 w1','j1 j2 j1 c1 j1','j1 v2 j1 j1'],
 M:['j1 mm mm j1','j1 j2 mm j1 j1','mm j1 r1 j2 mm j1','w1 j1 mm c1 j1 j1 mm','w1 mm j1 r2 j1 j1','w1 j1 v1 mm j2','w1 j1 r1 v1'],
 N:['j1 j1 j1 j1','v1 j1 j2 j1 w1','v1 v2 j1 w1 w1 w1','w1 w1 v3 v4 v2 v2 v1','w1 w1 w1 j1 v2 v1','j1 j1 j2 j1 j1','j1 j1 j1 j1'],
};
function parseTok(t){
  if(t==='mm')return{type:'m',val:0};if(t[0]==='s')return{type:'s',val:0,num:+t[1]||0}; // s1–s4: numbered start spaces
  if(t[0]==='g')return{type:'g',sym:t[1],val:1};
  return{type:t[0],val:+t[1]};
}
function parseTpl(rows){
  const cells=[];
  rows.forEach((row,i)=>{const r=i-3,toks=row.trim().split(/\s+/),qmin=Math.max(-3,-r-3),qmax=Math.min(3,-r+3);
    if(toks.length!==qmax-qmin+1)throw new Error('bad tile row '+row);
    toks.forEach((t,j)=>cells.push({q:qmin+j,r,d:parseTok(t)}));});
  return cells;
}
const TPL={};for(const k in BOARDS)TPL[k]=parseTpl(BOARDS[k]);

/* =========================================================
   GEOMETRY / MAP
   ========================================================= */
const SQ3=Math.sqrt(3),R=34;
const DIRS=[[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]];
const key=(q,r)=>q+','+r;
const rot=(q,r,k)=>{for(let i=0;i<k;i++){const t=q;q=-r;r=t+r;}return[q,r];};
const pxOf=(q,r)=>[R*SQ3*(q+r/2),R*1.5*r];
function mulberry32(a){return function(){a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function shuffle(a,rnd=Math.random){for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
const hash=(x,y)=>{let h=Math.imul(x|0,374761393)+Math.imul(y|0,668265263);h=Math.imul(h^(h>>>13),1274126177);return((h^(h>>>16))>>>0)/4294967296;};

/* =========================================================
   COURSES — fixed routes (no random generation).
   p: the boards in route order as [letter, q, r, rotation]; the first is start board A or B.
      (q,r) is where the board's central space goes; rotation is in 60° steps.
   e: [q,r] the middle finishing space of the El Dorado tile, next to the last board.
   s: El Dorado side, 'j' jungle or 'w' water.
   Blockades are dealt at random onto the connections when a game starts (rulebook).
   ========================================================= */
const COURSES=[
  // Positions and rotations taken from Ravensburger's setup sheet (first game); El Dorado water side on K's top-right corner.
  {id:'first',name:'First Expedition',src:'Rulebook route for your first game',diff:'Easy',
   p:[['B',0,0,2],['C',7,-3,5],['N',11,0,2],['I',14,4,2],['K',21,-1,0]],e:[25,-5],s:'w'},
];
const courseById=id=>COURSES.find(c=>c.id===id)||null;
function buildCourse(C,seed){
  const hexes=new Map(),tiles=[];
  C.p.forEach(([name,cq,cr,k],ti)=>{
    const tpl=TPL[name];if(!tpl)throw new Error('Unknown board '+name);
    if((ti===0)!==(name==='A'||name==='B'))throw new Error('A route starts with board A or B, and only there.');
    let sx=0,sy=0;
    for(const cell of tpl){const[lq,lr]=rot(cell.q,cell.r,k);const q=cq+lq,r=cr+lr,K=key(q,r);
      if(hexes.has(K))throw new Error('Boards '+tiles[hexes.get(K).tile].name+' and '+name+' overlap.');
      const[x,y]=pxOf(q,r);hexes.set(K,{...cell.d,q,r,k:K,tile:ti,x,y});sx+=x;sy+=y;}
    tiles.push({c:[cq,cr],name,k,x:sx/tpl.length,y:sy/tpl.length});
  });
  const nT=tiles.length;
  // El Dorado tile: the given space plus its two neighbours along the last board's edge
  const touch=(q,r)=>!hexes.has(key(q,r))&&DIRS.some(([a,b])=>{const n=hexes.get(key(q+a,r+b));return n&&n.tile===nT-1&&n.type!=='m';});
  const[eq,er]=C.e;if(!touch(eq,er))throw new Error('El Dorado must sit against the last board.');
  let side=null;
  for(let d=0;d<3&&!side;d++){const a=[eq+DIRS[d][0],er+DIRS[d][1]],b=[eq-DIRS[d][0],er-DIRS[d][1]];if(touch(...a)&&touch(...b))side=[a,b];}
  if(!side){const fr=DIRS.map(([a,b])=>[eq+a,er+b]).filter(c=>touch(...c));if(fr.length<2)throw new Error('No room for El Dorado there.');side=fr.slice(0,2);}
  for(const[q,r]of[[eq,er],...side]){const K=key(q,r),[x,y]=pxOf(q,r);hexes.set(K,{type:'g',sym:C.s,val:1,q,r,k:K,tile:nT,x,y});}
  // connections between consecutive boards (only these carry blockades; other touching boards are open)
  const conns=[];const edgeConn=new Map();
  for(let i=0;i<nT-1;i++)conns.push({a:i,b:i+1,edges:[]});
  for(const h of hexes.values())for(const[dq,dr]of DIRS){const n=hexes.get(key(h.q+dq,h.r+dr));
    if(n&&n.tile===h.tile+1&&n.tile<nT){conns[h.tile].edges.push([h.k,n.k]);edgeConn.set(h.k+'|'+n.k,h.tile);edgeConn.set(n.k+'|'+h.k,h.tile);}}
  conns.forEach((c,i)=>{if(c.edges.filter(([a,b])=>hexes.get(a).type!=='m'&&hexes.get(b).type!=='m').length<2)throw new Error('Boards '+tiles[i].name+' and '+tiles[i+1].name+' are not properly connected.');});
  const starts=[...hexes.values()].filter(h=>h.type==='s');
  const goals=[...hexes.values()].filter(h=>h.type==='g');
  const seen=new Set(starts.map(s=>s.k)),q=[...starts];let found=false;
  while(q.length){const h=q.shift();if(h.type==='g'){found=true;break;}
    for(const[dq,dr]of DIRS){const n=hexes.get(key(h.q+dq,h.r+dr));if(!n||seen.has(n.k)||n.type==='m'||n.type==='s')continue;seen.add(n.k);q.push(n);}}
  if(!found)throw new Error('There is no path from the start to El Dorado.');
  // start spaces numbered along their edge
  const sc=starts.reduce((a,h)=>[a[0]+h.x/starts.length,a[1]+h.y/starts.length],[0,0]);
  const ang=Math.atan2(tiles[1].y-tiles[0].y,tiles[1].x-tiles[0].x)+Math.PI/2;
  const proj=h=>(h.x-sc[0])*Math.cos(ang)+(h.y-sc[1])*Math.sin(ang);
  if(starts.every(s=>s.num))starts.sort((a,b)=>a.num-b.num);else{starts.sort((a,b)=>proj(a)-proj(b));starts.forEach((s,i)=>s.num=i+1);}
  // a random blockade on each connection
  const deal=shuffle(BLOCKADES.slice(),mulberry32(seed^0x2c1b3c6d));
  if(conns.length>deal.length)throw new Error('Too many connections for 6 blockades.');
  const blockDefs=conns.map((c,i)=>({...deal[i],conn:i}));
  const gc=goals.reduce((a,h)=>[a[0]+h.x/3,a[1]+h.y/3],[0,0]);
  const last=tiles[nT-1];let dx=gc[0]-last.x,dy=gc[1]-last.y;const dl=Math.hypot(dx,dy)||1;dx/=dl;dy/=dl;
  const city={x:gc[0]+dx*R*2.5,y:gc[1]+dy*R*2.5,dx,dy};
  tiles.push({c:[eq,er],name:'El Dorado',k:0,end:true,x:gc[0],y:gc[1]});
  let minX=1e9,minY=1e9,maxX=-1e9,maxY=-1e9;
  for(const h of hexes.values()){minX=Math.min(minX,h.x-R);maxX=Math.max(maxX,h.x+R);minY=Math.min(minY,h.y-R);maxY=Math.max(maxY,h.y+R);}
  minX=Math.min(minX,city.x-R*2.6);maxX=Math.max(maxX,city.x+R*2.6);minY=Math.min(minY,city.y-R*2.6);maxY=Math.max(maxY,city.y+R*2.6);
  const pad=R*.6;minX-=pad;minY-=pad;maxX+=pad;maxY+=pad;
  return{hexes,tiles,conns,edgeConn,starts:starts.map(s=>s.k),goals:goals.map(g=>g.k),blockDefs,city,endSym:C.s,minX,minY,w:maxX-minX,h:maxY-minY,route:C.p.map(x=>x[0]),name:C.name,course:C.id};
}

/* =========================================================
   RULES ENGINE — pure game logic shared by the browser and the server.
   Works on the module-level S (game state) and MAP (board built from S.course + S.seed).
   Nothing in here touches the page.
   ========================================================= */
let S=null,MAP=null;
const hexAt=k=>MAP.hexes.get(k);
const typeOf=id=>S.cards[id];
const def=id=>CT[S.cards[id]];
const plural=(n,w)=>n+' '+w+(n===1?'':'s');
const fmt=n=>(n%1?(Math.floor(n)?Math.floor(n)+'½':'½'):String(n));
function rm(arr,id){const i=arr.indexOf(id);if(i>=0)arr.splice(i,1);}
function playerDone(p){return p.pieces.every(k=>k==='done');}
function isActive(p){return !playerDone(p)&&!p.resigned;}

function mapFor(st){return buildCourse(st.course,st.seed);}
function newGame(o){
  const course=o.course||COURSES[0];
  MAP=buildCourse(course,o.seed);
  let nid=1;const cards={};const mk=t=>{const id='c'+(nid++);cards[id]=t;return id;};
  const players=o.players.map(p=>{
    const deck=[];for(let i=0;i<3;i++)deck.push(mk('explorer'));for(let i=0;i<4;i++)deck.push(mk('traveler'));deck.push(mk('sailor'));
    return{name:p.name,color:p.color,pieces:[],deck:shuffle(deck),hand:[],discard:[],play:[],blocks:[],fin:0,resigned:0};
  });
  const st=MAP.starts;
  if(players.length===2){players[0].pieces=[st[0],st[2]];players[1].pieces=[st[1],st[3]];}
  else players.forEach((p,i)=>p.pieces=[st[i]]);
  S={v:4,seed:o.seed,course,players,cards,nid,market:MARKET0.map(t=>({t,n:3})),reserve:RESERVE0.map(t=>({t,n:3})),
     blockades:MAP.blockDefs.map(d=>({...d,owner:null})),cur:0,start:0,round:1,endTriggered:false,over:false,winners:null,places:null,
     fullRace:o.fullRace!==false,turn:{bought:false,active:null,pending:null},trash:[],log:[],privacy:!!o.privacy,resigns:0};
  players.forEach(p=>drawCards(p,4));
  log(null,'The expedition sets out: '+players.map(p=>p.name).join(', ')+'. Course: '+MAP.name+' ('+MAP.route.join(' · ')+' · El Dorado).');
  return S;
}
function newCard(t){const id='c'+(S.nid++);S.cards[id]=t;return id;}
function drawCards(p,n){const got=[];for(let i=0;i<n;i++){if(!p.deck.length){if(!p.discard.length)break;p.deck=shuffle(p.discard);p.discard=[];}const c=p.deck.pop();p.hand.push(c);got.push(c);}return got;}
function log(pi,t){S.log.push({p:pi,t});if(S.log.length>200)S.log.shift();}
function occupied(k,exPl,exPi){return S.players.some((p,pi)=>p.pieces.some((pk,i)=>pk===k&&!(pi===exPl&&i===exPi)));}
function blockAt(a,b){const c=MAP.edgeConn.get(a+'|'+b);if(c===undefined)return null;const bi=S.blockades.findIndex(x=>x.conn===c);if(bi<0||S.blockades[bi].owner!==null)return null;return bi;}
function neighbors(k){const nb=MAP._nb||(MAP._nb=new Map());let r=nb.get(k);if(!r){const h=hexAt(k);r=DIRS.map(([dq,dr])=>key(h.q+dq,h.r+dr)).filter(n=>MAP.hexes.has(n));nb.set(k,r);}return r;} // cached per map
function coinVal(id){const d=def(id);if(d.c==='y'||d.c==='x')return d.p;return .5;}
function blkLabel(B){return B.k==='r'?'discard '+plural(B.v,'card'):plural(B.v,SYMNAME[B.k]);}

/* ---------- reachability ---------- */
function reach(pl,pi,syms,budget){
  const out=new Map();const from=S.players[pl].pieces[pi];if(!from||from==='done')return out;
  for(const sym of syms){
    const dist=new Map([[from,0]]),prev=new Map(),pq=[[0,from]];
    while(pq.length){
      let bi=0;for(let i=1;i<pq.length;i++)if(pq[i][0]<pq[bi][0])bi=i;
      const[d,u]=pq[bi];pq[bi]=pq[pq.length-1];pq.pop();if(d>dist.get(u))continue;
      if(u!==from&&hexAt(u).type==='g')continue;
      for(const n of neighbors(u)){
        const h=hexAt(n);
        if(!(h.type===sym||(h.type==='g'&&h.sym===sym)))continue;
        if(occupied(n,pl,pi))continue;
        let c=h.val;const b=blockAt(u,n);
        if(b!==null){if(S.blockades[b].k!==sym)continue;c+=S.blockades[b].v;}
        const nd=d+c;if(nd>budget)continue;
        if(!dist.has(n)||nd<dist.get(n)){dist.set(n,nd);prev.set(n,u);pq.push([nd,n]);}
      }
    }
    const pathTo=k=>{const p=[];let x=k;while(x!==from){p.unshift(x);x=prev.get(x);}return p;};
    for(const[k,d]of dist){if(k===from)continue;const o=out.get(k);if(!o||d<o.cost)out.set(k,{kind:'move',cost:d,sym,path:pathTo(k),pi});}
    for(const[k,d]of dist){
      if(hexAt(k).type==='g')continue;
      for(const n of neighbors(k)){const b=blockAt(k,n);if(b===null)continue;const B=S.blockades[b];
        if(B.k!==sym||d+B.v>budget)continue;const K='B'+b;const o=out.get(K);
        if(!o||d+B.v<o.cost)out.set(K,{kind:'bl',bl:b,cost:d+B.v,sym,path:k===from?[]:pathTo(k),pi});}
    }
  }
  return out;
}
function nativeTargets(pl,pi){
  const T=new Map();const pk=S.players[pl].pieces[pi];if(!pk||pk==='done')return T;
  for(const n of neighbors(pk)){const h=hexAt(n);if(h.type==='m'||h.type==='s'||occupied(n))continue;T.set(n,{kind:'native',path:[n],cost:0,pi,bl:blockAt(pk,n)});}
  for(const n of neighbors(pk)){const b=blockAt(pk,n);if(b!==null&&!T.has('B'+b))T.set('B'+b,{kind:'nativebl',bl:b,path:[],cost:0,pi});}
  return T;
}
/* spaces/blockades entered by discarding (rubble, grey blockade) or removing cards (base camp) */
function payTargets(pl,pi){
  const T=new Map();const P=S.players[pl];const pk=P.pieces[pi];if(!pk||pk==='done')return T;
  const hn=P.hand.length;
  for(const n of neighbors(pk)){const h=hexAt(n);
    if((h.type==='r'||h.type==='c')&&!occupied(n)&&blockAt(pk,n)===null&&hn>=h.val)T.set(n,{kind:h.type==='r'?'rubble':'camp',need:h.val,path:[n],pi});
    const b=blockAt(pk,n);if(b!==null&&S.blockades[b].k==='r'&&hn>=S.blockades[b].v&&!T.has('B'+b))T.set('B'+b,{kind:'blr',bl:b,need:S.blockades[b].v,pi});
  }
  return T;
}

/* =========================================================
   APPLY AN ACTION. Returns {ok, err?, ev:[events], reveal}
   reveal = new information came out (cards drawn), so undo stops here.
   Actions (acting player = S.cur):
     {t:'move', card, pi, to}        movement card (or a card with leftover strength)
     {t:'native', card, pi, to}
     {t:'pay', pi, to, cards}        rubble / base camp / grey blockade
     {t:'action', card}              Cartographer, Compass, Scientist, Travel Log
     {t:'trash', cards}              finish Scientist / Travel Log
     {t:'transmit', card, src, idx}
     {t:'buy', src, idx, cards}
     {t:'end', keep}                 end the turn, keeping these hand cards
   ========================================================= */
function applyAction(seat,a){
  const fail=err=>({ok:false,err,ev:[]});
  if(!S||S.over)return fail('The game is over.');
  if(seat!==S.cur)return fail('It is not your turn.');
  if(!a||typeof a!=='object')return fail('Bad action.');
  const P=S.players[seat],T=S.turn,ev=[];let reveal=false;
  const inHand=id=>typeof id==='string'&&P.hand.includes(id);
  const distinctHand=ids=>Array.isArray(ids)&&new Set(ids).size===ids.length&&ids.every(inHand);
  const pieceOk=pi=>Number.isInteger(pi)&&pi>=0&&pi<P.pieces.length&&P.pieces[pi]!=='done';
  if(T.pending&&a.t!=='trash')return fail('Choose which cards to remove first.');
  const takeBlock=b=>{const B=S.blockades[b];if(B.owner!==null)return;B.owner=seat;P.blocks.push(b);log(seat,'tears down blockade #'+B.n+' and keeps it.');ev.push({e:'block',pl:seat,n:B.n});};
  const arrive=pi=>{if(P.pieces[pi]!=='done')return;log(seat,'reaches El Dorado!');ev.push({e:'arrive',pl:seat,pi});
    if(playerDone(P)&&!P.fin){P.fin=S.round;checkEnd();}};
  switch(a.t){
    case 'move':{
      const act=T.active&&T.active.id===a.card?T.active:null;
      if(!act&&!inHand(a.card))return fail('That card is not in your hand.');
      const d=def(a.card);if(!d||d.c==='p')return fail('That card cannot move.');
      const pi=act?act.pi:a.pi;if(!pieceOk(pi))return fail('Choose one of your explorers.');
      const syms=act?[act.sym]:(d.s==='*'?['j','w','v']:[d.s]);const budget=act?act.left:d.p;
      const tg=reach(seat,pi,syms,budget).get(a.to);if(!tg)return fail('That space is out of reach.');
      if(!act){T.active=null;rm(P.hand,a.card);P.play.push(a.card);}
      const from=P.pieces[pi];let pos=from;const path=[from];
      for(const st of tg.path){const b=blockAt(pos,st);if(b!==null)takeBlock(b);pos=st;path.push(st);}
      if(tg.kind==='bl')takeBlock(tg.bl);
      const done=hexAt(pos).type==='g';P.pieces[pi]=done?'done':pos;
      const left=budget-tg.cost;T.active=(left>0&&!done)?{id:a.card,pi,sym:tg.sym,left}:null;
      if(tg.path.length){log(seat,'moves '+plural(tg.path.length,'space')+' with '+d.n+(d.s==='*'?' (as '+SYMNAME[tg.sym]+')':'')+'.');ev.push({e:'move',pl:seat,pi,path});}
      arrive(pi);break;
    }
    case 'native':{
      if(!inHand(a.card)||typeOf(a.card)!=='native')return fail('You need the Native.');
      if(!pieceOk(a.pi))return fail('Choose one of your explorers.');
      const tg=nativeTargets(seat,a.pi).get(a.to);if(!tg)return fail('The Native can only reach an adjacent free space.');
      T.active=null;rm(P.hand,a.card);P.play.push(a.card);
      if(tg.bl!=null)takeBlock(tg.bl);
      if(tg.kind==='native'){const from=P.pieces[a.pi];const n=tg.path[0];P.pieces[a.pi]=hexAt(n).type==='g'?'done':n;
        log(seat,'plays the Native and moves to an adjacent space.');ev.push({e:'move',pl:seat,pi:a.pi,path:[from,n]});arrive(a.pi);}
      else log(seat,'plays the Native to tear down a blockade.');
      break;
    }
    case 'pay':{
      if(!pieceOk(a.pi))return fail('Choose one of your explorers.');
      const tg=payTargets(seat,a.pi).get(a.to);if(!tg)return fail('You cannot enter there.');
      if(!distinctHand(a.cards)||a.cards.length!==tg.need)return fail('Choose exactly '+plural(tg.need,'card')+'.');
      T.active=null;const trash=tg.kind==='camp';
      for(const id of a.cards){rm(P.hand,id);if(trash)S.trash.push(id);else P.play.push(id);}
      if(tg.kind==='blr'){takeBlock(tg.bl);log(seat,'discards '+plural(tg.need,'card')+' to clear the blockade.');}
      else{const from=P.pieces[a.pi];const n=tg.path[0];P.pieces[a.pi]=n;
        log(seat,trash?'removes '+plural(tg.need,'card')+' from the game to enter a base camp.':'discards '+plural(tg.need,'card')+' to cross rubble.');
        ev.push({e:'move',pl:seat,pi:a.pi,path:[from,n]});}
      break;
    }
    case 'action':{
      const t=inHand(a.card)&&typeOf(a.card);
      const n={cartographer:2,compass:3,scientist:1,travellog:2}[t];if(!n)return fail('That card has no draw effect.');
      T.active=null;rm(P.hand,a.card);if(CT[t].once)S.trash.push(a.card);else P.play.push(a.card);
      const got=drawCards(P,n);reveal=true;
      log(seat,'plays '+CT[t].n+' and draws '+plural(got.length,'card')+'.');ev.push({e:'draw',pl:seat,n:got.length});
      if(t==='scientist'||t==='travellog')T.pending={max:t==='scientist'?1:2};
      break;
    }
    case 'trash':{
      if(!T.pending)return fail('Nothing to remove.');
      if(!distinctHand(a.cards)||a.cards.length>T.pending.max)return fail('Choose up to '+plural(T.pending.max,'card')+'.');
      if(a.cards.length){for(const id of a.cards){rm(P.hand,id);S.trash.push(id);}log(seat,'removes '+a.cards.map(i=>def(i).n).join(', ')+' from the game.');}
      T.pending=null;break;
    }
    case 'transmit':{
      if(!inHand(a.card)||typeOf(a.card)!=='transmitter')return fail('You need the Transmitter.');
      const stack=a.src==='m'?S.market[a.idx]:a.src==='r'?S.reserve[a.idx]:null;if(!stack||stack.n<=0)return fail('That card is sold out.');
      T.active=null;rm(P.hand,a.card);S.trash.push(a.card);
      stack.n--;P.discard.push(newCard(stack.t));
      log(seat,'uses the Transmitter to take '+CT[stack.t].n+'.');ev.push({e:'gain',pl:seat,t:stack.t,src:a.src,idx:a.idx});
      break;
    }
    case 'buy':{
      if(T.bought)return fail('You can buy only one card per turn.');
      const open=S.market.some(s=>s.n===0);
      let stack=a.src==='m'?S.market[a.idx]:a.src==='r'?S.reserve[a.idx]:null;
      if(!stack||stack.n<=0)return fail('That card is sold out.');
      if(a.src==='r'&&!open)return fail('The reserve opens once a market slot is empty.');
      if(!distinctHand(a.cards))return fail('Pay with cards from your hand.');
      const total=a.cards.reduce((s,id)=>s+coinVal(id),0),cost=CT[stack.t].cost;
      if(total<cost)return fail('Not enough coins.');
      T.active=null;
      for(const id of a.cards){rm(P.hand,id);const d=def(id);if(d.once&&(d.c==='y'||d.c==='x'))S.trash.push(id);else P.play.push(id);}
      const t=stack.t;
      if(a.src==='r'){const slot=S.market.findIndex(s=>s.n===0);S.market[slot]={t,n:stack.n};S.reserve.splice(a.idx,1);stack=S.market[slot];}
      stack.n--;P.discard.push(newCard(t));T.bought=true;
      log(seat,'buys '+CT[t].n+' for '+fmt(total)+' coin'+(total===1?'':'s')+'.');ev.push({e:'gain',pl:seat,t,src:a.src,idx:a.idx});
      break;
    }
    case 'end':{
      const keep=Array.isArray(a.keep)?a.keep:[];
      if(!keep.every(inHand)||new Set(keep).size!==keep.length)return fail('Bad cards to keep.');
      const toDisc=P.hand.filter(id=>!keep.includes(id));
      for(const id of toDisc){rm(P.hand,id);P.discard.push(id);}
      P.discard.push(...P.play);P.play=[];
      drawCards(P,Math.max(0,4-P.hand.length));reveal=true;
      log(seat,'ends the turn'+(toDisc.length?', discarding '+toDisc.length:'')+(keep.length?(toDisc.length?' and':'')+' keeping '+keep.length:'')+'.');
      S.turn={bought:false,active:null,pending:null};
      advance();ev.push({e:'turn',pl:S.cur});
      break;
    }
    default:return fail('Unknown action.');
  }
  if(S.over)ev.push({e:'over'});
  return{ok:true,ev,reveal};
}
/* who still races */
function checkEnd(){
  const n=S.players.length;
  if(S.fullRace){if(S.players.filter(isActive).length<=1&&!S.endTriggered){S.endTriggered=true;log(null,'Only one expedition is still racing. The round will be finished.');}}
  else if(S.players.some(playerDone)&&!S.endTriggered){S.endTriggered=true;log(null,'The final round has begun.');}
  if(S.players.every(p=>!isActive(p))&&S.fullRace)S.endTriggered=true;
  return n;
}
function advance(){
  const n=S.players.length;let i=S.cur;
  for(let step=0;step<n*2+2;step++){
    i=(i+1)%n;
    if(i===S.start){if(S.endTriggered){endGame();return;}S.round++;}
    const p=S.players[i];
    if(S.fullRace?isActive(p):!p.resigned){S.cur=i;return;}
  }
  endGame();
}
/* A player leaves a game for good (online): placed below everyone still racing. */
function resign(seat){
  if(!S||S.over)return{ok:false,ev:[]};
  const P=S.players[seat];if(P.resigned||playerDone(P))return{ok:false,ev:[]};
  P.resigned=++S.resigns;log(seat,'leaves the expedition.');
  const ev=[{e:'resign',pl:seat}];
  const others=S.players.filter((p,i)=>i!==seat&&!p.resigned);
  if(others.length<=1||S.players.filter(isActive).length<=1){ // nobody left to race: finish now
    if(S.players.filter(isActive).length===0||others.length<=1){endGame();ev.push({e:'over'});return{ok:true,ev};}
  }
  checkEnd();
  if(seat===S.cur){S.turn={bought:false,active:null,pending:null};advance();ev.push({e:'turn',pl:S.cur});}
  if(S.over)ev.push({e:'over'});
  return{ok:true,ev};
}
function progress(p){ // lower = closer: sum of shortest step counts from each explorer to a finishing space
  let tot=0;
  for(const k of p.pieces){if(k==='done')continue;
    const seen=new Set([k]);let q=[k],d=0,found=false;
    while(q.length&&!found){d++;const nq=[];for(const u of q)for(const n of neighbors(u)){if(seen.has(n))continue;const h=hexAt(n);if(h.type==='m')continue;if(h.type==='g'){found=true;break;}seen.add(n);nq.push(n);}q=nq;if(d>200)break;}
    tot+=found?d:999;}
  return tot;
}
function endGame(){
  S.over=true;
  const mb=p=>Math.max(0,...p.blocks.map(b=>S.blockades[b].n));
  const keyOf=(p)=>playerDone(p)?[0,p.fin,-p.blocks.length,-mb(p)]:p.resigned?[2,-p.resigned,0,0]:[1,progress(p),-p.blocks.length,-mb(p)];
  const idx=S.players.map((p,i)=>({i,k:keyOf(p)}));
  const cmp=(a,b)=>{for(let j=0;j<4;j++)if(a.k[j]!==b.k[j])return a.k[j]-b.k[j];return 0;};
  idx.sort(cmp);
  const places=new Array(S.players.length);
  idx.forEach((x,j)=>{places[x.i]=j>0&&cmp(x,idx[j-1])===0?places[idx[j-1].i]:j+1;});
  S.places=places;S.winners=places.map((p,i)=>p===1?i:-1).filter(i=>i>=0);
  log(null,S.winners.map(i=>S.players[i].name).join(' & ')+' win'+(S.winners.length>1?'':'s')+' the race to El Dorado.');
}
/* ---------- multiplayer Elo from a finishing order ---------- */
function eloDeltas(ratings,places,games){
  const n=ratings.length;const out=new Array(n).fill(0);if(n<2)return out;
  for(let i=0;i<n;i++){const K=(games[i]<10?48:32)/(n-1);
    for(let j=0;j<n;j++){if(i===j)continue;
      const E=1/(1+Math.pow(10,(ratings[j]-ratings[i])/400));
      const Sc=places[i]<places[j]?1:places[i]===places[j]?.5:0;
      out[i]+=K*(Sc-E);}}
  return out.map(x=>Math.round(x*10)/10);
}
/* ---------- what one player may see ---------- */
function redact(state,seat){
  const R=JSON.parse(JSON.stringify(state));const vis=new Set();
  R.players.forEach((p,i)=>{
    if(i===seat){p.deck=p.deck.slice().sort((a,b)=>(state.cards[a]<state.cards[b]?-1:state.cards[a]>state.cards[b]?1:0));p.hand.forEach(id=>vis.add(id));p.deck.forEach(id=>vis.add(id));}
    else{p.hand=p.hand.map((_,k)=>'h'+i+'_'+k);p.deck=p.deck.map((_,k)=>'d'+i+'_'+k);}
    p.play.forEach(id=>vis.add(id));p.discard.forEach(id=>vis.add(id));
  });
  R.trash.forEach(id=>vis.add(id));
  if(R.turn&&R.turn.active)vis.add(R.turn.active.id);
  const cards={};for(const id of vis)if(state.cards[id])cards[id]=state.cards[id];R.cards=cards;
  return R;
}

/* =========================================================
   BOT — plays through the same applyAction as a human. Runs anywhere the engine runs
   (browser for local games; Node for training). Never sees hidden information it
   shouldn't: its own draw pile is re-shuffled before every look-ahead, and opponents
   are judged only by public facts (position, blockades, the cards they own).

   Decision = greedy over "afterstates": list every legal atomic action, apply each to
   a copy of the state, score the result with value(), take the best. value() is either
   the hand-written heuristic or a small neural net trained by self-play (TD-Gammon style).
   ========================================================= */
const BOT_TYPES=Object.keys(CT);
/* ---- static distances to El Dorado, per map (cost = sum of space values along the way) ---- */
function botDist(){
  if(MAP._bd)return MAP._bd;
  const cost=new Map(),steps=new Map(),next=new Map(),pq=[];
  for(const g of MAP.goals){cost.set(g,0);steps.set(g,0);pq.push([0,g]);}
  while(pq.length){let bi=0;for(let i=1;i<pq.length;i++)if(pq[i][0]<pq[bi][0])bi=i;const[d,u]=pq.splice(bi,1)[0];if(d>cost.get(u))continue;
    const hu=hexAt(u);if(hu.type==='s')continue;           // start spaces can't be entered, so nothing routes through them
    const enter=hu.type==='g'?1:hu.val;                     // cost of stepping onto u
    for(const n of neighbors(u)){const h=hexAt(n);if(h.type==='m'||h.type==='g')continue;
      const nd=d+enter;if(!cost.has(n)||nd<cost.get(n)){cost.set(n,nd);steps.set(n,steps.get(u)+1);next.set(n,u);pq.push([nd,n]);}}}
  const mix=new Map(); // terrain still ahead on the cheapest route, per type (tells the bot what to buy)
  for(const k of cost.keys()){const m={j:0,w:0,v:0,r:0,c:0};let x=next.get(k),guard=0;
    while(x&&guard++<200){const h=hexAt(x);if(h.type==='g'){m[h.sym]+=1;break;}if(m[h.type]!=null)m[h.type]+=h.val;x=next.get(x);}mix.set(k,m);}
  MAP._bd={cost,steps,mix};return MAP._bd;
}
const botCost=k=>k==='done'?0:(botDist().cost.get(k)??60);
function botRemaining(pl){const p=S.players[pl];return p.pieces.reduce((a,k)=>a+botCost(k),0)/p.pieces.length;} // route cost still ahead
/* ---- legal atomic actions for the player to move (deduplicated by card type) ---- */
function botWorth(t){const d=CT[t];if(!d)return 0;if(d.c==='p')return t==='native'?3:t==='transmitter'?3.5:2.5;return d.p*(d.c==='x'?1.25:1)+(d.once?-.5:0);}
/* every distinct subset (by card types) of `ids` with exactly k cards */
function botCombos(ids,k){const out=[],seen=new Set(),cur=[];
  const rec=i=>{if(cur.length===k){const sig=cur.map(typeOf).sort().join();if(!seen.has(sig)){seen.add(sig);out.push(cur.slice());}return;}
    for(let j=i;j<ids.length;j++){cur.push(ids[j]);rec(j+1);cur.pop();}};rec(0);return out;}
function botActions(){
  const seat=S.cur,P=S.players[seat],T=S.turn,out=[];
  // Scientist / Travel Log: remove nothing, or any distinct choice of up to `max` cards
  if(T.pending){for(let k=0;k<=Math.min(T.pending.max,P.hand.length);k++)for(const c of botCombos(P.hand,k))out.push({t:'trash',cards:c});return out;}
  const seen=new Set(),hand=P.hand.filter(id=>{const t=typeOf(id);if(seen.has(t))return false;seen.add(t);return true;}); // one of each type
  P.pieces.forEach((pk,pi)=>{if(pk==='done')return;
    if(T.active&&T.active.pi===pi)for(const[k]of reach(seat,pi,[T.active.sym],T.active.left))out.push({t:'move',card:T.active.id,pi,to:k});
    for(const id of hand){const d=def(id),t=typeOf(id);
      if(t==='native'){for(const[k]of nativeTargets(seat,pi))out.push({t:'native',card:id,pi,to:k});continue;}
      if(d.c==='p')continue;
      for(const[k]of reach(seat,pi,d.s==='*'?['j','w','v']:[d.s],d.p))out.push({t:'move',card:id,pi,to:k});}
    // rubble / base camp / rubble blockade: every distinct choice of cards to give up
    for(const[k,tg]of payTargets(seat,pi))for(const c of botCombos(P.hand,tg.need))out.push({t:'pay',pi,to:k,cards:c});
  });
  for(const id of hand){const t=typeOf(id);if(['cartographer','compass','scientist','travellog'].includes(t))out.push({t:'action',card:id});}
  const open=S.market.some(s=>s.n===0);
  const tr=hand.find(id=>typeOf(id)==='transmitter');
  if(tr){S.market.forEach((s,i)=>{if(s.n>0)out.push({t:'transmit',card:tr,src:'m',idx:i});});S.reserve.forEach((s,i)=>{if(s.n>0)out.push({t:'transmit',card:tr,src:'r',idx:i});});}
  if(!T.bought){
    // every minimal way to pay (no card could be left out), distinct by card types
    const cash=P.hand.reduce((a,id)=>a+coinVal(id),0),pays=new Map();
    const payFor=cost=>{if(pays.has(cost))return pays.get(cost);const res=[];
      for(let k=1;k<=P.hand.length&&res.length<8;k++)for(const c of botCombos(P.hand,k)){const tot=c.reduce((a,id)=>a+coinVal(id),0);if(tot>=cost&&c.every(id=>tot-coinVal(id)<cost))res.push(c);}
      pays.set(cost,res);return res;};
    const tryStack=(src,s,i)=>{if(s.n<=0||CT[s.t].cost>cash)return;for(const cards of payFor(CT[s.t].cost))out.push({t:'buy',src,idx:i,cards});};
    S.market.forEach((s,i)=>tryStack('m',s,i));if(open)S.reserve.forEach((s,i)=>tryStack('r',s,i));
  }
  // end turn keeping any distinct choice of 0–3 cards
  for(let k=0;k<=Math.min(3,P.hand.length);k++)for(const c of botCombos(P.hand,k))out.push({t:'end',keep:c});
  return out;
}
/* ---- features: everything a player can see at a glance, from `me`'s point of view ----
   No history-based deductions. Hidden: my draw-pile ORDER, opponents' hands vs. draw piles
   (but all the cards they own and their discard piles are public). The map is encoded along
   the "steps to El Dorado" axis, so the same inputs work on any course. */
const BOT_BINS=16,BOT_BW=3,BOT_NT=BOT_TYPES.length;
const BOT_NF=16*9+14+BOT_NT*4+12+3*(BOT_NT*2+8)+BOT_NT*2+2+6*9+4;
function botCounts(ids){const c=new Float32Array(BOT_NT);for(const id of ids){const k=BOT_TYPES.indexOf(S.cards[id]);if(k>=0)c[k]++;}return c;}
function botFeatures(me){
  const f=new Float32Array(BOT_NF);let i=0;const put=(v)=>{f[i++]=v;},putArr=(a,sc)=>{for(const x of a)f[i++]=x*sc;};
  const P=S.players[me],endView=S._endView===me,myTurn=S.cur===me&&!S.over&&!endView,bd=botDist(),n=S.players.length;
  const stepsOf=k=>k==='done'?0:(bd.steps.get(k)??48);
  // 1. the map, binned by steps to El Dorado: width, terrain mix, difficulty, crowding, blockades
  const bins=Array.from({length:BOT_BINS},()=>new Float32Array(9));
  const occ=new Set();S.players.forEach(p=>p.pieces.forEach(k=>{if(k!=='done')occ.add(k);}));
  for(const[k,st]of bd.steps){const h=hexAt(k);if(h.type==='g'||h.type==='s')continue;const b=bins[Math.min(BOT_BINS-1,Math.floor(st/BOT_BW))];
    b[0]++;const t='jwvrc'.indexOf(h.type);if(t>=0)b[1+t]++;b[6]+=h.val;if(occ.has(k))b[7]++;}
  S.blockades.forEach(B=>{if(B.owner!==null)return;const e=MAP.conns[B.conn].edges[0];const st=Math.min(stepsOf(e[0]),stepsOf(e[1]));bins[Math.min(BOT_BINS-1,Math.floor(st/BOT_BW))][8]+=B.v;});
  for(const b of bins){const c=b[0]||1;put(b[0]/10);for(let t=1;t<=5;t++)put(b[t]/c);put(b[6]/c/3);put(b[7]/2);put(b[8]/2);}
  // 2. me: where I am and what's ahead
  const pieceCost=p=>p.pieces.reduce((a,k)=>a+botCost(k),0)/p.pieces.length,pieceSteps=p=>p.pieces.reduce((a,k)=>a+stepsOf(k),0)/p.pieces.length;
  const myCost=pieceCost(P);put(myCost/40);put(pieceSteps(P)/40);put(Math.min(...P.pieces.map(stepsOf))/40);put(playerDone(P)?1:0);put(P.blocks.length/3);
  const mix={j:0,w:0,v:0,r:0,c:0};for(const k of P.pieces){if(k==='done')continue;const m=bd.mix.get(k);if(m)for(const s in mix)mix[s]+=m[s];}
  for(const s of'jwvrc')put(mix[s]/P.pieces.length/20);
  put(myTurn?1:0);put(((me-S.start+n)%n)/3);put(S.turn&&S.cur===me&&S.turn.bought?1:0);put(n===2?1:0);
  // 3. my cards: hand (only meaningful on my turn), draw pile, discard, in play
  // hand: my cards on my turn; in the end-of-turn view, the cards I kept
  putArr(myTurn||endView?botCounts(P.hand):new Float32Array(BOT_NT),1/3);putArr(botCounts(P.deck),1/4);putArr(botCounts(P.discard),1/4);putArr(botCounts(P.play),1/3);
  // 4. this turn: leftover strength, pending removal, what the hand could still do
  if(myTurn){const a=S.turn.active;put(a?a.left/4:0);for(const s of'jwv')put(a&&a.sym===s?1:0);put(S.turn.pending?S.turn.pending.max/2:0);
    let coins=0;for(const id of P.hand)coins+=coinVal(id);put(coins/6);put(P.hand.length/6);put(P.hand.filter(id=>def(id).c==='p').length/2);
    let bestRed=0,sumRed=0;
    for(const id of P.hand){const d=def(id);if(d.c==='p')continue;let r=0;P.pieces.forEach((pk,pi)=>{if(pk==='done')return;const base=botCost(pk);for(const[k]of reach(me,pi,d.s==='*'?['j','w','v']:[d.s],d.p)){if(k[0]!=='B')r=Math.max(r,base-botCost(k));}});bestRed=Math.max(bestRed,r);sumRed+=r;}
    if(a){const pk=P.pieces[a.pi];if(pk!=='done'){const base=botCost(pk);for(const[k]of reach(me,a.pi,[a.sym],a.left))if(k[0]!=='B'){const r=base-botCost(k);bestRed=Math.max(bestRed,r);sumRed+=r;}}}
    put(bestRed/8);put(sumRed/12);put(myCost>0?Math.min(1,sumRed/myCost):1);put(1);
  }else i+=12;
  // 5. opponents in turn order after me: all cards they own, their discard pile, position, blockades
  for(let k=1;k<=3;k++){const j=(me+k)%n;const p=k<n?S.players[j]:null;if(!p){i+=BOT_NT*2+8;continue;}
    putArr(botCounts([...p.deck,...p.hand,...p.discard,...p.play]),1/4);putArr(botCounts(p.discard),1/4);
    put(pieceCost(p)/40);put(pieceSteps(p)/40);put(playerDone(p)?1:0);put(p.resigned?1:0);put(p.blocks.length/3);put(p.hand.length/6);put(j===S.cur?1:0);put((pieceCost(p)-myCost)/20);}
  // 6. market and reserve (cards left of each type) + reserve open
  const mk=new Float32Array(BOT_NT),rs=new Float32Array(BOT_NT);S.market.forEach(s=>{mk[BOT_TYPES.indexOf(s.t)]+=s.n;});S.reserve.forEach(s=>{rs[BOT_TYPES.indexOf(s.t)]+=s.n;});
  putArr(mk,1/3);putArr(rs,1/3);put(S.market.some(s=>s.n===0)?1:0);put(S.market.filter(s=>s.n>0).length/6);
  // 7. blockades #1–6: on the board / mine / someone else's, cost, where, type
  for(let num=1;num<=6;num++){const bi=S.blockades.findIndex(B=>B.n===num);if(bi<0){i+=9;continue;}const B=S.blockades[bi];
    const e=MAP.conns[B.conn].edges[0];put(B.owner===null?1:0);put(B.owner===me?1:0);put(B.owner!==null&&B.owner!==me?1:0);put(B.v/2);put(Math.min(stepsOf(e[0]),stepsOf(e[1]))/40);
    for(const s of'jwvr')put(B.k===s?1:0);}
  // 8. game clock
  put(S.round/40);put((n-2)/2);put(S.endTriggered?1:0);put(S.players.filter(p=>playerDone(p)).length/3);
  if(i!==BOT_NF)throw new Error('bot features: wrote '+i+' of '+BOT_NF);
  return f;
}
/* ---- values ---- */
function botHeuristic(me){ // hand-tuned: be close to the goal, own a strong deck, use this turn's cards well
  const P=S.players[me];if(playerDone(P))return 100-P.fin;
  const own=[...P.deck,...P.hand,...P.discard,...P.play],tot=own.length||1;let pw=0;
  for(const id of own){const d=CT[S.cards[id]];if(d.c!=='p')pw+=d.p*(d.c==='x'?1.2:1);else pw+=1.2;}
  let v=-P.pieces.reduce((a,k)=>a+botCost(k),0)/P.pieces.length;
  v+=pw/tot*9-Math.max(0,tot-12)*.35+P.blocks.length*1.5;
  if(S.cur===me&&!S.over&&S._endView!==me){let sumRed=0;
    for(const id of P.hand){const d=def(id);if(d.c==='p')continue;let r=0;P.pieces.forEach((pk,pi)=>{if(pk==='done')return;const base=botCost(pk);for(const[k]of reach(me,pi,d.s==='*'?['j','w','v']:[d.s],d.p))if(k[0]!=='B')r=Math.max(r,base-botCost(k));});sumRed+=r;}
    const a=S.turn.active;if(a&&P.pieces[a.pi]!=='done'){const base=botCost(P.pieces[a.pi]);let r=0;for(const[k]of reach(me,a.pi,[a.sym],a.left))if(k[0]!=='B')r=Math.max(r,base-botCost(k));sumRed+=r;}
    v+=sumRed*.95;}
  return v;
}
/* ---- per-map network input: the summary above + every space on this course + every tile connection ----
   Each space gets 4 slots (my explorer here / opponent 1, 2, 3 here, in turn order after me);
   each connection between tiles gets 8 (which blockade type was dealt there, its cost, owned by nobody / me / an opponent).
   The terrain itself never changes on a given course, so the network learns it per slot. */
function botMapOrder(){if(MAP._bo)return MAP._bo;const keys=[...MAP.hexes.keys()].filter(k=>MAP.hexes.get(k).type!=='m').sort();const idx=new Map(keys.map((k,i)=>[k,i]));MAP._bo={keys,idx};return MAP._bo;}
function botNetNF(){return BOT_NF+botMapOrder().keys.length*4+MAP.conns.length*8;}
function botNetFeatures(me){
  const{keys,idx}=botMapOrder(),n=S.players.length,f=new Float32Array(botNetNF());
  f.set(botFeatures(me),0);let o=BOT_NF;
  S.players.forEach((p,j)=>{const rel=(j-me+n)%n;if(rel>3)return;for(const k of p.pieces){if(k==='done')continue;const x=idx.get(k);if(x!=null)f[o+x*4+rel]=1;}});
  o+=keys.length*4;
  S.blockades.forEach(B=>{const c=o+B.conn*8;const t='jwvr'.indexOf(B.k);if(t>=0)f[c+t]=1;f[c+4]=B.v/2;f[c+5]=B.owner===null?1:0;f[c+6]=B.owner===me?1:0;f[c+7]=B.owner!==null&&B.owner!==me?1:0;});
  return f;
}
/* network: {course, nf, w1T (input-major, nf×h1), b1, w2 (h2×h1), b2, w3 (h2), b3}; leaky-ReLU, sigmoid out.
   The first layer only touches non-zero inputs (most board slots are empty), so it stays fast in the browser. */
let BOT_NET=null;
function botNetValue(f){const N=BOT_NET,H1=N.b1.length,H2=N.b2.length;const h1=Float32Array.from(N.b1);
  for(let k=0;k<f.length;k++){const x=f[k];if(x===0)continue;const r=k*H1,w=N.w1T;for(let j=0;j<H1;j++)h1[j]+=w[r+j]*x;}
  for(let j=0;j<H1;j++)if(h1[j]<0)h1[j]*=.01;
  let s=N.b3[0];for(let j=0;j<H2;j++){let a=N.b2[j];const r=j*H1;for(let k=0;k<H1;k++)a+=N.w2[r+k]*h1[k];s+=N.w3[j]*(a>0?a:.01*a);}
  return 1/(1+Math.exp(-s));}
const botNetReady=()=>!!(BOT_NET&&MAP&&BOT_NET.course===MAP.course&&BOT_NET.nf===botNetNF());
function botValue(me,mode){
  if(S.over){const pl=S.places[me],n=S.players.length;return mode==='net'?(n-pl)/(n-1):1e3-pl*100;}
  return mode==='net'&&botNetReady()?botNetValue(botNetFeatures(me)):botHeuristic(me);
}
/* ---- choose and play ---- */
/* fast structural copy of the game state (everything applyAction can change gets its own copy) */
function botClone(st){
  const t=st.turn;
  // cards (id → type) is shared: look-ahead only ever adds new ids, which the real game later overwrites with its own
  return{...st,log:[],trash:st.trash.slice(),
    players:st.players.map(p=>({...p,pieces:p.pieces.slice(),deck:p.deck.slice(),hand:p.hand.slice(),discard:p.discard.slice(),play:p.play.slice(),blocks:p.blocks.slice()})),
    market:st.market.map(x=>({...x})),reserve:st.reserve.map(x=>({...x})),blockades:st.blockades.map(b=>({...b})),
    turn:{...t,active:t.active&&{...t.active},pending:t.pending&&{...t.pending}},
    winners:st.winners&&st.winners.slice(),places:st.places&&st.places.slice()};
}
/* "My turn is over, next hand not drawn yet": played and unkept cards go to the discard pile.
   Scoring "end turn" here (instead of after the real draw) values it as an expectation over the draw, without peeking. */
function botEndView(me,keep){const P=S.players[me];keep=(keep||[]).filter(id=>P.hand.includes(id));
  P.discard.push(...P.play,...P.hand.filter(id=>!keep.includes(id)));P.play=[];P.hand=keep.slice();
  S.turn={bought:false,active:null,pending:null};S._endView=me;}
function botEndFeatures(me,keep){const root=S;S=botClone(root);botEndView(me,keep);const f=botNetFeatures(me);S=root;return f;}
const BOT_DRAW={cartographer:1,compass:1,scientist:1,travellog:1};
/* Pick an action. Each option is scored by the value network's estimate of my chance of finishing ahead
   from the position right after it (TD-Gammon / AlphaZero style; mid-turn positions include the cards still in hand).
   Chance is handled as an expectation: "end turn" is scored before the next hand is drawn (botEndView), and a card that
   draws is scored as the average over opts.draws imagined draws from my (unordered) draw pile.
   Training exploration: eps = uniformly random action; temp = softmax over scores; turnState.forceBuy = a random purchase this turn. */
function botChoose(opts){
  opts=opts||{};let mode=opts.mode||(BOT_NET?'net':'heur');const eps=opts.eps||0,rnd=opts.rnd||Math.random;
  const me=S.cur,root=S;let acts=botActions();if(mode==='net'&&!botNetReady())mode='heur';
  if(opts.turnState&&opts.turnState.noBuy){const f=acts.filter(a=>a.t!=='buy'&&a.t!=='transmit');if(f.length)acts=f;} // exploration: a turn without gaining a card
  if(eps&&rnd()<eps)return{a:acts[Math.floor(rnd()*acts.length)]};
  const ts=opts.turnState;
  if(ts&&ts.forceBuy&&!S.turn.bought){const buys=acts.filter(a=>a.t==='buy');if(buys.length){ts.forceBuy=false;return{a:buys[Math.floor(rnd()*buys.length)]};}}
  if(ts&&ts.forceTransmit){const tr=acts.filter(a=>a.t==='transmit');if(tr.length){ts.forceTransmit=false; // a random card, reserve included, weighted toward expensive ones (cost²)
    const w=tr.map(a=>{const s=a.src==='m'?S.market[a.idx]:S.reserve[a.idx];return CT[s.t].cost**2;});let r=rnd()*w.reduce((x,y)=>x+y,0);for(let i=0;i<tr.length;i++){r-=w[i];if(r<=0)return{a:tr[i]};}return{a:tr[tr.length-1]};}}
  const vals=[];let best=null,bv=-Infinity;const K=opts.draws||4;
  const one=a=>{S=botClone(root);shuffle(S.players[me].deck,rnd);let v;
    if(a.t==='end'){botEndView(me,a.keep);v=botValue(me,mode);}
    else{const r=applyAction(me,a);v=r.ok?botValue(me,mode):-Infinity;}
    S=root;return v;};
  for(const a of acts){
    let v=a.t==='action'&&BOT_DRAW[typeOf(a.card)]?[...Array(K)].reduce(x=>x+one(a),0)/K:one(a);
    if(opts.noise&&v>-Infinity)v+=(rnd()-.5)*opts.noise;
    vals.push(v);if(v>bv){bv=v;best=a;}
  }
  if(opts.temp&&acts.length>1){const w=vals.map(v=>v===-Infinity?0:Math.exp((v-bv)/opts.temp)),tot=w.reduce((x,y)=>x+y,0);let r=rnd()*tot;
    for(let i=0;i<acts.length;i++){r-=w[i];if(r<=0)return{a:acts[i],v:vals[i]};}}
  return{a:best||{t:'end',keep:[]},v:bv};
}
/* play one whole turn for the player to move (used by the UI and the simulator) */
function botTurn(opts){const me=S.cur;const steps=[];for(let g=0;g<40&&!S.over&&S.cur===me;g++){const{a}=botChoose(opts);const r=applyAction(me,a);steps.push(a);if(!r.ok){applyAction(me,{t:'end',keep:[]});break;}}return steps;}

/* ---- random courses for training (so the bot learns to play, not to memorise one map) ----
   Boards chained edge to edge, never touching non-neighbours; random sides and rotations;
   start board rotated so its start row faces away from the route; El Dorado on the far edge. */
function botRandomCourse(seed,nMid){
  const rnd=mulberry32(seed),TV=[[7,-3],[3,4],[-4,7],[-7,3],[-3,-4],[4,-7]],pairs=[['C','D'],['E','F'],['G','H'],['I','J'],['K','L'],['M','N']];
  for(let attempt=0;attempt<400;attempt++){
    const cs=[[0,0]];let ok=true,dir=Math.floor(rnd()*6);
    for(let b=0;b<nMid;b++){let placed=false;
      for(const dd of shuffle([0,1,-1,0,1,-1,2,-2],rnd)){const d=(dir+dd+6)%6,L=cs[cs.length-1],c=[L[0]+TV[d][0],L[1]+TV[d][1]];
        if(cs.some((p,j)=>(p[0]===c[0]&&p[1]===c[1])||(j<cs.length-1&&TV.some(v=>p[0]+v[0]===c[0]&&p[1]+v[1]===c[1]))))continue;
        cs.push(c);dir=d;placed=true;break;}
      if(!placed){ok=false;break;}}
    if(!ok)continue;
    const mids=shuffle(pairs.slice(),rnd).slice(0,nMid).map(p=>p[rnd()<.5?0:1]);
    const start=rnd()<.5?'A':'B';
    // start rotation: start row as far as possible from the next board
    let bestK=0,bestD=-1;const nx=pxOf(cs[1][0],cs[1][1]);
    for(let k=0;k<6;k++){const pts=TPL[start].filter(c=>c.d.type==='s').map(c=>rot(c.q,c.r,k));const m=pts.reduce((a,[q,r])=>{const[x,y]=pxOf(q,r);return a+Math.hypot(x-nx[0],y-nx[1]);},0);if(m>bestD){bestD=m;bestK=k;}}
    const p=[[start,0,0,bestK],...mids.map((L,j)=>[L,cs[j+1][0],cs[j+1][1],Math.floor(rnd()*6)])];
    // El Dorado: try spaces just beyond the last board, farthest from the previous one first
    const last=cs[cs.length-1],prev=cs[cs.length-2],cand=[];
    for(let dq=-4;dq<=4;dq++)for(let dr=-4;dr<=4;dr++){const q=last[0]+dq,r=last[1]+dr,dist=(Math.abs(dq)+Math.abs(dr)+Math.abs(dq+dr))/2;if(dist!==4)continue;
      const[x,y]=pxOf(q,r),[px,py]=pxOf(prev[0],prev[1]);cand.push([q,r,Math.hypot(x-px,y-py)]);}
    cand.sort((a,b)=>b[2]-a[2]);
    for(const[q,r]of cand.slice(0,8)){const C={id:'rnd'+seed,name:'Random '+seed,p,e:[q,r],s:rnd()<.5?'j':'w'};try{buildCourse(C,1);return C;}catch(e){}}
  }
  return null;
}

export const E={botRemaining,botEndFeatures,botClone,botRandomCourse,botNetFeatures,botNetNF,botNetValue,botChoose,botTurn,botActions,botFeatures,botValue,endGame,BOT_NF,setNet(n){BOT_NET=n},buildCourse,mapFor,COURSES,courseById,newGame,applyAction,resign,eloDeltas,redact,reach,payTargets,nativeTargets,playerDone,CT,get S(){return S},set S(v){S=v},get MAP(){return MAP},set MAP(v){MAP=v}};
